// zhao_probe_rcp24_rom -- DOES A 256-ARM CASE BECOME AN M10K IF YOU CLOCK IT?
//
// GENERATED by tools/quartus/gen_probe_rcp24_rom.py from
// fpga/rtl/field/zhao_field_rcp24_rom.sv. DO NOT EDIT. Re-run the
// generator; `--check` is a gate.
//
// ---------------------------------------------------------------------------
// THE QUESTION, AND WHY THE PHASE-3 REPORT GOT ITS SHAPE WRONG
// ---------------------------------------------------------------------------
// reports/PHASE3-THE-LEVER-IS-DUPLICATION-20260928.md calls
// `zhao_field_rcp24_rom` x13 "the sharpest row" and "the cheapest thing on
// this list to reason about, because a ROM has no state and no throughput
// contract -- only a read port count".
//
// THAT ROM HAS NO READ PORT AT ALL. It is a 256-arm `unique case` inside an
// `always_comb` -- a 256:1 mux over 31 bits, pure combinational logic, about
// 133 ALUTs per copy and 1,727 across thirteen. Quartus cannot infer memory
// from it because there is no memory to infer: no clock, no read port,
// nothing to register. "Add a pipeline stage at 13 call sites" was only half
// the blocker; the other half is that the table is not a table in RTL.
//
// So the lever turns on a question nobody has measured on THIS toolchain:
// given a registered read, does Quartus 17.0.2 infer an M10K from a CASE
// STATEMENT, or does it require an indexed ARRAY with an initialiser?
// The answer decides whether the fix is one pipeline stage or a structural
// rewrite of a generated file, and those are very different packets.
//
// ---------------------------------------------------------------------------
// THE FOUR STYLES. One map each; each measures exactly one thing.
// ---------------------------------------------------------------------------
//   STYLE=0  BASELINE. The shipped shape: combinational case, registered
//            OUTSIDE the table. Expect 0 M10K and ~133 ALUTs. If this does
//            not reproduce, the probe is not measuring the shipped block.
//   STYLE=1  THE QUESTION. The same case, moved INSIDE `always_ff`, so the
//            read is registered. Nothing else changes.
//   STYLE=2  THE DOCUMENTED FORM. An indexed array with an `initial`
//            initialiser and a clocked read -- what the Quartus handbook
//            shows for ROM inference.
//   STYLE=3  POSITIVE CONTROL. A plain 256x31 single-clock RAM, written and
//            read. THIS MUST REPORT M10K. If it does not, styles 0-2 say
//            nothing whatever -- the flow, the device or the probe is at
//            fault, not the shape. Never quote 0-2 without it.
//
// Read the result with tools/quartus/check_ram_inference.py, not by eye.
//
// The 256 constants below are a COPY, and their VALUES do not matter to the
// measurement -- only that they are INCOMPRESSIBLE. A synthetic table
// (`base + i*stride`) is arithmetic Quartus would compute rather than store,
// which would report a false negative for every style.

module zhao_probe_rcp24_rom #(
    parameter int unsigned STYLE = 0
) (
    input  logic        clk,
    input  logic        we_i,      // STYLE=3 only
    input  logic [ 7:0] idx_i,
    input  logic [30:0] wdata_i,   // STYLE=3 only
    output logic [30:0] seed_o
);

  // Quartus 17.0.2 rejects a bare module-scope elaboration check; it must
  // sit inside `initial begin ... end`. QUARTUS_GOTCHAS.md has the case.
  initial begin
    if (STYLE > 3) $fatal(1, "zhao_probe_rcp24_rom: STYLE=%0d is not 0..3", STYLE);
  end

  function automatic logic [30:0] rcp24_seed(input logic [7:0] i);
    unique case (i)
      8'd0  : rcp24_seed = 31'h7FC01FF0;
      8'd1  : rcp24_seed = 31'h7F411E53;
      8'd2  : rcp24_seed = 31'h7EC31843;
      8'd3  : rcp24_seed = 31'h7E460ADA;
      8'd4  : rcp24_seed = 31'h7DC9F339;
      8'd5  : rcp24_seed = 31'h7D4ECE90;
      8'd6  : rcp24_seed = 31'h7CD49A16;
      8'd7  : rcp24_seed = 31'h7C5B5311;
      8'd8  : rcp24_seed = 31'h7BE2F6CE;
      8'd9  : rcp24_seed = 31'h7B6B82A7;
      8'd10 : rcp24_seed = 31'h7AF4F3FE;
      8'd11 : rcp24_seed = 31'h7A7F4841;
      8'd12 : rcp24_seed = 31'h7A0A7CE7;
      8'd13 : rcp24_seed = 31'h79968F70;
      8'd14 : rcp24_seed = 31'h79237D66;
      8'd15 : rcp24_seed = 31'h78B1445C;
      8'd16 : rcp24_seed = 31'h783FE1F0;
      8'd17 : rcp24_seed = 31'h77CF53C6;
      8'd18 : rcp24_seed = 31'h775F978C;
      8'd19 : rcp24_seed = 31'h76F0AAFA;
      8'd20 : rcp24_seed = 31'h76828BCE;
      8'd21 : rcp24_seed = 31'h761537D0;
      8'd22 : rcp24_seed = 31'h75A8ACD0;
      8'd23 : rcp24_seed = 31'h753CE8A5;
      8'd24 : rcp24_seed = 31'h74D1E92F;
      8'd25 : rcp24_seed = 31'h7467AC55;
      8'd26 : rcp24_seed = 31'h73FE3007;
      8'd27 : rcp24_seed = 31'h7395723B;
      8'd28 : rcp24_seed = 31'h732D70EE;
      8'd29 : rcp24_seed = 31'h72C62A25;
      8'd30 : rcp24_seed = 31'h725F9BEC;
      8'd31 : rcp24_seed = 31'h71F9C457;
      8'd32 : rcp24_seed = 31'h7194A17F;
      8'd33 : rcp24_seed = 31'h71303185;
      8'd34 : rcp24_seed = 31'h70CC7290;
      8'd35 : rcp24_seed = 31'h706962CD;
      8'd36 : rcp24_seed = 31'h70070070;
      8'd37 : rcp24_seed = 31'h6FA549B4;
      8'd38 : rcp24_seed = 31'h6F443CD9;
      8'd39 : rcp24_seed = 31'h6EE3D826;
      8'd40 : rcp24_seed = 31'h6E8419E7;
      8'd41 : rcp24_seed = 31'h6E25006E;
      8'd42 : rcp24_seed = 31'h6DC68A14;
      8'd43 : rcp24_seed = 31'h6D68B535;
      8'd44 : rcp24_seed = 31'h6D0B8037;
      8'd45 : rcp24_seed = 31'h6CAEE980;
      8'd46 : rcp24_seed = 31'h6C52EF7F;
      8'd47 : rcp24_seed = 31'h6BF790A9;
      8'd48 : rcp24_seed = 31'h6B9CCB74;
      8'd49 : rcp24_seed = 31'h6B429E60;
      8'd50 : rcp24_seed = 31'h6AE907EF;
      8'd51 : rcp24_seed = 31'h6A9006A9;
      8'd52 : rcp24_seed = 31'h6A37991A;
      8'd53 : rcp24_seed = 31'h69DFBDD4;
      8'd54 : rcp24_seed = 31'h6988736D;
      8'd55 : rcp24_seed = 31'h6931B880;
      8'd56 : rcp24_seed = 31'h68DB8BAC;
      8'd57 : rcp24_seed = 31'h6885EB96;
      8'd58 : rcp24_seed = 31'h6830D6E5;
      8'd59 : rcp24_seed = 31'h67DC4C46;
      8'd60 : rcp24_seed = 31'h67884A6A;
      8'd61 : rcp24_seed = 31'h6734D006;
      8'd62 : rcp24_seed = 31'h66E1DBD5;
      8'd63 : rcp24_seed = 31'h668F6C92;
      8'd64 : rcp24_seed = 31'h663D8100;
      8'd65 : rcp24_seed = 31'h65EC17E3;
      8'd66 : rcp24_seed = 31'h659B3006;
      8'd67 : rcp24_seed = 31'h654AC836;
      8'd68 : rcp24_seed = 31'h64FADF43;
      8'd69 : rcp24_seed = 31'h64AB7402;
      8'd70 : rcp24_seed = 31'h645C854B;
      8'd71 : rcp24_seed = 31'h640E11FB;
      8'd72 : rcp24_seed = 31'h63C018F0;
      8'd73 : rcp24_seed = 31'h6372990E;
      8'd74 : rcp24_seed = 31'h6325913C;
      8'd75 : rcp24_seed = 31'h62D90063;
      8'd76 : rcp24_seed = 31'h628CE570;
      8'd77 : rcp24_seed = 31'h62413F54;
      8'd78 : rcp24_seed = 31'h61F60D03;
      8'd79 : rcp24_seed = 31'h61AB4D73;
      8'd80 : rcp24_seed = 31'h6160FF9F;
      8'd81 : rcp24_seed = 31'h61172283;
      8'd82 : rcp24_seed = 31'h60CDB521;
      8'd83 : rcp24_seed = 31'h6084B67B;
      8'd84 : rcp24_seed = 31'h603C2597;
      8'd85 : rcp24_seed = 31'h5FF40180;
      8'd86 : rcp24_seed = 31'h5FAC4940;
      8'd87 : rcp24_seed = 31'h5F64FBE7;
      8'd88 : rcp24_seed = 31'h5F1E1886;
      8'd89 : rcp24_seed = 31'h5ED79E32;
      8'd90 : rcp24_seed = 31'h5E918C01;
      8'd91 : rcp24_seed = 31'h5E4BE10F;
      8'd92 : rcp24_seed = 31'h5E069C77;
      8'd93 : rcp24_seed = 31'h5DC1BD58;
      8'd94 : rcp24_seed = 31'h5D7D42D5;
      8'd95 : rcp24_seed = 31'h5D392C10;
      8'd96 : rcp24_seed = 31'h5CF57831;
      8'd97 : rcp24_seed = 31'h5CB22662;
      8'd98 : rcp24_seed = 31'h5C6F35CD;
      8'd99 : rcp24_seed = 31'h5C2CA5A0;
      8'd100: rcp24_seed = 31'h5BEA750D;
      8'd101: rcp24_seed = 31'h5BA8A344;
      8'd102: rcp24_seed = 31'h5B672F7D;
      8'd103: rcp24_seed = 31'h5B2618EC;
      8'd104: rcp24_seed = 31'h5AE55ECD;
      8'd105: rcp24_seed = 31'h5AA5005B;
      8'd106: rcp24_seed = 31'h5A64FCD2;
      8'd107: rcp24_seed = 31'h5A255375;
      8'd108: rcp24_seed = 31'h59E60383;
      8'd109: rcp24_seed = 31'h59A70C42;
      8'd110: rcp24_seed = 31'h59686CF7;
      8'd111: rcp24_seed = 31'h592A24EB;
      8'd112: rcp24_seed = 31'h58EC3369;
      8'd113: rcp24_seed = 31'h58AE97BB;
      8'd114: rcp24_seed = 31'h58715130;
      8'd115: rcp24_seed = 31'h58345F18;
      8'd116: rcp24_seed = 31'h57F7C0C6;
      8'd117: rcp24_seed = 31'h57BB758C;
      8'd118: rcp24_seed = 31'h577F7CC1;
      8'd119: rcp24_seed = 31'h5743D5BB;
      8'd120: rcp24_seed = 31'h57087FD4;
      8'd121: rcp24_seed = 31'h56CD7A68;
      8'd122: rcp24_seed = 31'h5692C4D2;
      8'd123: rcp24_seed = 31'h56585E71;
      8'd124: rcp24_seed = 31'h561E46A5;
      8'd125: rcp24_seed = 31'h55E47CD0;
      8'd126: rcp24_seed = 31'h55AB0056;
      8'd127: rcp24_seed = 31'h5571D09B;
      8'd128: rcp24_seed = 31'h5538ED06;
      8'd129: rcp24_seed = 31'h55005500;
      8'd130: rcp24_seed = 31'h54C807F3;
      8'd131: rcp24_seed = 31'h54900549;
      8'd132: rcp24_seed = 31'h54584C70;
      8'd133: rcp24_seed = 31'h5420DCD6;
      8'd134: rcp24_seed = 31'h53E9B5EC;
      8'd135: rcp24_seed = 31'h53B2D722;
      8'd136: rcp24_seed = 31'h537C3FEB;
      8'd137: rcp24_seed = 31'h5345EFBC;
      8'd138: rcp24_seed = 31'h530FE60B;
      8'd139: rcp24_seed = 31'h52DA224E;
      8'd140: rcp24_seed = 31'h52A4A3FF;
      8'd141: rcp24_seed = 31'h526F6A96;
      8'd142: rcp24_seed = 31'h523A7590;
      8'd143: rcp24_seed = 31'h5205C468;
      8'd144: rcp24_seed = 31'h51D1569D;
      8'd145: rcp24_seed = 31'h519D2BAD;
      8'd146: rcp24_seed = 31'h5169431A;
      8'd147: rcp24_seed = 31'h51359C64;
      8'd148: rcp24_seed = 31'h51023710;
      8'd149: rcp24_seed = 31'h50CF12A0;
      8'd150: rcp24_seed = 31'h509C2E9A;
      8'd151: rcp24_seed = 31'h50698A86;
      8'd152: rcp24_seed = 31'h503725EA;
      8'd153: rcp24_seed = 31'h50050050;
      8'd154: rcp24_seed = 31'h4FD31942;
      8'd155: rcp24_seed = 31'h4FA1704B;
      8'd156: rcp24_seed = 31'h4F7004F7;
      8'd157: rcp24_seed = 31'h4F3ED6D4;
      8'd158: rcp24_seed = 31'h4F0DE571;
      8'd159: rcp24_seed = 31'h4EDD305E;
      8'd160: rcp24_seed = 31'h4EACB72A;
      8'd161: rcp24_seed = 31'h4E7C7969;
      8'd162: rcp24_seed = 31'h4E4C76AC;
      8'd163: rcp24_seed = 31'h4E1CAE88;
      8'd164: rcp24_seed = 31'h4DED2092;
      8'd165: rcp24_seed = 31'h4DBDCC60;
      8'd166: rcp24_seed = 31'h4D8EB189;
      8'd167: rcp24_seed = 31'h4D5FCFA4;
      8'd168: rcp24_seed = 31'h4D31264B;
      8'd169: rcp24_seed = 31'h4D02B518;
      8'd170: rcp24_seed = 31'h4CD47BA6;
      8'd171: rcp24_seed = 31'h4CA67990;
      8'd172: rcp24_seed = 31'h4C78AE73;
      8'd173: rcp24_seed = 31'h4C4B19EE;
      8'd174: rcp24_seed = 31'h4C1DBB9D;
      8'd175: rcp24_seed = 31'h4BF09322;
      8'd176: rcp24_seed = 31'h4BC3A01C;
      8'd177: rcp24_seed = 31'h4B96E22D;
      8'd178: rcp24_seed = 31'h4B6A58F7;
      8'd179: rcp24_seed = 31'h4B3E041D;
      8'd180: rcp24_seed = 31'h4B11E343;
      8'd181: rcp24_seed = 31'h4AE5F60D;
      8'd182: rcp24_seed = 31'h4ABA3C22;
      8'd183: rcp24_seed = 31'h4A8EB527;
      8'd184: rcp24_seed = 31'h4A6360C3;
      8'd185: rcp24_seed = 31'h4A383E9F;
      8'd186: rcp24_seed = 31'h4A0D4E64;
      8'd187: rcp24_seed = 31'h49E28FBB;
      8'd188: rcp24_seed = 31'h49B8024E;
      8'd189: rcp24_seed = 31'h498DA5C8;
      8'd190: rcp24_seed = 31'h496379D6;
      8'd191: rcp24_seed = 31'h49397E24;
      8'd192: rcp24_seed = 31'h490FB25F;
      8'd193: rcp24_seed = 31'h48E61636;
      8'd194: rcp24_seed = 31'h48BCA957;
      8'd195: rcp24_seed = 31'h48936B72;
      8'd196: rcp24_seed = 31'h486A5C37;
      8'd197: rcp24_seed = 31'h48417B58;
      8'd198: rcp24_seed = 31'h4818C885;
      8'd199: rcp24_seed = 31'h47F04371;
      8'd200: rcp24_seed = 31'h47C7EBD0;
      8'd201: rcp24_seed = 31'h479FC154;
      8'd202: rcp24_seed = 31'h4777C3B3;
      8'd203: rcp24_seed = 31'h474FF2A1;
      8'd204: rcp24_seed = 31'h47284DD4;
      8'd205: rcp24_seed = 31'h4700D502;
      8'd206: rcp24_seed = 31'h46D987E3;
      8'd207: rcp24_seed = 31'h46B2662E;
      8'd208: rcp24_seed = 31'h468B6F9B;
      8'd209: rcp24_seed = 31'h4664A3E2;
      8'd210: rcp24_seed = 31'h463E02BE;
      8'd211: rcp24_seed = 31'h46178BE9;
      8'd212: rcp24_seed = 31'h45F13F1D;
      8'd213: rcp24_seed = 31'h45CB1C15;
      8'd214: rcp24_seed = 31'h45A5228D;
      8'd215: rcp24_seed = 31'h457F5242;
      8'd216: rcp24_seed = 31'h4559AAF0;
      8'd217: rcp24_seed = 31'h45342C55;
      8'd218: rcp24_seed = 31'h450ED630;
      8'd219: rcp24_seed = 31'h44E9A83E;
      8'd220: rcp24_seed = 31'h44C4A240;
      8'd221: rcp24_seed = 31'h449FC3F4;
      8'd222: rcp24_seed = 31'h447B0D1C;
      8'd223: rcp24_seed = 31'h44567D77;
      8'd224: rcp24_seed = 31'h443214C7;
      8'd225: rcp24_seed = 31'h440DD2CF;
      8'd226: rcp24_seed = 31'h43E9B750;
      8'd227: rcp24_seed = 31'h43C5C20D;
      8'd228: rcp24_seed = 31'h43A1F2CA;
      8'd229: rcp24_seed = 31'h437E494B;
      8'd230: rcp24_seed = 31'h435AC554;
      8'd231: rcp24_seed = 31'h433766AA;
      8'd232: rcp24_seed = 31'h43142D12;
      8'd233: rcp24_seed = 31'h42F11852;
      8'd234: rcp24_seed = 31'h42CE2830;
      8'd235: rcp24_seed = 31'h42AB5C74;
      8'd236: rcp24_seed = 31'h4288B4E4;
      8'd237: rcp24_seed = 31'h42663148;
      8'd238: rcp24_seed = 31'h4243D168;
      8'd239: rcp24_seed = 31'h4221950E;
      8'd240: rcp24_seed = 31'h41FF7C01;
      8'd241: rcp24_seed = 31'h41DD860C;
      8'd242: rcp24_seed = 31'h41BBB2F8;
      8'd243: rcp24_seed = 31'h419A0290;
      8'd244: rcp24_seed = 31'h4178749F;
      8'd245: rcp24_seed = 31'h415708EF;
      8'd246: rcp24_seed = 31'h4135BF4D;
      8'd247: rcp24_seed = 31'h41149784;
      8'd248: rcp24_seed = 31'h40F39161;
      8'd249: rcp24_seed = 31'h40D2ACB1;
      8'd250: rcp24_seed = 31'h40B1E941;
      8'd251: rcp24_seed = 31'h409146DF;
      8'd252: rcp24_seed = 31'h4070C559;
      8'd253: rcp24_seed = 31'h4050647E;
      8'd254: rcp24_seed = 31'h4030241B;
      8'd255: rcp24_seed = 31'h40100401;
      default: rcp24_seed = 31'h0;
    endcase
  endfunction

  // Explicit generate/endgenerate: Quartus 17.0.2 needs the keywords, while
  // both Verilator and slang accept the implicit form. GOTCHAS again.
  //
  // AND THE LINE ABOVE MUST NOT BEGIN WITH THE WORD "Verilator". A comment
  // whose FIRST WORD is `verilator` (any case) is parsed as a PRAGMA, so
  // `// Verilator and slang accept ...` is read as an unknown verilator
  // directive and is a hard BADVLTPRAGMA error, not a comment. This
  // generator emitted exactly that and the probe would not lint. The
  // shipped RTL says "both Verilator and slang" and is fine BY ACCIDENT --
  // one leading word is the whole difference.
  generate
    if (STYLE != 3) begin : g_tie_ctrl
      // `we_i` and `wdata_i` are declared in EVERY style so that the port
      // list is IDENTICAL across the four maps. Differing I/O would change
      // the pin and boundary accounting and make the rows incomparable,
      // which is the entire point of a sweep. Consumed with this tree's
      // own unused-sink idiom rather than waived, so -Wall stays on.
      wire unused_ctrl = &{1'b0, we_i, wdata_i};
    end
  endgenerate

  generate
    if (STYLE == 0) begin : g_comb_case
      // BASELINE -- the shipped shape. Combinational table, register after.
      logic [30:0] comb_c;
      always_comb comb_c = rcp24_seed(idx_i);
      always_ff @(posedge clk) seed_o <= comb_c;
    end else if (STYLE == 1) begin : g_sync_case
      // THE QUESTION -- identical table, registered read.
      always_ff @(posedge clk) seed_o <= rcp24_seed(idx_i);
    end else if (STYLE == 2) begin : g_sync_array
      // THE DOCUMENTED ROM FORM -- indexed array, initialised, clocked read.
      logic [30:0] tbl [0:255];
      initial begin
        for (int unsigned i = 0; i < 256; i++) tbl[i] = rcp24_seed(i[7:0]);
      end
      always_ff @(posedge clk) seed_o <= tbl[idx_i];
    end else begin : g_ram_control
      // POSITIVE CONTROL -- a plain RAM. MUST infer M10K.
      logic [30:0] ram [0:255];
      always_ff @(posedge clk) begin
        if (we_i) ram[idx_i] <= wdata_i;
        seed_o <= ram[idx_i];
      end
    end
  endgenerate

endmodule
