#!/usr/bin/env python3
"""Generate fpga/rtl/synth/zhao_probe_rcp24_rom.sv.

WHY THIS IS GENERATED RATHER THAN HAND-WRITTEN. The probe needs the REAL 256
constants from zhao_field_rcp24_rom.sv, and it needs them in four different
RTL shapes. A hand-written copy of a 256-entry table is the mutant-drift
pattern waiting to happen: a copy that goes stale in the flattering direction
while still looking authoritative. Generating it from the shipped ROM means the
copy cannot drift without this script being re-run, and `--check` makes that a
gate.

The constants' VALUES are irrelevant to what the probe measures -- only the
SHAPE is under test. But they must be INCOMPRESSIBLE: a synthetic table like
`tbl[i] = base + i*stride` is arithmetic Quartus can compute, so it would
never become memory no matter how it was written, and the probe would report a
false negative. That is why the real table is used.

Usage:
  python tools/quartus/gen_probe_rcp24_rom.py            # write
  python tools/quartus/gen_probe_rcp24_rom.py --check    # RC 1 if stale
"""
import re
import sys
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
SRC = ROOT / 'fpga' / 'rtl' / 'field' / 'zhao_field_rcp24_rom.sv'
OUT = ROOT / 'fpga' / 'rtl' / 'synth' / 'zhao_probe_rcp24_rom.sv'

ENTRY = re.compile(r"^\s*8'd(\d+)\s*:\s*seed_o\s*=\s*31'h([0-9A-Fa-f_]+);", re.M)


def read_table():
    text = SRC.read_text(encoding='utf-8')
    rows = {}
    for m in ENTRY.finditer(text):
        rows[int(m.group(1))] = m.group(2).replace('_', '').upper()
    # ANTI-VACUITY. A regex that silently matches nothing is this repository's
    # most-repeated broken instrument, and it always reads as good news.
    if len(rows) != 256:
        sys.exit(f'{SRC.name}: parsed {len(rows)} entries, expected 256 -- '
                 'the table shape changed and this parser did not')
    if sorted(rows) != list(range(256)):
        sys.exit('indices are not exactly 0..255')
    return [rows[i] for i in range(256)]


def emit(tbl):
    L = []
    a = L.append
    a('// zhao_probe_rcp24_rom -- DOES A 256-ARM CASE BECOME AN M10K IF YOU CLOCK IT?')
    a('//')
    a('// GENERATED by tools/quartus/gen_probe_rcp24_rom.py from')
    a('// fpga/rtl/field/zhao_field_rcp24_rom.sv. DO NOT EDIT. Re-run the')
    a('// generator; `--check` is a gate.')
    a('//')
    a('// ---------------------------------------------------------------------------')
    a('// THE QUESTION, AND WHY THE PHASE-3 REPORT GOT ITS SHAPE WRONG')
    a('// ---------------------------------------------------------------------------')
    a('// reports/PHASE3-THE-LEVER-IS-DUPLICATION-20260928.md calls')
    a('// `zhao_field_rcp24_rom` x13 "the sharpest row" and "the cheapest thing on')
    a('// this list to reason about, because a ROM has no state and no throughput')
    a('// contract -- only a read port count".')
    a('//')
    a('// THAT ROM HAS NO READ PORT AT ALL. It is a 256-arm `unique case` inside an')
    a('// `always_comb` -- a 256:1 mux over 31 bits, pure combinational logic, about')
    a('// 133 ALUTs per copy and 1,727 across thirteen. Quartus cannot infer memory')
    a('// from it because there is no memory to infer: no clock, no read port,')
    a('// nothing to register. "Add a pipeline stage at 13 call sites" was only half')
    a('// the blocker; the other half is that the table is not a table in RTL.')
    a('//')
    a('// So the lever turns on a question nobody has measured on THIS toolchain:')
    a('// given a registered read, does Quartus 17.0.2 infer an M10K from a CASE')
    a('// STATEMENT, or does it require an indexed ARRAY with an initialiser?')
    a('// The answer decides whether the fix is one pipeline stage or a structural')
    a('// rewrite of a generated file, and those are very different packets.')
    a('//')
    a('// ---------------------------------------------------------------------------')
    a('// THE FOUR STYLES. One map each; each measures exactly one thing.')
    a('// ---------------------------------------------------------------------------')
    a('//   STYLE=0  BASELINE. The shipped shape: combinational case, registered')
    a('//            OUTSIDE the table. Expect 0 M10K and ~133 ALUTs. If this does')
    a('//            not reproduce, the probe is not measuring the shipped block.')
    a('//   STYLE=1  THE QUESTION. The same case, moved INSIDE `always_ff`, so the')
    a('//            read is registered. Nothing else changes.')
    a('//   STYLE=2  THE DOCUMENTED FORM. An indexed array with an `initial`')
    a('//            initialiser and a clocked read -- what the Quartus handbook')
    a('//            shows for ROM inference.')
    a('//   STYLE=3  POSITIVE CONTROL. A plain 256x31 single-clock RAM, written and')
    a('//            read. THIS MUST REPORT M10K. If it does not, styles 0-2 say')
    a('//            nothing whatever -- the flow, the device or the probe is at')
    a('//            fault, not the shape. Never quote 0-2 without it.')
    a('//')
    a('// Read the result with tools/quartus/check_ram_inference.py, not by eye.')
    a('//')
    a('// The 256 constants below are a COPY, and their VALUES do not matter to the')
    a('// measurement -- only that they are INCOMPRESSIBLE. A synthetic table')
    a('// (`base + i*stride`) is arithmetic Quartus would compute rather than store,')
    a('// which would report a false negative for every style.')
    a('')
    a('module zhao_probe_rcp24_rom #(')
    a('    parameter int unsigned STYLE = 0')
    a(') (')
    a('    input  logic        clk,')
    a('    input  logic        we_i,      // STYLE=3 only')
    a('    input  logic [ 7:0] idx_i,')
    a('    input  logic [30:0] wdata_i,   // STYLE=3 only')
    a('    output logic [30:0] seed_o')
    a(');')
    a('')
    a('  // Quartus 17.0.2 rejects a bare module-scope elaboration check; it must')
    a('  // sit inside `initial begin ... end`. QUARTUS_GOTCHAS.md has the case.')
    a('  initial begin')
    a('    if (STYLE > 3) $fatal(1, "zhao_probe_rcp24_rom: STYLE=%0d is not 0..3", STYLE);')
    a('  end')
    a('')
    a('  function automatic logic [30:0] rcp24_seed(input logic [7:0] i);')
    a('    unique case (i)')
    for i, v in enumerate(tbl):
        a(f"      8'd{i:<3}: rcp24_seed = 31'h{v};")
    a("      default: rcp24_seed = 31'h0;")
    a('    endcase')
    a('  endfunction')
    a('')
    a('  // Explicit generate/endgenerate: Quartus 17.0.2 needs the keywords, while')
    a('  // both Verilator and slang accept the implicit form. GOTCHAS again.')
    a('  //')
    a('  // AND THE LINE ABOVE MUST NOT BEGIN WITH THE WORD "Verilator". A comment')
    a('  // whose FIRST WORD is `verilator` (any case) is parsed as a PRAGMA, so')
    a('  // `// Verilator and slang accept ...` is read as an unknown verilator')
    a('  // directive and is a hard BADVLTPRAGMA error, not a comment. This')
    a('  // generator emitted exactly that and the probe would not lint. The')
    a('  // shipped RTL says "both Verilator and slang" and is fine BY ACCIDENT --')
    a('  // one leading word is the whole difference.')
    a('  generate')
    a('    if (STYLE != 3) begin : g_tie_ctrl')
    a('      // `we_i` and `wdata_i` are declared in EVERY style so that the port')
    a('      // list is IDENTICAL across the four maps. Differing I/O would change')
    a('      // the pin and boundary accounting and make the rows incomparable,')
    a('      // which is the entire point of a sweep. Consumed with this tree\'s')
    a('      // own unused-sink idiom rather than waived, so -Wall stays on.')
    a('      wire unused_ctrl = &{1\'b0, we_i, wdata_i};')
    a('    end')
    a('  endgenerate')
    a('')
    a('  generate')
    a('    if (STYLE == 0) begin : g_comb_case')
    a('      // BASELINE -- the shipped shape. Combinational table, register after.')
    a('      logic [30:0] comb_c;')
    a('      always_comb comb_c = rcp24_seed(idx_i);')
    a('      always_ff @(posedge clk) seed_o <= comb_c;')
    a('    end else if (STYLE == 1) begin : g_sync_case')
    a('      // THE QUESTION -- identical table, registered read.')
    a('      always_ff @(posedge clk) seed_o <= rcp24_seed(idx_i);')
    a('    end else if (STYLE == 2) begin : g_sync_array')
    a('      // THE DOCUMENTED ROM FORM -- indexed array, initialised, clocked read.')
    a('      logic [30:0] tbl [0:255];')
    a('      initial begin')
    a('        for (int unsigned i = 0; i < 256; i++) tbl[i] = rcp24_seed(i[7:0]);')
    a('      end')
    a('      always_ff @(posedge clk) seed_o <= tbl[idx_i];')
    a('    end else begin : g_ram_control')
    a('      // POSITIVE CONTROL -- a plain RAM. MUST infer M10K.')
    a('      logic [30:0] ram [0:255];')
    a('      always_ff @(posedge clk) begin')
    a('        if (we_i) ram[idx_i] <= wdata_i;')
    a('        seed_o <= ram[idx_i];')
    a('      end')
    a('    end')
    a('  endgenerate')
    a('')
    a('endmodule')
    return '\n'.join(L) + '\n'


def main():
    tbl = read_table()
    text = emit(tbl)
    if '--check' in sys.argv:
        if not OUT.exists():
            print(f'MISSING: {OUT.relative_to(ROOT)}')
            return 1
        cur = OUT.read_text(encoding='utf-8')
        if cur.replace('\r\n', '\n') != text:
            print(f'STALE: {OUT.relative_to(ROOT)} -- re-run this generator')
            return 1
        print(f'fresh: {OUT.relative_to(ROOT)} (256 entries)')
        return 0
    OUT.write_text(text, encoding='utf-8', newline='\n')
    print(f'wrote {OUT.relative_to(ROOT)} ({len(text.splitlines())} lines, 256 entries)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
