#!/usr/bin/env python3
"""gen_jitter_rom.py -- JITTER_Q16, the FORGE.PRIM.EVAL sideways-kink table.

GENERATED, NOT TRANSCRIBED, both directions -- the same law as SIN_Q16
(fpga/rtl/field/zhao_field_sin_rom.sv): 256 hand-copied constants is where a
silent error hides, and a wrong jitter entry does not fail loudly, it puts one
kink slightly off, which reads as a style choice rather than a break.

THE FORMULA LIVES HERE AND NOWHERE ELSE. This script emits BOTH consumers:

    fpga/rtl/forge/zhao_forge_jitter_rom.sv            (the M10K table)
    reference/include/zref/generated/zref_forge_jitter_table.hpp  (the oracle)

so the two cannot drift from each other without drifting from this file, and
tests/forge/forge_jitter_rom_directed.cpp checks every RTL entry against the
generated header -- a generated file goes stale as easily as a copied one,
because the generator is not run by the build.

WHY A TABLE AT ALL: the console is in an ALM/DSP rescue (41,910 ALM /
58,359 counted; 112 DSP / 192). Jitter values resident in one M10K
(256 x 18 bit = 4,608 bits of a 10,240-bit block; 553 M10K owned, ~147 used)
cost a resource the machine has in abundance instead of multipliers it does
not have. The hash that INDEXES the table is xorshift32 -- shifts and xors,
zero multipliers.

THE DISTRIBUTION: uniform over the full fx16 unit range [-1.0, +1.0), i.e.
raw [-65536, +65535]. Entry k is two xorshift32 rounds over a Weyl-scrambled
k, so neighbouring indices are decorrelated. If the owner ever wants a
different CHARACTER of lightning (e.g. triangular-distributed, calmer kinks),
this formula is the one knob to retune: regenerate, re-run the directed test,
done. Do not hand-edit the outputs.

Deterministic: no RNG state, no time, no environment. Same output every run.
"""

from __future__ import annotations

import os

ENTRIES = 256
MASK = 0xFFFFFFFF

# Named constants of the formula. Change here, regenerate, never in the output.
WEYL_MUL = 2654435761          # Knuth multiplicative hash constant (2^32/phi)
WEYL_ADD = 0x9E3779B9          # golden-ratio salt so entry 0 is not trivial


def xorshift32(h: int) -> int:
    h ^= (h << 13) & MASK
    h ^= h >> 17
    h ^= (h << 5) & MASK
    return h & MASK


def entry(k: int) -> int:
    """Signed fx16 jitter value in [-65536, +65535] for table index k."""
    h = (k * WEYL_MUL + WEYL_ADD) & MASK
    h = xorshift32(xorshift32(h))
    return (h & 0x1FFFF) - 65536


def repo_root() -> str:
    return os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))


def emit_sv(vals: list[int]) -> str:
    lines = []
    lines.append("// zhao_forge_jitter_rom.sv - JITTER_Q16, the FORGE.PRIM.EVAL kink table.")
    lines.append("//")
    lines.append("// GENERATED by tools/forge/gen_jitter_rom.py -- DO NOT HAND-EDIT.")
    lines.append("// The formula lives in the generator; this file and the zref header")
    lines.append("// (reference/include/zref/generated/zref_forge_jitter_table.hpp) are its")
    lines.append("// two emissions, and tests/forge/forge_jitter_rom_directed.cpp checks every")
    lines.append("// entry of this one against that one.")
    lines.append("//")
    lines.append("// 256 entries, signed fx16 in [-1.0, +1.0) (raw [-65536, +65535], 18 bits).")
    lines.append("// Uniform. Indexed by the low 8 bits of the evaluator's xorshift32 stream.")
    lines.append("//")
    lines.append("// THE SHAPE THAT INFERS M10K (QUARTUS_GOTCHAS S10, same as")
    lines.append("// zhao_field_sin_rom): one array, synchronous dual read, NO reset anywhere")
    lines.append("// near `tbl` or the outputs -- a reset would hand the entries back to logic.")
    lines.append("// 256 x 18 = 4,608 bits, well inside one 10,240-bit M10K in x18 mode.")
    lines.append("`default_nettype none")
    lines.append("")
    lines.append("module zhao_forge_jitter_rom (")
    lines.append("    input  logic        clk,")
    lines.append("    input  logic [7:0]  idx_a_i,")
    lines.append("    input  logic [7:0]  idx_b_i,")
    lines.append("    output logic [17:0] val_a_o,   // signed fx16, sign in bit 17")
    lines.append("    output logic [17:0] val_b_o")
    lines.append(");")
    lines.append("")
    lines.append("  logic [17:0] tbl [0:255];")
    lines.append("")
    lines.append("  initial begin")
    for k, v in enumerate(vals):
        raw = v & 0x3FFFF  # two's complement in 18 bits
        lines.append("    tbl[%3d] = 18'h%05X;" % (k, raw))
    lines.append("  end")
    lines.append("")
    lines.append("  always_ff @(posedge clk) begin")
    lines.append("    val_a_o <= tbl[idx_a_i];")
    lines.append("    val_b_o <= tbl[idx_b_i];")
    lines.append("  end")
    lines.append("")
    lines.append("endmodule : zhao_forge_jitter_rom")
    lines.append("")
    lines.append("`default_nettype wire")
    lines.append("")
    return "\n".join(lines)


def emit_hpp(vals: list[int]) -> str:
    lines = []
    lines.append("// zref_forge_jitter_table.hpp -- JITTER_Q16, the oracle's copy.")
    lines.append("//")
    lines.append("// GENERATED by tools/forge/gen_jitter_rom.py -- DO NOT HAND-EDIT.")
    lines.append("// See the generator header for the formula and the reason it lives there.")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <cstdint>")
    lines.append("")
    lines.append("namespace zref {")
    lines.append("namespace forge {")
    lines.append("")
    lines.append("constexpr int kEvalJitterEntries = %d;" % len(vals))
    lines.append("")
    lines.append("constexpr int32_t kEvalJitterTable[%d] = {" % len(vals))
    for base in range(0, len(vals), 8):
        row = ", ".join("%6d" % v for v in vals[base:base + 8])
        lines.append("    " + row + ",")
    lines.append("};")
    lines.append("")
    lines.append("}  // namespace forge")
    lines.append("}  // namespace zref")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    vals = [entry(k) for k in range(ENTRIES)]
    lo, hi = min(vals), max(vals)
    assert -65536 <= lo and hi <= 65535, (lo, hi)
    # Self-check: the formula must actually vary (a broken instrument reads
    # constant), and must hit both signs.
    assert len(set(vals)) > 200, "table degenerate: %d distinct" % len(set(vals))
    assert lo < 0 < hi, "table one-sided"

    root = repo_root()
    sv_path = os.path.join(root, "fpga", "rtl", "forge", "zhao_forge_jitter_rom.sv")
    hpp_path = os.path.join(root, "reference", "include", "zref", "generated",
                            "zref_forge_jitter_table.hpp")
    with open(sv_path, "w", newline="\n") as f:
        f.write(emit_sv(vals))
    with open(hpp_path, "w", newline="\n") as f:
        f.write(emit_hpp(vals))
    print("wrote %s (%d entries, min %d, max %d)" % (sv_path, ENTRIES, lo, hi))
    print("wrote %s" % hpp_path)


if __name__ == "__main__":
    main()
