import assert from 'node:assert/strict';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import test from 'node:test';

import { emitCpp } from '../../src/backends/index.js';
import { compileFrontend } from '../../src/frontend/index.js';
import { lowerHir } from '../../src/hir/index.js';
import { lowerZir } from '../../src/zir/index.js';
import { repoRoot } from '../helpers.js';

function compileFixture(reverse = false) {
  const dir = path.join(repoRoot(), 'compiler', 'tests', 'form', 'fixture');
  const files = ['a_arena.form', 'b_audit.form'];
  if (reverse) files.reverse();
  const sources = Object.fromEntries(files.map((file) => [file, readFileSync(path.join(dir, file), 'utf8')]));
  const frontend = compileFrontend(sources);
  assert.equal(frontend.ok, true, frontend.diagnostics.map((item) => `${item.code}: ${item.message}`).join('\n'));
  const hir = lowerHir(frontend);
  assert.ok(hir);
  return emitCpp(hir, lowerZir(hir));
}

function byPath(output: ReturnType<typeof compileFixture>, name: string): string {
  const file = output.files.find((item) => item.path.endsWith(name));
  assert.ok(file, `missing emitted ${name}`);
  return file.content;
}

test('C++17 emission is byte-stable, module-partitioned, and phase-flat', () => {
  const first = compileFixture(false);
  const second = compileFixture(true);
  assert.deepEqual(first, second);
  assert.deepEqual(first.files.map((file) => file.path), [
    'generated/form/arena.cpp',
    'generated/form/arena.hpp',
    'generated/form/audit.cpp',
    'generated/form/audit.hpp',
    'generated/form/form_game.hpp',
    'generated/form/form_types.hpp',
  ]);
  assert.ok(first.files.every((file) => file.content.startsWith('// Generated by Form C++ backend v1; DO NOT EDIT.\n')));
  assert.ok(first.files.every((file) => file.content.endsWith('\n') && !file.content.includes('\r')));

  const arena = byPath(first, 'arena.hpp');
  assert.match(arena, /namespace form::arena \{/);
  assert.match(arena, /std::array<World3, capacity> position/);
  assert.match(arena, /std::array<u32, capacity> age/);
  const game = byPath(first, 'form_game.hpp');
  assert.match(game, /struct FormState \{/);
  assert.match(game, /inline void sim_tick\(FormState& state, const PadFrame pads\[4\], u32 tick\)/);
  assert.match(game, /inline void present_frame\(const FormState& state, zref::FrameBuilder& builder\)/);
  assert.match(game, /inline u32 sim_hash\(u32 previous, const FormState& state\)/);
  const seed = game.indexOf('arena::system_seed_wave');
  const observe = game.indexOf('audit::system_observe');
  const advance = game.indexOf('arena::system_advance');
  assert.ok(seed >= 0 && seed < observe && observe < advance);
  assert.match(game, /if \(\(tick % 2u\) == 0u\) arena::system_seed_wave/);
  assert.match(game, /if \(\(tick % 4u\) == 0u\) arena::system_advance/);
  assert.match(byPath(first, 'arena.cpp'), /if \(\(i % 4u\) == \(tick % 4u\)\)/);
});

test('emitted deterministic source has no forbidden numeric or host-clock surface', () => {
  const output = compileFixture();
  const forbidden = /\b(?:float|double)\b|<cmath>|\b(?:chrono|clock_gettime|system_clock|steady_clock|gettimeofday)\b/;
  for (const file of output.files) {
    assert.doesNotMatch(file.content, forbidden, file.path);
    assert.doesNotMatch(file.content, /\bwhile\s*\(|\bgoto\b/, file.path);
  }
});

test('C++ backend refuses field applications until W3.4 supplies the physical wrapper', () => {
  const frontend = compileFrontend({
    'field_user.form': `module field_user {
  @earth field lift_ground() -> terrain_delta
    footprint circle(0m, 0m, 4m);
    max_ops 16
  {
    let d = dist(sample.x, sample.z, 0m, 0m);
    return terrain_delta { height = d, velocity = 0m, material = 0, nav_cost = 0m };
  }
  system apply_earth every 1 ticks reads writes terrain {
    apply terrain_field lift_ground(origin: world2 { x = 0w, y = 0w }) duration 45t;
  }
}
`,
  });
  assert.equal(frontend.ok, true, frontend.diagnostics.map((item) => `${item.code}: ${item.message}`).join('\n'));
  const hir = lowerHir(frontend);
  assert.ok(hir);
  assert.throws(
    () => emitCpp(hir, lowerZir(hir)),
    /cannot emit terrain_field application 'lift_ground'.*W3\.4 supplies its validated physical Field IR wrapper/,
  );
});

test('WinLibs compiles and runs generated C++17 state/hash smoke', (t) => {
  const compiler = 'C:/programmieren/dsstuff/mingw64/bin/g++.exe';
  if (!existsSync(compiler)) {
    t.skip(`WinLibs compiler absent: ${compiler}`);
    return;
  }
  const output = compileFixture();
  const root = mkdtempSync(path.join(tmpdir(), 'form-cpp-'));
  try {
    const generated = path.join(root, 'generated', 'form');
    mkdirSync(generated, { recursive: true });
    for (const file of output.files) {
      const target = path.join(root, ...file.path.split('/'));
      mkdirSync(path.dirname(target), { recursive: true });
      writeFileSync(target, file.content, { encoding: 'utf8' });
    }
    const smoke = path.join(root, 'smoke.cpp');
    writeFileSync(smoke, `#include "form_game.hpp"
#include <cstdio>
int main() {
  form::FormState state{};
  form::PadFrame pads[4]{};
  const form::u32 cartridge = 0x13579bdfu;
  form::initialize(state, cartridge);
  form::u32 chain = form::sim_hash_initial(cartridge);
  for (form::u32 tick = 0u; tick < 8u; ++tick) {
    form::sim_tick(state, pads, tick);
    chain = form::sim_hash(chain, state);
  }
  const form::u32 before = form::sim_hash(0x2468ace0u, state);
  state.audit.observed += 1u;
  const form::u32 after = form::sim_hash(0x2468ace0u, state);
  if (state.arena.particles.count != 4u || state.arena.particles.age[0] != 2u) return 2;
  if (state.arena.counter != 1u || state.audit.observed != 2u || before == after) return 3;
  std::printf("%08x %08x %08x\\n", chain, before, after);
  return 0;
}
`, 'utf8');
    const executable = path.join(root, 'smoke.exe');
    const repo = repoRoot();
    const args = [
      '-std=c++17', '-O2', '-Wall', '-Wextra',
      `-I${generated}`,
      `-I${path.join(repo, 'runtime', 'include')}`,
      `-I${path.join(repo, 'reference', 'include')}`,
      path.join(generated, 'arena.cpp'),
      path.join(generated, 'audit.cpp'),
      path.join(repo, 'reference', 'src', 'zref_frame.cpp'),
      smoke, '-o', executable,
    ];
    const build = spawnSync(compiler, args, { encoding: 'utf8', windowsHide: true });
    assert.equal(build.status, 0, `${build.stdout}\n${build.stderr}`);
    const run = spawnSync(executable, [], { encoding: 'utf8', windowsHide: true });
    assert.equal(run.status, 0, `${run.stdout}\n${run.stderr}`);
    assert.equal(run.stdout.replaceAll('\r', ''), '6b636786 0b2ee995 690c60ac\n');
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});
