"""register_candidate.py -- the three design-file edits for the FORGE.CLIFF
bitmap-RAM candidate, kept as a script so the exact text is on record:

  design/prod_manifest.yml   the candidate declared absent (not-yet-adopted)
  design/fit_targets.yml     fit gate F-CLIFF1 named, with its one question
  tests/CMakeLists.txt       seven test targets registered after the golden's

Each edit is anchored on a unique existing line and refuses to apply twice.
Run from the zhaozhou root.
"""
import sys


def patch(path, anchor, addition):
    s = open(path, encoding='utf-8').read()
    if addition.strip().splitlines()[0] in s:
        print(f"{path}: already applied")
        return
    assert s.count(anchor) == 1, f"{path}: anchor not unique/missing"
    open(path, 'w', encoding='utf-8').write(s.replace(anchor, anchor + addition))
    print(f"{path}: patched")


# ---- prod_manifest.yml -------------------------------------------------------
patch('design/prod_manifest.yml',
      "  - zhao_forge_jitter_rom: not-yet-adopted  JITTER_Q16 table (generated by tools/forge/gen_jitter_rom.py), instantiated by zhao_forge_prim_eval only; adopted the moment its parent is\n",
      "  - zhao_forge_cliff_ram: not-yet-adopted  the FORGE.CLIFF bitmap-RAM CANDIDATE beside the golden (ALM-Liberation Roadmap s6 / s14 Commit6; reports/FORGE-CLIFF-BITMAP-RAM-20260910.md): same law, same ports plus walk_fault_o, the 34x34 SOLID window in one RAM behind three row registers and the 2,048-bit alive bitmap deleted by span-walk compaction; the golden directed+random suites pass UNMODIFIED against it and tests/forge/forge_cliff_ram_differential.cpp is bit-identical to golden and oracle on 752 pages with three committed mutants seen to fail; declared register bits 3,646 -> 630 is ARITHMETIC, the ALM saving is UNKNOWN until fit gate F-CLIFF1 (design/fit_targets.yml) maps it; adopt in place of zhao_forge_cliff only after that gate\n")

# ---- fit_targets.yml -----------------------------------------------------------
patch('design/fit_targets.yml',
      """  - top: zhao_forge_cliff
    sources:
      - fpga/rtl/forge/zhao_forge_cliff.sv

""",
      """  # FORGE.CLIFF bitmap-RAM candidate -- fit gate F-CLIFF1 (ALM-Liberation Roadmap
  # s6 / s14 Commit6; reports/FORGE-CLIFF-BITMAP-RAM-20260910.md). Batched with
  # the next forge-subsystem map per the 2026-09-08 batching law; it is a
  # quartus_map, not a full fit. Its ONE question: with the 34x34 SOLID window
  # as a 34-word RAM behind three row registers and the alive bitmap deleted,
  # (a) does `inferredMemories` list FIVE memories -- win_mem 34x34 (M10K or
  # MLAB, either is fine; flip-flops is the failure) plus the golden's four
  # payload tables still SDP at 2048x12 / 2048x6 / 2048x32 / 1024x17, with
  # ramConversionWarnings 0 -- and (b) what are the estimated ALM, comb ALUT
  # and register counts against the golden's map-only 7,664 / 8,149 / 3,875?
  # The golden's row is an ESTIMATE, so the delta this gate produces is an
  # estimate-to-estimate comparison (same tool, same stage, same device) and
  # settles the STRUCTURE (did 3,204 bitmap flops and their cones leave, did
  # the tables stay RAM, did the extra write sites break the async-read
  # rescue), not a fitted ALM number. Declared register bits 3,646 -> 630 is
  # arithmetic from the source and needs no Quartus. Correctness, cycle counts,
  # handshakes and the compaction's same-address suppression are Verilator's
  # (tests/forge/forge_cliff_ram_differential.cpp) and do not need this gate.
  - top: zhao_forge_cliff_ram
    sources:
      - fpga/rtl/forge/zhao_forge_cliff_ram.sv

""")

# ---- tests/CMakeLists.txt ------------------------------------------------------
patch('tests/CMakeLists.txt',
      """add_test(NAME forge_cliff_random_nightly COMMAND test_forge_cliff_random --nightly)
set_tests_properties(forge_cliff_random_nightly PROPERTIES LABELS "nightly" TIMEOUT 3600)
""",
      """
# ---- FORGE.CLIFF bitmap-RAM CANDIDATE (Roadmap s14 Commit6) ------------------
# zhao_forge_cliff_ram beside the golden: the 34x34 SOLID window in one RAM
# behind three row registers, the alive bitmap deleted by span-walk
# compaction, the algorithm untouched. Three kinds of evidence, each a target:
#   1. the golden suites UNMODIFIED against the candidate -- the candidate is
#      verilated under the golden's PREFIX so the suites compile untouched;
#   2. the three-way differential (oracle / golden / candidate in ONE process,
#      752 pages, cycle counts printed) -- two verilate() calls on one target;
#   3. the committed mutants with inverted-polarity controls: two fire the
#      candidate's walk_fault_o (zero span / overshoot), one shows the
#      differential FAILING on a prefetch one row off.
set(ZHAO_FORGE_CLIFF_RAM_SV
    ${CMAKE_SOURCE_DIR}/fpga/rtl/forge/zhao_forge_cliff_ram.sv)

add_test(NAME lint_forge_cliff_ram
         COMMAND "${ZHAO_VERILATOR_LINT}" --lint-only -Wall
                 --top-module zhao_forge_cliff_ram
                 ${ZHAO_FORGE_CLIFF_RAM_SV})
set_tests_properties(lint_forge_cliff_ram PROPERTIES
  LABELS "lint;fast"
  ENVIRONMENT "VERILATOR_ROOT=${VERILATOR_ROOT}")

add_executable(test_forge_cliff_ram_directed forge/forge_cliff_directed.cpp)
target_link_libraries(test_forge_cliff_ram_directed PRIVATE zhao_harness zhao_zref)
target_include_directories(test_forge_cliff_ram_directed PRIVATE
  ${CMAKE_CURRENT_SOURCE_DIR}/forge)
verilate(test_forge_cliff_ram_directed
  PREFIX Vzhao_forge_cliff
  TOP_MODULE zhao_forge_cliff_ram
  SOURCES ${ZHAO_FORGE_CLIFF_RAM_SV})
add_test(NAME forge_cliff_ram_directed COMMAND test_forge_cliff_ram_directed)
set_tests_properties(forge_cliff_ram_directed PROPERTIES LABELS "fast;nightly" TIMEOUT 1800)

add_executable(test_forge_cliff_ram_random forge/forge_cliff_random.cpp)
target_link_libraries(test_forge_cliff_ram_random PRIVATE zhao_harness zhao_zref)
target_include_directories(test_forge_cliff_ram_random PRIVATE
  ${CMAKE_CURRENT_SOURCE_DIR}/forge)
verilate(test_forge_cliff_ram_random
  PREFIX Vzhao_forge_cliff
  TOP_MODULE zhao_forge_cliff_ram
  SOURCES ${ZHAO_FORGE_CLIFF_RAM_SV})
add_test(NAME forge_cliff_ram_random COMMAND test_forge_cliff_ram_random)
set_tests_properties(forge_cliff_ram_random PROPERTIES LABELS "fast;nightly" TIMEOUT 1800)

add_executable(test_forge_cliff_ram_differential forge/forge_cliff_ram_differential.cpp)
target_link_libraries(test_forge_cliff_ram_differential PRIVATE zhao_harness zhao_zref)
target_include_directories(test_forge_cliff_ram_differential PRIVATE
  ${CMAKE_CURRENT_SOURCE_DIR}/forge)
verilate(test_forge_cliff_ram_differential
  PREFIX Vzhao_forge_cliff
  TOP_MODULE zhao_forge_cliff
  VERILATOR_ARGS --assert
  SOURCES ${ZHAO_FORGE_CLIFF_SV})
verilate(test_forge_cliff_ram_differential
  PREFIX Vzhao_forge_cliff_ram
  TOP_MODULE zhao_forge_cliff_ram
  VERILATOR_ARGS --assert
  SOURCES ${ZHAO_FORGE_CLIFF_RAM_SV})
add_test(NAME forge_cliff_ram_differential COMMAND test_forge_cliff_ram_differential)
set_tests_properties(forge_cliff_ram_differential PROPERTIES LABELS "fast;nightly" TIMEOUT 1800)
add_test(NAME forge_cliff_ram_differential_nightly COMMAND test_forge_cliff_ram_differential --nightly)
set_tests_properties(forge_cliff_ram_differential_nightly PROPERTIES LABELS "nightly" TIMEOUT 3600)

# the mutants: each verilated under the golden's PREFIX so the shared driver
# header compiles; each control PASSES when the instrument FIRES.
foreach(mut IN ITEMS mutant over_mutant)
  add_executable(test_forge_cliff_ram_${mut}_control forge/forge_cliff_ram_mutant_control.cpp)
  target_link_libraries(test_forge_cliff_ram_${mut}_control PRIVATE zhao_harness zhao_zref)
  target_include_directories(test_forge_cliff_ram_${mut}_control PRIVATE
    ${CMAKE_CURRENT_SOURCE_DIR}/forge)
  verilate(test_forge_cliff_ram_${mut}_control
    PREFIX Vzhao_forge_cliff
    TOP_MODULE zhao_forge_cliff_ram_${mut}
    VERILATOR_ARGS --assert
    SOURCES ${CMAKE_SOURCE_DIR}/tests/mutants/zhao_forge_cliff_ram_${mut}.sv)
  add_test(NAME forge_cliff_ram_${mut}_control COMMAND test_forge_cliff_ram_${mut}_control)
  set_tests_properties(forge_cliff_ram_${mut}_control PROPERTIES LABELS "fast;nightly" TIMEOUT 600)
endforeach()

add_executable(test_forge_cliff_ram_rowoff_control forge/forge_cliff_ram_rowoff_control.cpp)
target_link_libraries(test_forge_cliff_ram_rowoff_control PRIVATE zhao_harness zhao_zref)
target_include_directories(test_forge_cliff_ram_rowoff_control PRIVATE
  ${CMAKE_CURRENT_SOURCE_DIR}/forge)
verilate(test_forge_cliff_ram_rowoff_control
  PREFIX Vzhao_forge_cliff
  TOP_MODULE zhao_forge_cliff_ram_rowoff_mutant
  VERILATOR_ARGS --assert
  SOURCES ${CMAKE_SOURCE_DIR}/tests/mutants/zhao_forge_cliff_ram_rowoff_mutant.sv)
add_test(NAME forge_cliff_ram_rowoff_control COMMAND test_forge_cliff_ram_rowoff_control)
set_tests_properties(forge_cliff_ram_rowoff_control PROPERTIES LABELS "fast;nightly" TIMEOUT 600)
""")
print("done")
