// GENERATED by Upheaval/creature/Zixxtrixx/tools/gen_profile.py
// DO NOT EDIT BY HAND. Regenerate if the concept sheet changes.
//
// Zixxtrixx's body taper, measured from the distance transform of
// S. Hofer's Side.png along its own medial axis. Each entry is the
// half-thickness the DRAWING has at that station, as a fraction of the
// head's, in 1/1000. The taper is deliberately not monotonic: it pinches
// hard at the neck, swells again through the body, and only then tapers
// away. A linear neck-to-tail taper is the wrong SHAPE, not merely the
// wrong magnitude.
//
// medial-axis arc used for the body: 2239 of 2346 px
// (the remainder is a tail blade, authored separately because it branches)

constexpr int kProfileStations = 57;
constexpr int32_t kBodyLenMm = 3050;
constexpr int32_t kHeadHalfMm = 268;
constexpr int16_t kProfile[kProfileStations] = {
    1000,  995,  969,  933,  860,  808,  766,  767,
     692,  627,  626,  652,  652,  675,  691,  682,
     668,  697,  658,  626,  622,  592,  570,  553,
     547,  567,  607,  633,  679,  728,  780,  761,
     728,  676,  605,  589,  601,  549,  445,  377,
     362,  355,  348,  335,  309,  293,  266,  253,
     245,  216,  209,  204,  213,  232,  270,  309,
     387,
};

