// zhao_pkg.sv — THE frozen Zhaozhou wave-2 interface package (plan W2.1).
//
// Every cross-block interface W2.2-W2.7 codes against is declared HERE and
// nowhere else: video mode + timing tables, the pixel stream, guard and
// arbiter request/response structs, HPS bridge burst types, the frame_tick /
// counter-snapshot conventions, and the PadFrame re-export.
//
//   *** FROZEN — ABI v2, commit-to-commit (plan §3): any change requires an
//   *** architect sign-off routed through the zhao_pkg.sv change process.
//
// Law (in citation order):
//   spec/video_rules.md   — modes, timing tables, canvas map, 60 Hz law
//   spec/input_rules.md   — PadFrame semantics (layout is ABI)
//   spec/audio_rules.md   — pair/credit shapes consumed by the PCM ring
//   spec/memory_rules.md  — region map, arbiter policy + liveness bound,
//                           bridge bursts, ring descriptors
//   spec/counters.md      — counter_id = catalog index, snapshot protocol
//   spec/commands.zidl    — the ABI (video_mode, PadFrame, opcodes)
//
// Conservative SystemVerilog subset only (charter §2): package, localparams,
// packed structs/enums, functions, bounded loops. No classes/queues/
// interfaces. Lint: clean under `verilator --lint-only -Wall` (enforced by
// the lint_zhao_pkg CTest).

package zhao_pkg;

  // --------------------------------------------------------------------------
  // ABI re-exports (generated byte-identical surfaces — never hand-copied)
  // --------------------------------------------------------------------------
  // The generated zhao_abi_pkg (fpga/rtl/generated/zhao_abi_pkg.sv) owns
  // every wire layout that crosses a language boundary. Importing it here
  // re-exports its names to every consumer of zhao_pkg, so implementers see
  // ONE import. Reverse-field-order packed structs are the generator's law
  // (capture_format.md §1.1 / plan R1) — pack/unpack only via its functions.
  import zhao_abi_pkg::*;

  // video_mode (ABI v2, u8): VIDEO_Z60=0 / VIDEO_STORM=1 / VIDEO_DUO=2 —
  // zhao_video_mode_e, re-exported. The 2-bit internal mirror below is for
  // RTL datapaths; conversions are exact for the three declared values.
  typedef enum logic [1:0] {
    ZHAO_MODE_Z60   = 2'd0,
    ZHAO_MODE_STORM = 2'd1,
    ZHAO_MODE_DUO   = 2'd2
  } zhao_mode_e;

  // PadFrame (ABI v2, 20 B): zhao_pad_frame_t, re-exported from the
  // generated package (input_rules.md §1). The .zcap CONTROLLER_SNAPSHOT
  // body IS this struct array — no second definition exists.

  // --------------------------------------------------------------------------
  // Video timing (spec/video_rules.md §1-§2, decision D1) — the ONE table
  // --------------------------------------------------------------------------
  typedef struct packed {
    logic [15:0] h_active;        // vid cycles of active pixels per line
    logic [15:0] h_front;         // horizontal front porch
    logic [15:0] h_sync;          // horizontal sync width (negative polarity)
    logic [15:0] h_back;          // horizontal back porch
    logic [15:0] h_total;         // h_active + h_front + h_sync + h_back
    logic [15:0] v_active;        // active lines
    logic [15:0] v_front;         // vertical front porch (lines)
    logic [15:0] v_sync;          // vertical sync width (negative polarity)
    logic [15:0] v_back;          // vertical back porch (lines)
    logic [15:0] v_total;         // 262 for every mode
    logic [31:0] frame_gpu_cycles; // v_total * h_total * 2 (gpu cycles)
  } zhao_timing_t;

  localparam zhao_timing_t ZHAO_TIMING [0:2] = '{
    // Z60: 384x240, 480 H total, 251,520 gpu cycles/frame
    '{h_active: 16'd384, h_front: 16'd8,  h_sync: 16'd48, h_back: 16'd40,
      h_total:  16'd480, v_active: 16'd240, v_front: 16'd4, v_sync: 16'd4,
      v_back:   16'd14,  v_total:  16'd262, frame_gpu_cycles: 32'd251_520},
    // Storm: 320x240, 416 H total, 217,984 gpu cycles/frame
    '{h_active: 16'd320, h_front: 16'd8,  h_sync: 16'd48, h_back: 16'd40,
      h_total:  16'd416, v_active: 16'd240, v_front: 16'd4, v_sync: 16'd4,
      v_back:   16'd14,  v_total:  16'd262, frame_gpu_cycles: 32'd217_984},
    // Duo: 512x240 (2 x 256x192 views), 608 H total, 318,592 gpu cycles/frame
    '{h_active: 16'd512, h_front: 16'd8,  h_sync: 16'd48, h_back: 16'd40,
      h_total:  16'd608, v_active: 16'd240, v_front: 16'd4, v_sync: 16'd4,
      v_back:   16'd14,  v_total:  16'd262, frame_gpu_cycles: 32'd318_592}
  };

  // vid_clk = gpu_clk/2 (frozen sim profile; PLL ratios are board data and
  // never change these contract surfaces). Exported for consumers; not
  // referenced inside this package.
  /* verilator lint_off UNUSEDPARAM */
  localparam int unsigned ZHAO_VID_CYCLES_PER_GPU = 2;

  // Canvas geometry (spec/video_rules.md §1/§3): ALLOCATION is not
  // OCCUPANCY. Both FB slots are always ALLOCATED ZHAO_FB_SLOT_SPAN =
  // 0x3C000 B (the largest canvas) so a mode switch never moves a slot;
  // ZHAO_CANVAS_BYTES_* is what a frame actually STORES — for Duo that is
  // the two packed 256x192 view blocks (0x30000, §3.1), NOT the 0x3C000
  // allocation and NOT the 512x240x2 displayed stream (which coincidental-
  // ly also equals 245,760 — see ZHAO_DISPLAYED_BYTES_* below). CMD.DMA's
  // blit-length law (`byte_len == zhao_canvas_bytes(mode)`) rides on these:
  // a Duo DebugFrameBlit carries exactly the stored frame, never the
  // allocation tail the spec declares untouched.
  localparam logic [31:0] ZHAO_CANVAS_BYTES_Z60   = 32'd184_320; // 384*240*2
  localparam logic [31:0] ZHAO_CANVAS_BYTES_STORM = 32'd153_600; // 320*240*2
  localparam logic [31:0] ZHAO_CANVAS_BYTES_DUO   = 32'd196_608; // 2*256*192*2 packed (§3.1)
  localparam logic [31:0] ZHAO_CANVAS_BYTES_MAX   = 32'd245_760; // largest DISPLAYED canvas = the slot allocation
  // Displayed-stream bytes per frame (spec/video_rules.md §4 Displayed-CRC
  // law: 2 * h_active * 240, border rows INCLUDED in Duo). This is what
  // DEBUG.CRC's expect_bytes_i wants — wiring zhao_canvas_bytes there would
  // be a silent Duo bug (196,608 stored vs 245,760 displayed).
  localparam logic [31:0] ZHAO_DISPLAYED_BYTES_Z60   = 32'd184_320; // 384*240*2
  localparam logic [31:0] ZHAO_DISPLAYED_BYTES_STORM = 32'd153_600; // 320*240*2
  localparam logic [31:0] ZHAO_DISPLAYED_BYTES_DUO   = 32'd245_760; // 512*240*2
  /* verilator lint_on UNUSEDPARAM */
  // Region-map constants (spec/memory_rules.md 5) are consumed by MEM.GUARD
  // and the tests; kept here as the single frozen definition.
  /* verilator lint_off UNUSEDPARAM */
  localparam logic [31:0] ZHAO_FB_SLOT0_BASE      = 32'h0000_0000;
  // FB slot 1 lives in DRAM BANK 1 (byte-address bit 25 -> ctrl bank bit 0;
  // the frozen ctrl mapping takes banks from byte addr [26:25]). It was
  // 0x0003_C000 — the SAME bank as slot 0 — until W2.7 composed the real
  // scanout-read + blit-write streams and measured the row thrash: ~82 of
  // 192 Duo lines starved per frame, and no mode could ever fence a
  // full-canvas DebugFrameBlit inside its D8 deadline. Distinct banks keep
  // each stream's row open; the thrash is gone structurally. This edit to
  // the frozen wave-2 interface carries its sign-off reference
  // (arbiter-bound precedent):
  // runs/CLAUDE-RUNS/RUN-20260814-2154-wave2-phase2-console-shell/
  // RATIFICATION-fb-slot-bank-split.md (RATIFIED) (2026-08-16).
  localparam logic [31:0] ZHAO_FB_SLOT1_BASE      = 32'h0200_0000;
  localparam logic [31:0] ZHAO_FB_SLOT_SPAN       = 32'h0003_C000; // 245,760

  // ---------------------------------------------------------------------
  // GEOM asset pool -- the Phase-3 region (spec/memory_rules.md 5f, 2026-09-04)
  //
  // WHY IT EXISTS: GEOM.MESHFETCH is the only zhao_guard_req_t client in the
  // whole geometry subsystem, and every region MEM.GUARD knew was a FRAME
  // BUFFER region, so `default: pass_ok = 1'b0` denied every meshlet
  // descriptor read BY DESIGN. That denial -- not eighteen wiring jobs -- is
  // what has kept the geometry front end out of the console (docket D22).
  //
  // WHY BANK 3: banks come from byte-address bits [26:25], and W2.7 measured
  // ~82 of 192 Duo lines starved when two streams shared a bank. Banks 0 and 1
  // are the FB slots that scanout reads every frame; bank 2 is terrain
  // (ruling T2). Bank 3 holds GEOM.PARAMBUF (ruling R7) and reserves
  // 0x06A0_0000..0x07FF_FFFF "pending evidence". Mesh assets are ENGINE1
  // render-geometry traffic exactly as PARAMBUF is -- same domain, same
  // pipeline phase, already behind one local arbiter (spec 5d) -- so they
  // serialize against each other rather than thrashing against scanout. That
  // is the W2.7 lesson applied rather than re-learned.
  //
  // 22 MiB, ending exactly at the top of the 27-bit VRAM map, so
  // BASE + SPAN cannot wrap 32 bits -- the defect the blit clamp exists for.
  //
  // READ-ONLY, and that is the safety argument: geometry never writes assets,
  // so this region cannot corrupt a frame buffer no matter what it admits.
  // IT IS A KNOB. Both constants are editable and the pool can move to any
  // unmapped range if board evidence says otherwise; nothing derives them.
  localparam logic [31:0] ZHAO_GEOM_ASSET_BASE    = 32'h06A0_0000;
  localparam logic [31:0] ZHAO_GEOM_ASSET_SPAN    = 32'h0160_0000; // 23,068,672

  // ---------------------------------------------------------------------
  // TERRAIN.PAGE_POOL -- the bank-2 region (ruling T2, spec/memory_rules.md
  // 5b, 2026-09-06)
  //
  // WHY IT EXISTS: TERRAIN.PAGELOADER writes whole 21,376-byte pages into
  // local SDRAM and every one of those writes landed on MEM.GUARD's
  // `default: pass_ok = 1'b0`. Bank 2 had no window at all, for anybody, so
  // the block was buildable, tested and UNINTEGRABLE -- exactly the state
  // GEOM.MESHFETCH was in before the asset pool existed.
  //
  // THE BOUNDS ARE THE RULING'S, EXACTLY, AND NOT ONE BYTE MORE.
  // T2 writes the region as 0x0400_0000 .. 0x054D_FFFF inclusive, "1,024 x
  // 21,376 B". 1024 * 21376 = 21,889,024 = 0x014E_0000, so the half-open end
  // is 0x054E_0000 and the two spellings agree to the byte -- there is no
  // rounding to argue about and no slack to take. The five OTHER bank-2
  // regions T2 names (RESIDENT_MIP_POOL, COMPOSED_HEIGHT, COMPOSED_VELOCITY,
  // WRITEBACK_STAGING, COMPOSED_MIP_POOL) are NOT opened here: no block
  // writes them yet, and a window opened ahead of its writer is a hole with a
  // plan attached.
  //
  // BASE + SPAN = 0x054E_0000, far below the 27-bit top 0x0800_0000, so the
  // sum cannot wrap 32 bits -- the defect the blit clamp exists for. Both
  // values are elaboration-time constants: no map input moves this window and
  // it is not frame-scoped.
  //
  // IT IS A KNOB. Both constants are editable and the pool can move to any
  // unmapped range; nothing derives them. `zref::terrain::kPagePoolBase` and
  // `kPagePoolSlots` carry the same numbers on the reference side and static
  // assert the same end address.
  localparam logic [31:0] ZHAO_TERRAIN_PAGE_POOL_BASE = 32'h0400_0000;
  localparam logic [31:0] ZHAO_TERRAIN_PAGE_POOL_SPAN = 32'h014E_0000; // 1024 * 21,376

  // Duo canvas map (spec/video_rules.md §3.1): two 256x192 views vertically
  // centered at x offsets 0 / 256, y offset 24; border rows are black and
  // part of the displayed stream.
  localparam logic [15:0] ZHAO_DUO_VIEW_W   = 16'd256;
  localparam logic [15:0] ZHAO_DUO_VIEW_H   = 16'd192;
  localparam logic [15:0] ZHAO_DUO_VIEW_Y   = 16'd24;
  localparam logic [15:0] ZHAO_DUO_BORDER_RGB565 = 16'h0000;
  /* verilator lint_on UNUSEDPARAM */

  function automatic logic [31:0] zhao_canvas_bytes(input zhao_mode_e m);
    zhao_canvas_bytes = (m == ZHAO_MODE_Z60)   ? ZHAO_CANVAS_BYTES_Z60
                      : (m == ZHAO_MODE_STORM) ? ZHAO_CANVAS_BYTES_STORM
                                               : ZHAO_CANVAS_BYTES_DUO;
  endfunction

  // displayed-stream bytes per frame (§4 law; NOT the stored occupancy)
  function automatic logic [31:0] zhao_displayed_bytes(input zhao_mode_e m);
    zhao_displayed_bytes = (m == ZHAO_MODE_Z60)   ? ZHAO_DISPLAYED_BYTES_Z60
                         : (m == ZHAO_MODE_STORM) ? ZHAO_DISPLAYED_BYTES_STORM
                                                  : ZHAO_DISPLAYED_BYTES_DUO;
  endfunction

  // --------------------------------------------------------------------------
  // SATURATING UNSIGNED ADD (spec/counters.md 4) -- the D9 counter law.
  //
  // Five sites spelled this out by hand: zhao_cmd_dma's sat_add,
  // zhao_input_snapshot's gap accumulator, two arms in zhao_hps_bridge and one
  // in zhao_vram_arbiter. They agreed on the law and disagreed on the spelling
  // -- some tested overflow (a > MAX - b), one tested headroom (MAX - b >= a)
  // -- and every one of them wrote MAX - x as a SUBTRACT.
  //
  // ALL-ONES MINUS x IS EXACTLY ~x. For unsigned N-bit x, (2^N - 1) - x == ~x,
  // with no borrow, because every bit of the minuend is 1 and so no column can
  // borrow from its neighbour. Identity, not approximation. The subtract
  // spelling put a full-width borrow chain in front of the compare for what is
  // a free bitwise inversion; INPUT.SNAPSHOT's seq -> gaps was the design's
  // largest remaining timing family at -0.351 ns across 38 paths.
  //
  // AND NO SIMULATION CAN CHECK THE SATURATION ARM. These are u64 counters, so
  // reaching the rail takes on the order of 2^64 events and nothing external
  // can preload them: replacing `~b` with plain `b`, which breaks the headroom
  // test outright, passes cmd_dma_directed AND its 5,000-packet random lane.
  // Checked, not assumed. That is not a hole more stimulus can close, which is
  // why the law lives here as ONE definition with a proof over ALL inputs
  // rather than as five hand-written copies backed by a green suite.
  //
  // ENFORCED-BY: tests/formal/sat_add.sby
  function automatic logic [63:0] zhao_sat_add64(input logic [63:0] a,
                                                 input logic [63:0] b);
    zhao_sat_add64 = (a > ~b) ? 64'hFFFF_FFFF_FFFF_FFFF : (a + b);
  endfunction

  // ENFORCED-BY: tests/formal/sat_add.sby
  function automatic logic [31:0] zhao_sat_add32(input logic [31:0] a,
                                                 input logic [31:0] b);
    zhao_sat_add32 = (a > ~b) ? 32'hFFFF_FFFF : (a + b);
  endfunction

  function automatic logic [15:0] zhao_active_width(input zhao_mode_e m);
    zhao_active_width = ZHAO_TIMING[m].h_active;
  endfunction

  // exact 2-bit <-> ABI u8 enum conversions (the three declared values)
  function automatic zhao_mode_e zhao_mode_from_abi(input logic [7:0] v);
    zhao_mode_from_abi = (v == 8'd0) ? ZHAO_MODE_Z60
                       : (v == 8'd1) ? ZHAO_MODE_STORM : ZHAO_MODE_DUO;
  endfunction

  function automatic logic [7:0] zhao_mode_to_abi(input zhao_mode_e m);
    zhao_mode_to_abi = {6'b000000, m};  // values 0..2 only (8-bit ABI u8)
  endfunction

  // --------------------------------------------------------------------------
  // Pixel stream (spec/video_rules.md §6) — serializer / scaler output
  // --------------------------------------------------------------------------
  typedef struct packed {
    logic        valid;    // pixel data is on the wires this cycle
    logic [15:0] rgb565;   // [15:11] R, [10:5] G, [4:0] B
    logic [9:0]  x;        // 0-based within the active raster (max 511)
    logic [7:0]  y;        // 0-based within active lines (max 239)
    logic        hsync;    // active during the horizontal sync pulse (negative)
    logic        vsync;    // active during the vertical sync pulse (negative)
    logic        hblank;   // outside h_active
    logic        vblank;   // outside v_active (frame boundary law window)
  } zhao_px_stream_t;

  // --------------------------------------------------------------------------
  // Memory clients / guard / arbiter (spec/memory_rules.md §2/§5/§6, D3)
  // --------------------------------------------------------------------------
  typedef enum logic [2:0] {
    ZHAO_CLIENT_SCANOUT = 3'd0,  // strict-priority guaranteed client
    ZHAO_CLIENT_BLIT_DMA = 3'd1, // DebugFrameBlit DMA (guaranteed)
    ZHAO_CLIENT_ENGINE0  = 3'd2, // reserved guaranteed slot
    ZHAO_CLIENT_ENGINE1  = 3'd3, // reserved guaranteed slot
    ZHAO_CLIENT_DEBUG    = 3'd4, // debug reads (best-effort class, Phase 3+)
    // 3'd5 IS DELIBERATELY UNSPENT. Ruling T3: "Client ID 5 remains available
    // for a measured split if board evidence proves ENGINE1 arbitration is the
    // limiter. Do not spend it pre-emptively." The gap in this enum IS that
    // reservation, held where anyone adding a client will read it. It is also
    // why the next value is 6 rather than 5 -- the number was ruled, not
    // chosen. `zhao_vram_arbiter` carries a matching dead port at index 5,
    // because in that block the ARRAY INDEX *is* the client id.
    // TERRAIN.BUILD -- best-effort / background: HPS->local page loads,
    // F-sheet writeback, prefetch, staging and journal traffic (ruling T3,
    // spec/memory_rules.md 5d). It does NOT join the guaranteed round robin
    // when a page is late; a streaming miss draws a proxy and records
    // pressure. MEM.GUARD gives it exactly one REGION -- TERRAIN.PAGE_POOL,
    // see ZHAO_TERRAIN_PAGE_POOL_BASE below -- with TWO arms: WRITE for
    // TERRAIN.PAGELOADER's pages and READ for TERRAIN.WRITEBACK's layer-F
    // sheets (T4 requires the evacuation; T2 puts layer F inside the page, so
    // the sheet is reachable only through this window). This line said
    // WRITE-ONLY until 2026-09-06, which was true of the blocks that existed
    // rather than of the region.
    ZHAO_CLIENT_TERRAIN_BUILD = 3'd6,
    ZHAO_CLIENT_NONE     = 3'd7
  } zhao_client_e;

  // 128 MB VRAM address space behind the guard
  localparam int unsigned ZHAO_VRAM_ADDR_BITS = 27;

  // client -> MEM.GUARD request (spec/memory_rules.md §5). One request per
  // client in flight; len in bytes (1..64); be is the per-byte enable mask
  // (all-ones for full beats; unaligned tails use masked beats, never
  // out-of-region bytes).
  typedef struct packed {
    logic                    valid;
    logic                    write;
    zhao_client_e            client;
    logic [ZHAO_VRAM_ADDR_BITS-1:0] addr;
    logic [6:0]              len;    // 1..64 bytes
    logic [63:0]             be;     // byte enables, bit i = addr+i
  } zhao_guard_req_t;

  typedef struct packed {
    logic ready;     // the guard accepted (and possibly forwarded) this cycle
    logic ok;        // request passed the region check
    logic violation; // request denied (dropped; NOTHING was written)
  } zhao_guard_rsp_t;

  // guard -> MEM.VRAM.ARBITER credit port (spec/memory_rules.md §2). Burst
  // granularity 8 words at the SDRAM edge; ready/valid at this client port.
  typedef struct packed {
    logic                    valid;
    logic                    write;
    zhao_client_e            client;
    logic [ZHAO_VRAM_ADDR_BITS-1:0] addr;
    logic [6:0]              len;
  } zhao_arb_req_t;

  typedef struct packed {
    logic        grant;    // request accepted into the scheduling window
    logic [7:0]  credits;  // reissued credits as bursts retire (D3 law)
  } zhao_arb_rsp_t;

  // ------------------------------------------------------------------------
  // Guaranteed-client liveness bound B (spec/memory_rules.md §2, D3)
  // ------------------------------------------------------------------------
  // SUPERSEDED — the wave-2 plan froze
  //     B = ZHAO_ARB_GUARANTEED * MAX_BURST + REFRESH_OVERHEAD
  //       = 2 * 14 + 12 = 40
  // and mem_vram_arbiter_liveness cites it. That proof had never been
  // elaborated; when it finally was, B = 40 FAILED. Two independent errors,
  // which partly cancelled and made 40 look plausible:
  //   (a) it budgeted ONE burst per client turn. A 64-B request is FOUR
  //       8-word bursts (ZHAO_ARB_BURSTS_PER_REQ) and the arbiter
  //       re-arbitrates only at burst boundaries, so a competitor's whole
  //       multi-burst request sits in front of the waiting client.
  //   (b) MAX_BURST = 8 + tRCD + tRP = 14 is not the worst grant-to-grant
  //       span. The bank-conflict full read is PRE, tRP, ACT, tRCD, READ,
  //       CAS, 8 bus beats => 18 (ZHAO_ARB_MAX_BURST_SPAN).
  // Re-derivation and the measured tight bounds: spec/memory_rules.md §2.
  // This edit to the frozen wave-2 interface IS the ratified sign-off:
  // runs/CLAUDE-RUNS/RUN-20260814-2154-wave2-phase2-console-shell/
  // RATIFICATION-arbiter-liveness-bound.md (2026-08-15).
  //
  // A waiting client waits out N whole burst spans, where N counts the one
  // burst already in flight (never preempted mid-burst, D3) plus the bursts
  // the competitor is still allowed to take before it must yield:
  //   scanout  (strict priority): N = 1 + 1 = 2
  //       — at most ONE aging-override burst from the RR class can be
  //         interposed; the override resets that client's age, so a second
  //         cannot follow it.
  //   RR class (blit/engine):     N = 1 + 2 = 3
  //       — the competitor may take min(BURSTS_PER_REQ, ceil(AGING/SPAN))
  //         = min(4, 2) = 2 bursts before the aging override closes the
  //         window. THIS is where the bursts-per-request factor enters: with
  //         one burst per turn the term is 1 and the bound collapses to the
  //         old (wrong) 2 spans.
  // The -2 is the alignment between the port-grant pulse and the arbitration
  // boundary (the client becomes visible to the selection one cycle after
  // its grant pulse, and the bound is stated exclusively, `waited < B`).
  //
  // Both refresh-free bounds are proven TIGHT by mem_vram_arbiter_liveness:
  // the bmc task PASSES at them and the bmc_tight_* tasks FAIL at bound-1.
  /* verilator lint_off UNUSEDPARAM */
  localparam int unsigned ZHAO_ARB_GUARANTEED     = 2;   // Phase-2 G
  localparam int unsigned ZHAO_ARB_BURSTS_PER_REQ = 4;   // 64 B / (8 words * 2 B)
  localparam int unsigned ZHAO_ARB_MAX_BURST_SPAN = 18;  // worst grant-to-grant
  localparam int unsigned ZHAO_ARB_AGING_OVERRIDE = 20;  // zhao_vram_arbiter

  localparam int unsigned ZHAO_ARB_SPANS_SCANOUT = 2;    // 1 in-flight + 1 override
  localparam int unsigned ZHAO_ARB_SPANS_RR      = 3;    // 1 in-flight + 2 competitor

  // Refresh-free bounds — formally proven, and proven tight (bisected).
  localparam int unsigned ZHAO_ARB_SCANOUT_BOUND_NOREF =
    ZHAO_ARB_SPANS_SCANOUT * ZHAO_ARB_MAX_BURST_SPAN - 2;   // 34
  localparam int unsigned ZHAO_ARB_LIVENESS_BOUND_NOREF =
    ZHAO_ARB_SPANS_RR * ZHAO_ARB_MAX_BURST_SPAN - 2;        // 52

  // One AUTO_REFRESH can land inside a wait window (REFRESH_INTERVAL = 780
  // sdram cycles >> either bound, so at most one). It costs the boundary
  // cycle plus tRP + tRC = 12 => 13 cycles of extra grant latency. This term
  // is ANALYTIC, not BMC-proven: the liveness BMC runs to depth 130, in which
  // refresh_cnt cannot reach the interval. The harness asserts that scope
  // claim (a_horizon_is_refresh_free) so it cannot silently rot, and the
  // refresh sequence's own cycle count is verified by mem_sdram_directed.
  localparam int unsigned ZHAO_ARB_REFRESH_STEAL = 13;

  // The operational bounds quoted by the contracts and spec/memory_rules.md.
  localparam int unsigned ZHAO_ARB_SCANOUT_BOUND =
    ZHAO_ARB_SCANOUT_BOUND_NOREF + ZHAO_ARB_REFRESH_STEAL;  // 47
  localparam int unsigned ZHAO_ARB_LIVENESS_BOUND =
    ZHAO_ARB_LIVENESS_BOUND_NOREF + ZHAO_ARB_REFRESH_STEAL; // 65
  /* verilator lint_on UNUSEDPARAM */

  // --------------------------------------------------------------------------
  // HPS-DDR bridge bursts (spec/memory_rules.md §3-§4, D10)
  // --------------------------------------------------------------------------
  // 64-B aligned bursts, 1..64 bytes, one in flight per client. In Verilator
  // the harness C++ IS the HPS and answers with the frozen sim profile
  // (16 gpu cycles to first beat, 1 beat/cycle after).
  typedef struct packed {
    logic         valid;
    logic         write;
    zhao_client_e client;
    logic [31:0]  addr;   // HPS DDR byte address
    logic [6:0]   len;    // 1..64 bytes
  } zhao_hps_burst_req_t;

  typedef struct packed {
    logic         beat_valid;
    logic [63:0]  data;   // read data (writes take data on the req channel)
    logic         last;   // final beat of the burst
    logic         err;    // malformed burst / bridge error: nothing issued
  } zhao_hps_burst_rsp_t;

  // --------------------------------------------------------------------------
  // frame_tick + counter snapshot conventions (spec/counters.md, D9)
  // --------------------------------------------------------------------------
  // frame_tick: one-cycle pulse emitted by VIDEO.FRAMECTL at each vblank
  // (after the swap/repeat decision). The machine-wide frame boundary:
  // INPUT.SNAPSHOT latches, per-block counter shadows latch, CMD.SCHEDULER
  // closes slots. Crosses vid->gpu with a 2-flop sync + toggle handshake.
  typedef struct packed {
    logic        pulse;     // one cycle in the DESTINATION domain
    logic [31:0] frame_id;  // displayed-frame counter (frame_cycles mirror)
    logic        repeated;  // this frame repeated the previous (60 Hz law)
  } zhao_frame_tick_t;

  // counter_id = catalog index (u16; design/blocks.yml counter_catalog,
  // ledger rule V15; .zcap COUNTERS section wire format). Values are u64,
  // saturating, never wrapping (spec/counters.md §4).
  /* verilator lint_off UNUSEDPARAM */
  localparam int unsigned ZHAO_COUNTER_ID_BITS = 16;
  localparam int unsigned ZHAO_COUNTER_VAL_BITS = 64;
  /* verilator lint_on UNUSEDPARAM */

  typedef struct packed {
    logic                 valid;
    logic [15:0]          counter_id; // catalog index, ascending in captures
    logic [63:0]          value;      // shadow value (stable all frame)
  } zhao_counter_snap_t;

  // Phase-2 active counter ids (catalog positions in design/blocks.yml —
  // append-only, never renumbered; see spec/counters.md §5 for the table).
  // Consumed by DEBUG.COUNTERS read-muxes, per-block shadow latches, tests
  // and capture tooling; not referenced inside this package.
  /* verilator lint_off UNUSEDPARAM */
  localparam logic [15:0] ZHAO_CNT_FRAME_CYCLES   = 16'd0;  // frame_cycles
  localparam logic [15:0] ZHAO_CNT_DEADLINE_FAULTS = 16'd1; // deadline_faults
  localparam logic [15:0] ZHAO_CNT_COMMANDS        = 16'd2; // commands
  localparam logic [15:0] ZHAO_CNT_VRAM_BYTES      = 16'd28; // vram_bytes_by_client
  localparam logic [15:0] ZHAO_CNT_HPS_BYTES       = 16'd29; // hps_ddr_bytes_by_client
  localparam logic [15:0] ZHAO_CNT_SCANOUT_STARVE  = 16'd30; // scanout_starvation_cycles
  localparam logic [15:0] ZHAO_CNT_AUDIO_UNDERRUNS = 16'd31; // audio_underruns
  localparam logic [15:0] ZHAO_CNT_INPUT_SEQ_GAPS  = 16'd35; // input_sequence_gaps
  localparam logic [15:0] ZHAO_CNT_RUMBLE_DROPPED  = 16'd36; // rumble_frames_dropped
  /* verilator lint_on UNUSEDPARAM */

endpackage : zhao_pkg
