// zhao_frame_pkg.sv — frame-packet ABI constants and status codes.
//
// >>> LOCAL PLACEHOLDER PACKAGE (W1). <<<
// The authoritative layout is generated by tools/abi-gen (W4) into
// fpga/rtl/generated/zhao_abi_pkg.sv from spec/commands.zidl. When that file
// lands, the ONLY change needed in fpga/rtl/ consumers is the import:
//     import zhao_abi_pkg::*;   // instead of:  import zhao_frame_pkg::*;
// This placeholder mirrors the header layout ratified in plan
// RUN-20260814-1912-wave1-architecture-plan (W4 / P5 3.1) so the swap is
// field-for-field identical.
//
// Header layout (little-endian byte stream, P5 3.1):
//   offset  size  field
//        0     4  magic             'Z','P','K','1' on the wire
//        4     2  abi_version       u16, currently 1
//        6     2  flags             u16 (bit0 = contains_debug_commands, 1.E)
//        8     4  frame_id          u32
//       12     4  sequence          u32
//       16     4  resource_epoch    u32
//       20     4  deadline          u32
//       24     4  command_count     u32
//       28     4  command_bytes     u32
//       32     4  header_crc32c     u32 (accepted, NOT validated by the stub
//                                     until W4 wires the CRC-32C table)
//   total    36 bytes, then command_bytes payload bytes.
//
// Conservative SystemVerilog subset only (charter 2: packages, packed
// structs/enums, always_ff/always_comb; no classes/queues/interfaces).

package zhao_frame_pkg;

  // 'Z','P','K','1' arrive as bytes 0..3; the stream is little-endian, so the
  // assembled u32 constant is 0x314B_505A.
  localparam logic [31:0] ZHAO_FRAME_MAGIC = 32'h314B_505A;

  localparam int unsigned ZHAO_ABI_VERSION        = 1;
  localparam int unsigned ZHAO_HEADER_BYTES       = 36;
  localparam int unsigned ZHAO_FRAME_SLOT_BYTES   = 1048576;  // 1 MiB, provisional (P5 1.E)
  localparam int unsigned ZHAO_COMMAND_ALIGNMENT  = 16;       // minimal command record

  // Byte offsets of the header fields (little-endian u16/u32).
  localparam int unsigned OFF_MAGIC        = 0;
  localparam int unsigned OFF_ABI_VERSION  = 4;
  localparam int unsigned OFF_FLAGS        = 6;
  localparam int unsigned OFF_FRAME_ID     = 8;
  localparam int unsigned OFF_SEQUENCE     = 12;
  localparam int unsigned OFF_RESOURCE_EPOCH = 16;
  localparam int unsigned OFF_DEADLINE     = 20;
  localparam int unsigned OFF_COMMAND_COUNT = 24;
  localparam int unsigned OFF_COMMAND_BYTES = 28;
  localparam int unsigned OFF_HEADER_CRC   = 32;

  // status output codes. IDLE = between frames; OK = frame completed.
  // Error codes are safe rejections: the stub never acts on a bad frame.
  typedef enum logic [7:0] {
    STATUS_IDLE       = 8'h00,
    STATUS_OK         = 8'h01,
    STATUS_ERR_MAGIC  = 8'h02,
    STATUS_ERR_ABI    = 8'h03,
    STATUS_ERR_LENGTH = 8'h04
  } status_e;

  // completion_flags output bits. Held until the next frame's first byte.
  localparam logic [7:0] ZHAO_COMPL_DONE = 8'h01;  // frame accepted & consumed
  localparam logic [7:0] ZHAO_COMPL_ERR  = 8'h02;  // frame rejected (see status)

endpackage : zhao_frame_pkg
