// zhao_pkg.sv — THE frozen Zhaozhou wave-2 interface package (plan W2.1).
//
// Every cross-block interface W2.2-W2.7 codes against is declared HERE and
// nowhere else: video mode + timing tables, the pixel stream, guard and
// arbiter request/response structs, HPS bridge burst types, the frame_tick /
// counter-snapshot conventions, and the PadFrame re-export.
//
//   *** FROZEN — ABI v2, commit-to-commit (plan §3): any change requires an
//   *** architect sign-off routed through the zhao_pkg.sv change process.
//
// Law (in citation order):
//   spec/video_rules.md   — modes, timing tables, canvas map, 60 Hz law
//   spec/input_rules.md   — PadFrame semantics (layout is ABI)
//   spec/audio_rules.md   — pair/credit shapes consumed by the PCM ring
//   spec/memory_rules.md  — region map, arbiter policy + liveness bound,
//                           bridge bursts, ring descriptors
//   spec/counters.md      — counter_id = catalog index, snapshot protocol
//   spec/commands.zidl    — the ABI (video_mode, PadFrame, opcodes)
//
// Conservative SystemVerilog subset only (charter §2): package, localparams,
// packed structs/enums, functions, bounded loops. No classes/queues/
// interfaces. Lint: clean under `verilator --lint-only -Wall` (enforced by
// the lint_zhao_pkg CTest).

package zhao_pkg;

  // --------------------------------------------------------------------------
  // ABI re-exports (generated byte-identical surfaces — never hand-copied)
  // --------------------------------------------------------------------------
  // The generated zhao_abi_pkg (fpga/rtl/generated/zhao_abi_pkg.sv) owns
  // every wire layout that crosses a language boundary. Importing it here
  // re-exports its names to every consumer of zhao_pkg, so implementers see
  // ONE import. Reverse-field-order packed structs are the generator's law
  // (capture_format.md §1.1 / plan R1) — pack/unpack only via its functions.
  import zhao_abi_pkg::*;

  // video_mode (ABI v2, u8): VIDEO_Z60=0 / VIDEO_STORM=1 / VIDEO_DUO=2 —
  // zhao_video_mode_e, re-exported. The 2-bit internal mirror below is for
  // RTL datapaths; conversions are exact for the three declared values.
  typedef enum logic [1:0] {
    ZHAO_MODE_Z60   = 2'd0,
    ZHAO_MODE_STORM = 2'd1,
    ZHAO_MODE_DUO   = 2'd2
  } zhao_mode_e;

  // PadFrame (ABI v2, 20 B): zhao_pad_frame_t, re-exported from the
  // generated package (input_rules.md §1). The .zcap CONTROLLER_SNAPSHOT
  // body IS this struct array — no second definition exists.

  // --------------------------------------------------------------------------
  // Video timing (spec/video_rules.md §1-§2, decision D1) — the ONE table
  // --------------------------------------------------------------------------
  typedef struct packed {
    logic [15:0] h_active;        // vid cycles of active pixels per line
    logic [15:0] h_front;         // horizontal front porch
    logic [15:0] h_sync;          // horizontal sync width (negative polarity)
    logic [15:0] h_back;          // horizontal back porch
    logic [15:0] h_total;         // h_active + h_front + h_sync + h_back
    logic [15:0] v_active;        // active lines
    logic [15:0] v_front;         // vertical front porch (lines)
    logic [15:0] v_sync;          // vertical sync width (negative polarity)
    logic [15:0] v_back;          // vertical back porch (lines)
    logic [15:0] v_total;         // 262 for every mode
    logic [31:0] frame_gpu_cycles; // v_total * h_total * 2 (gpu cycles)
  } zhao_timing_t;

  localparam zhao_timing_t ZHAO_TIMING [0:2] = '{
    // Z60: 384x240, 480 H total, 251,520 gpu cycles/frame
    '{h_active: 16'd384, h_front: 16'd8,  h_sync: 16'd48, h_back: 16'd40,
      h_total:  16'd480, v_active: 16'd240, v_front: 16'd4, v_sync: 16'd4,
      v_back:   16'd14,  v_total:  16'd262, frame_gpu_cycles: 32'd251_520},
    // Storm: 320x240, 416 H total, 217,984 gpu cycles/frame
    '{h_active: 16'd320, h_front: 16'd8,  h_sync: 16'd48, h_back: 16'd40,
      h_total:  16'd416, v_active: 16'd240, v_front: 16'd4, v_sync: 16'd4,
      v_back:   16'd14,  v_total:  16'd262, frame_gpu_cycles: 32'd217_984},
    // Duo: 512x240 (2 x 256x192 views), 608 H total, 318,592 gpu cycles/frame
    '{h_active: 16'd512, h_front: 16'd8,  h_sync: 16'd48, h_back: 16'd40,
      h_total:  16'd608, v_active: 16'd240, v_front: 16'd4, v_sync: 16'd4,
      v_back:   16'd14,  v_total:  16'd262, frame_gpu_cycles: 32'd318_592}
  };

  // vid_clk = gpu_clk/2 (frozen sim profile; PLL ratios are board data and
  // never change these contract surfaces). Exported for consumers; not
  // referenced inside this package.
  /* verilator lint_off UNUSEDPARAM */
  localparam int unsigned ZHAO_VID_CYCLES_PER_GPU = 2;

  // Canvas geometry (spec/video_rules.md §1/§3) — both FB slots are sized
  // for the largest canvas; a mode switch never moves a slot.
  localparam logic [31:0] ZHAO_CANVAS_BYTES_Z60   = 32'd184_320; // 384*240*2
  localparam logic [31:0] ZHAO_CANVAS_BYTES_STORM = 32'd153_600; // 320*240*2
  localparam logic [31:0] ZHAO_CANVAS_BYTES_DUO   = 32'd245_760; // 512*240*2
  localparam logic [31:0] ZHAO_CANVAS_BYTES_MAX   = 32'd245_760;
  /* verilator lint_on UNUSEDPARAM */
  // Region-map constants (spec/memory_rules.md 5) are consumed by MEM.GUARD
  // and the tests; kept here as the single frozen definition.
  /* verilator lint_off UNUSEDPARAM */
  localparam logic [31:0] ZHAO_FB_SLOT0_BASE      = 32'h0000_0000;
  localparam logic [31:0] ZHAO_FB_SLOT1_BASE      = 32'h0003_C000;
  localparam logic [31:0] ZHAO_FB_SLOT_SPAN       = 32'h0003_C000; // 245,760

  // Duo canvas map (spec/video_rules.md §3.1): two 256x192 views vertically
  // centered at x offsets 0 / 256, y offset 24; border rows are black and
  // part of the displayed stream.
  localparam logic [15:0] ZHAO_DUO_VIEW_W   = 16'd256;
  localparam logic [15:0] ZHAO_DUO_VIEW_H   = 16'd192;
  localparam logic [15:0] ZHAO_DUO_VIEW_Y   = 16'd24;
  localparam logic [15:0] ZHAO_DUO_BORDER_RGB565 = 16'h0000;
  /* verilator lint_on UNUSEDPARAM */

  function automatic logic [31:0] zhao_canvas_bytes(input zhao_mode_e m);
    zhao_canvas_bytes = (m == ZHAO_MODE_Z60)   ? ZHAO_CANVAS_BYTES_Z60
                      : (m == ZHAO_MODE_STORM) ? ZHAO_CANVAS_BYTES_STORM
                                               : ZHAO_CANVAS_BYTES_DUO;
  endfunction

  function automatic logic [15:0] zhao_active_width(input zhao_mode_e m);
    zhao_active_width = ZHAO_TIMING[m].h_active;
  endfunction

  // exact 2-bit <-> ABI u8 enum conversions (the three declared values)
  function automatic zhao_mode_e zhao_mode_from_abi(input logic [7:0] v);
    zhao_mode_from_abi = (v == 8'd0) ? ZHAO_MODE_Z60
                       : (v == 8'd1) ? ZHAO_MODE_STORM : ZHAO_MODE_DUO;
  endfunction

  function automatic logic [7:0] zhao_mode_to_abi(input zhao_mode_e m);
    zhao_mode_to_abi = {6'b000000, m};  // values 0..2 only (8-bit ABI u8)
  endfunction

  // --------------------------------------------------------------------------
  // Pixel stream (spec/video_rules.md §6) — serializer / scaler output
  // --------------------------------------------------------------------------
  typedef struct packed {
    logic        valid;    // pixel data is on the wires this cycle
    logic [15:0] rgb565;   // [15:11] R, [10:5] G, [4:0] B
    logic [9:0]  x;        // 0-based within the active raster (max 511)
    logic [7:0]  y;        // 0-based within active lines (max 239)
    logic        hsync;    // active during the horizontal sync pulse (negative)
    logic        vsync;    // active during the vertical sync pulse (negative)
    logic        hblank;   // outside h_active
    logic        vblank;   // outside v_active (frame boundary law window)
  } zhao_px_stream_t;

  // --------------------------------------------------------------------------
  // Memory clients / guard / arbiter (spec/memory_rules.md §2/§5/§6, D3)
  // --------------------------------------------------------------------------
  typedef enum logic [2:0] {
    ZHAO_CLIENT_SCANOUT = 3'd0,  // strict-priority guaranteed client
    ZHAO_CLIENT_BLIT_DMA = 3'd1, // DebugFrameBlit DMA (guaranteed)
    ZHAO_CLIENT_ENGINE0  = 3'd2, // reserved guaranteed slot
    ZHAO_CLIENT_ENGINE1  = 3'd3, // reserved guaranteed slot
    ZHAO_CLIENT_DEBUG    = 3'd4, // debug reads (best-effort class, Phase 3+)
    ZHAO_CLIENT_NONE     = 3'd7
  } zhao_client_e;

  // 128 MB VRAM address space behind the guard
  localparam int unsigned ZHAO_VRAM_ADDR_BITS = 27;

  // client -> MEM.GUARD request (spec/memory_rules.md §5). One request per
  // client in flight; len in bytes (1..64); be is the per-byte enable mask
  // (all-ones for full beats; unaligned tails use masked beats, never
  // out-of-region bytes).
  typedef struct packed {
    logic                    valid;
    logic                    write;
    zhao_client_e            client;
    logic [ZHAO_VRAM_ADDR_BITS-1:0] addr;
    logic [6:0]              len;    // 1..64 bytes
    logic [63:0]             be;     // byte enables, bit i = addr+i
  } zhao_guard_req_t;

  typedef struct packed {
    logic ready;     // the guard accepted (and possibly forwarded) this cycle
    logic ok;        // request passed the region check
    logic violation; // request denied (dropped; NOTHING was written)
  } zhao_guard_rsp_t;

  // guard -> MEM.VRAM.ARBITER credit port (spec/memory_rules.md §2). Burst
  // granularity 8 words at the SDRAM edge; ready/valid at this client port.
  typedef struct packed {
    logic                    valid;
    logic                    write;
    zhao_client_e            client;
    logic [ZHAO_VRAM_ADDR_BITS-1:0] addr;
    logic [6:0]              len;
  } zhao_arb_req_t;

  typedef struct packed {
    logic        grant;    // request accepted into the scheduling window
    logic [7:0]  credits;  // reissued credits as bursts retire (D3 law)
  } zhao_arb_rsp_t;

  // Guaranteed-client liveness bound B = G*MAX_BURST + REFRESH_OVERHEAD
  // (spec/memory_rules.md §2): G=2 guaranteed Phase-2 clients,
  // MAX_BURST = 8 (burst) + tRCD + tRP = 6 => 14; REFRESH_OVERHEAD =
  // tRC + tRP = 12. Formal property mem_vram_arbiter_liveness proves grants
  // within this bound (in sdram cycles). The bound constants are consumed
  // by the arbiter's formal property and tests, not inside this package.
  /* verilator lint_off UNUSEDPARAM */
  localparam int unsigned ZHAO_ARB_GUARANTEED = 2;
  localparam int unsigned ZHAO_ARB_MAX_BURST  = 14;
  localparam int unsigned ZHAO_ARB_REFRESH_OVERHEAD = 12;
  localparam int unsigned ZHAO_ARB_LIVENESS_BOUND =
    ZHAO_ARB_GUARANTEED * ZHAO_ARB_MAX_BURST + ZHAO_ARB_REFRESH_OVERHEAD; // 40
  /* verilator lint_on UNUSEDPARAM */

  // --------------------------------------------------------------------------
  // HPS-DDR bridge bursts (spec/memory_rules.md §3-§4, D10)
  // --------------------------------------------------------------------------
  // 64-B aligned bursts, 1..64 bytes, one in flight per client. In Verilator
  // the harness C++ IS the HPS and answers with the frozen sim profile
  // (16 gpu cycles to first beat, 1 beat/cycle after).
  typedef struct packed {
    logic         valid;
    logic         write;
    zhao_client_e client;
    logic [31:0]  addr;   // HPS DDR byte address
    logic [6:0]   len;    // 1..64 bytes
  } zhao_hps_burst_req_t;

  typedef struct packed {
    logic         beat_valid;
    logic [63:0]  data;   // read data (writes take data on the req channel)
    logic         last;   // final beat of the burst
    logic         err;    // malformed burst / bridge error: nothing issued
  } zhao_hps_burst_rsp_t;

  // --------------------------------------------------------------------------
  // frame_tick + counter snapshot conventions (spec/counters.md, D9)
  // --------------------------------------------------------------------------
  // frame_tick: one-cycle pulse emitted by VIDEO.FRAMECTL at each vblank
  // (after the swap/repeat decision). The machine-wide frame boundary:
  // INPUT.SNAPSHOT latches, per-block counter shadows latch, CMD.SCHEDULER
  // closes slots. Crosses vid->gpu with a 2-flop sync + toggle handshake.
  typedef struct packed {
    logic        pulse;     // one cycle in the DESTINATION domain
    logic [31:0] frame_id;  // displayed-frame counter (frame_cycles mirror)
    logic        repeated;  // this frame repeated the previous (60 Hz law)
  } zhao_frame_tick_t;

  // counter_id = catalog index (u16; design/blocks.yml counter_catalog,
  // ledger rule V15; .zcap COUNTERS section wire format). Values are u64,
  // saturating, never wrapping (spec/counters.md §4).
  /* verilator lint_off UNUSEDPARAM */
  localparam int unsigned ZHAO_COUNTER_ID_BITS = 16;
  localparam int unsigned ZHAO_COUNTER_VAL_BITS = 64;
  /* verilator lint_on UNUSEDPARAM */

  typedef struct packed {
    logic                 valid;
    logic [15:0]          counter_id; // catalog index, ascending in captures
    logic [63:0]          value;      // shadow value (stable all frame)
  } zhao_counter_snap_t;

  // Phase-2 active counter ids (catalog positions in design/blocks.yml —
  // append-only, never renumbered; see spec/counters.md §5 for the table).
  // Consumed by DEBUG.COUNTERS read-muxes, per-block shadow latches, tests
  // and capture tooling; not referenced inside this package.
  /* verilator lint_off UNUSEDPARAM */
  localparam logic [15:0] ZHAO_CNT_FRAME_CYCLES   = 16'd0;  // frame_cycles
  localparam logic [15:0] ZHAO_CNT_DEADLINE_FAULTS = 16'd1; // deadline_faults
  localparam logic [15:0] ZHAO_CNT_COMMANDS        = 16'd2; // commands
  localparam logic [15:0] ZHAO_CNT_VRAM_BYTES      = 16'd28; // vram_bytes_by_client
  localparam logic [15:0] ZHAO_CNT_HPS_BYTES       = 16'd29; // hps_ddr_bytes_by_client
  localparam logic [15:0] ZHAO_CNT_SCANOUT_STARVE  = 16'd30; // scanout_starvation_cycles
  localparam logic [15:0] ZHAO_CNT_AUDIO_UNDERRUNS = 16'd31; // audio_underruns
  localparam logic [15:0] ZHAO_CNT_INPUT_SEQ_GAPS  = 16'd35; // input_sequence_gaps
  localparam logic [15:0] ZHAO_CNT_RUMBLE_DROPPED  = 16'd36; // rumble_frames_dropped
  /* verilator lint_on UNUSEDPARAM */

endpackage : zhao_pkg
