// tb_geom_bin_pipe_v2.sv -- private full Packet-D bin-to-resolve harness.
//
// The DUT is the exact product composition at a 2x2-tile characterization grid.
// External cache fill, palette, Surface Sheet and framebuffer backpressure are
// driven by geom_bin_pipe_v2_directed.cpp.  The two pause inputs alter handshake
// availability only and exist solely under ZHAO_PACKET_D_TEST_HOOKS.
`default_nettype none

module tb_geom_bin_pipe_v2 (
    input  logic clk,
    input  logic rst_n,

    input  logic               frame_begin_i,
    input  logic               frame_end_i,
    input  logic        [5:0]  grid_w_i,
    input  logic        [5:0]  grid_h_i,
    input  logic        [63:0] frame_clear_word_i,

    input  logic               tri_valid_i,
    output logic               tri_ready_o,
    input  logic signed [22:0] tri_kx0_i,
    input  logic signed [22:0] tri_ky0_i,
    input  logic signed [47:0] tri_kc0_i,
    input  logic signed [22:0] tri_kx1_i,
    input  logic signed [22:0] tri_ky1_i,
    input  logic signed [47:0] tri_kc1_i,
    input  logic signed [22:0] tri_kx2_i,
    input  logic signed [22:0] tri_ky2_i,
    input  logic signed [47:0] tri_kc2_i,
    input  logic        [2:0]  tri_tl_i,
    input  logic signed [20:0] tri_ax_i,
    input  logic signed [20:0] tri_ay_i,
    input  logic signed [20:0] tri_bx_i,
    input  logic signed [20:0] tri_by_i,
    input  logic signed [20:0] tri_cx_i,
    input  logic signed [20:0] tri_cy_i,
    input  logic signed [11:0] tri_min_x_i,
    input  logic signed [11:0] tri_max_x_i,
    input  logic signed [11:0] tri_min_y_i,
    input  logic signed [11:0] tri_max_y_i,
    input  logic        [15:0] tri_src_id_i,
    input  logic        [46:0] tri_area2_i,
    input  logic       [239:0] tri_invw_plane_i,
    input  logic       [239:0] tri_u_over_w_plane_i,
    input  logic       [239:0] tri_v_over_w_plane_i,
    // The Gouraud planes (owner decision R234 D1). Lanes 3..5.
    input  logic       [239:0] tri_r_plane_i,
    input  logic       [239:0] tri_g_plane_i,
    input  logic       [239:0] tri_b_plane_i,
    input  logic       [297:0] tri_flat_request_i,
    input  logic        [47:0] tri_continuation_tail_i,
    input  logic        [31:0] tri_fragment_state_i,

    // Unchanged flat oracle path, enabled only for the dedicated differential.
    input  logic               old_enable_i,
    input  logic        [63:0] old_job_fill_word_i,
    input  logic        [31:0] old_job_state_i,
    input  logic        [7:0]  old_job_src_a_i,
    input  logic        [23:0] old_job_texel_rgb_i,
    input  logic        [7:0]  old_job_texel_a_i,
    input  logic        [7:0]  old_job_texel_idx_i,
    output logic               old_fb_valid_o,
    output logic        [15:0] old_fb_rgb565_o,
    output logic        [7:0]  old_fb_tag_o,
    output logic        [7:0]  old_fb_addr_o,
    output logic signed [11:0] old_fb_x_o,
    output logic signed [11:0] old_fb_y_o,
    output logic               old_fb_last_o,
    output logic        [15:0] old_fb_src_id_o,
    output logic        [31:0] old_tile_crc_o,
    output logic        [15:0] old_tile_crc_index_o,
    output logic               old_tile_done_o,
    output logic        [8:0]  old_tile_cov_count_o,
    output logic               old_tile_degenerate_o,
    output logic               old_drain_done_o,

    output logic               tok_req_o,
    input  logic               tok_grant_i,

    input  logic               frame_fault_clear_valid_i,
    output logic               frame_fault_clear_ready_o,
    output logic               frame_fault_o,
    output logic               lifetime_structural_fault_o,

    input  logic               cfg_valid_i,
    output logic               cfg_ready_o,
    input  logic        [1:0]  cfg_op_i,
    input  logic        [7:0]  cfg_page_generation_i,
    input  logic        [7:0]  cfg_selector_i,
    input  logic        [74:0] cfg_row_i,
    input  logic        [31:0] cfg_crc32_i,
    output logic               cfg_rsp_valid_o,
    input  logic               cfg_rsp_ready_i,
    output logic        [1:0]  cfg_rsp_op_o,
    output logic        [3:0]  cfg_rsp_status_o,
    output logic        [7:0]  cfg_rsp_page_generation_o,
    output logic        [7:0]  active_page_generation_o,

    output logic               fill_req_valid_o,
    input  logic               fill_req_ready_i,
    output logic        [31:0] fill_req_addr_o,
    input  logic               fill_data_valid_i,
    input  logic        [15:0] fill_data_i,
    input  logic               fill_refused_i,

    input  logic               pal_load_valid_i,
    output logic               pal_load_ready_o,
    input  logic        [1:0]  pal_load_op_i,
    input  logic        [1:0]  pal_load_slot_i,
    input  logic        [7:0]  pal_load_gen_i,
    input  logic        [7:0]  pal_load_idx_i,
    input  logic        [15:0] pal_load_rgb565_i,
    input  logic               pal_load_crc_ok_i,

    output logic               sheet_req_valid_o,
    input  logic               sheet_req_ready_i,
    output logic        [1:0]  sheet_req_op_o,
    output logic        [31:0] sheet_req_handle_o,
    output logic        [11:0] sheet_req_texel_o,
    output logic        [15:0] sheet_req_src_id_o,
    input  logic               pg_valid_i,
    output logic               pg_ready_o,
    input  logic        [1:0]  pg_op_i,
    input  logic        [1:0]  pg_status_i,
    input  logic        [7:0]  pg_tag_i,
    input  logic        [7:0]  pg_strength_i,
    input  logic        [15:0] pg_src_id_i,

    output logic               fb_valid_o,
    input  logic               fb_ready_i,
    output logic        [15:0] fb_rgb565_o,
    output logic        [7:0]  fb_tag_o,
    output logic        [7:0]  fb_addr_o,
    output logic signed [11:0] fb_x_o,
    output logic signed [11:0] fb_y_o,
    output logic               fb_last_o,
    output logic        [15:0] fb_src_id_o,
    output logic        [31:0] tile_crc_o,
    output logic        [15:0] tile_crc_index_o,
    output logic               tile_done_o,
    output logic        [8:0]  tile_cov_count_o,
    output logic               tile_degenerate_o,

    output logic               drain_busy_o,
    output logic               drain_done_o,
    output logic               binner_initialized_o,
    output logic        [31:0] binner_tile_references_o,
    output logic        [15:0] binner_max_tile_list_depth_o,
    output logic        [31:0] binner_triangles_culled_o,
    output logic               binner_overflow_o,
    output logic               binner_arena_full_o,
    output logic        [8:0]  binner_arena_used_o,
    output logic        [31:0] jobs_taken_o,
    output logic        [31:0] job_stall_clocks_o,

    output logic               quiet_o,
    output logic               raster_abort_o,
    output logic               local_attribute_abort_o,
    output logic               local_fault_pulse_o,
    output logic        [31:0] local_fault_count_o,
    output logic        [31:0] coordinate_fault_count_o,
    output logic        [31:0] range_fault_count_o,
    output logic        [31:0] aux_profile_fault_count_o,
    output logic        [31:0] candidate_cancel_count_o,
    output logic        [31:0] local_drop_count_o,
    output logic        [31:0] raster_jobs_started_o,
    output logic        [31:0] raster_jobs_sunk_o,
    output logic               sequence_abort_o,
    output logic               sequence_mismatch_o,
    output logic        [31:0] sequence_drop_count_o,
    output logic        [31:0] admission_sequence_o,
    output logic        [31:0] expected_sequence_o,
    output logic        [31:0] returned_sequence_o,
    output logic               packet_c_cand_fire_o,
    output logic               packet_c_fragment_fire_o,
    output logic               packet_c_drop_fire_o,
    output logic        [31:0] tilestore_references_o,
    output logic        [31:0] resolved_tiles_o,
    output logic        [31:0] early_z_rejects_o,
    output logic        [31:0] early_z_covered_o,
    output logic        [31:0] fragment_covered_o,
    output logic        [31:0] blended_fragments_o,
    output logic        [31:0] texture_fragments_o,
    output logic        [31:0] texture_cache_hits_o,
    output logic        [31:0] texture_cache_misses_o,
    output logic        [31:0] texture_palette_lookups_o,
    output logic        [31:0] texture_plan_accepted_o,
    output logic        [31:0] texture_dispatch_accepted_o,
    output logic        [31:0] texture_combine_refused_o,
    // Entry I49, 2026-09-20: TMU samples PUBLISHED into a fragment.
    output logic        [31:0] texture_samples_o,
    output logic               fragment_error_o,

    output logic               coverage_hold_valid_o,
    output logic        [5:0]  coverage_delivered_mask_o,
    output logic        [7:0]  start_delivered_mask_o,
    output logic        [5:0]  attribute_idle_o,
    output logic               earlyz_hold_valid_o,
    output logic        [1:0]  skid_level_o,
    output logic               stage_candidate_valid_o,
    output logic       [489:0] stage_candidate_data_o,
    output logic               stage_fragment_valid_o,
    output logic        [7:0]  stage_fragment_addr_o,
    output logic        [23:0] stage_fragment_depth_o,
    output logic        [31:0] stage_fragment_state_o,
    output logic        [15:0] stage_fragment_src_id_o,
    output logic        [23:0] stage_fragment_texel_rgb_o,
    output logic        [7:0]  stage_fragment_texel_a_o,
    output logic        [7:0]  stage_fragment_texel_idx_o,
    output logic        [7:0]  stage_fragment_status_o,
    output logic               texture_quiet_o,
    output logic               fragment_idle_o,
    output logic               front_bank_o,
    output logic        [7:0]  bin_mask_o,
    output logic        [23:0] z_floor_o,

    input  logic        [7:0]  test_start_enable_i,
    input  logic        [5:0]  test_attr_cov_enable_i,
    input  logic               test_stage_admit_enable_i
);

  logic v2_tri_ready_w, old_tri_ready_w;
  logic v2_tri_valid_w, old_tri_valid_w;
  logic old_tok_req_w;
  logic [63:0] old_clear_q;

  // Test-only atomic fork: when the old oracle is selected, neither binner sees
  // the triangle until both can accept it on the same edge.
  assign tri_ready_o = old_enable_i ? (v2_tri_ready_w && old_tri_ready_w)
                                    : v2_tri_ready_w;
  assign v2_tri_valid_w = tri_valid_i && (!old_enable_i || old_tri_ready_w);
  assign old_tri_valid_w = tri_valid_i && old_enable_i && v2_tri_ready_w;

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) old_clear_q <= 64'd0;
    else if (frame_begin_i) old_clear_q <= frame_clear_word_i;
  end

  zhao_geom_bin_pipe_v2 u_dut (
      // The serialise pass is not requested here: this bench is Packet D's
      // raster path, and with `ser_req_i` low the binner's walk is the raster
      // drain and nothing else -- which is what keeps this bench's numbers
      // comparable across the I54 change rather than silently re-baselined.
      .ser_req_i(1'b0), .ser_ready_i(1'b0),
      .ser_busy_o(), .ser_done_o(), .ser_valid_o(),
      .ser_tri_id_o(), .ser_tile_o(), .ser_first_o(), .ser_last_o(),
      .clk(clk), .rst_n(rst_n),
      .frame_begin_i(frame_begin_i), .frame_end_i(frame_end_i),
      .grid_w_i(grid_w_i), .grid_h_i(grid_h_i),
      .frame_clear_word_i(frame_clear_word_i),
      .tri_valid_i(v2_tri_valid_w), .tri_ready_o(v2_tri_ready_w),
      .tri_kx0_i(tri_kx0_i), .tri_ky0_i(tri_ky0_i), .tri_kc0_i(tri_kc0_i),
      .tri_kx1_i(tri_kx1_i), .tri_ky1_i(tri_ky1_i), .tri_kc1_i(tri_kc1_i),
      .tri_kx2_i(tri_kx2_i), .tri_ky2_i(tri_ky2_i), .tri_kc2_i(tri_kc2_i),
      .tri_tl_i(tri_tl_i),
      .tri_ax_i(tri_ax_i), .tri_ay_i(tri_ay_i),
      .tri_bx_i(tri_bx_i), .tri_by_i(tri_by_i),
      .tri_cx_i(tri_cx_i), .tri_cy_i(tri_cy_i),
      .tri_min_x_i(tri_min_x_i), .tri_max_x_i(tri_max_x_i),
      .tri_min_y_i(tri_min_y_i), .tri_max_y_i(tri_max_y_i),
      .tri_src_id_i(tri_src_id_i), .tri_area2_i(tri_area2_i),
      .tri_invw_plane_i(tri_invw_plane_i),
      .tri_u_over_w_plane_i(tri_u_over_w_plane_i),
      .tri_v_over_w_plane_i(tri_v_over_w_plane_i),
      .tri_r_plane_i(tri_r_plane_i),
      .tri_g_plane_i(tri_g_plane_i),
      .tri_b_plane_i(tri_b_plane_i),
      .tri_flat_request_i(tri_flat_request_i),
      .tri_continuation_tail_i(tri_continuation_tail_i),
      .tri_fragment_state_i(tri_fragment_state_i),
      .tok_req_o(tok_req_o), .tok_grant_i(tok_grant_i),
      .frame_fault_clear_valid_i(frame_fault_clear_valid_i),
      .frame_fault_clear_ready_o(frame_fault_clear_ready_o),
      .frame_fault_o(frame_fault_o),
      .lifetime_structural_fault_o(lifetime_structural_fault_o),
      .cfg_valid_i(cfg_valid_i), .cfg_ready_o(cfg_ready_o),
      .cfg_op_i(cfg_op_i), .cfg_page_generation_i(cfg_page_generation_i),
      .cfg_selector_i(cfg_selector_i), .cfg_row_i(cfg_row_i),
      .cfg_crc32_i(cfg_crc32_i), .cfg_rsp_valid_o(cfg_rsp_valid_o),
      .cfg_rsp_ready_i(cfg_rsp_ready_i), .cfg_rsp_op_o(cfg_rsp_op_o),
      .cfg_rsp_status_o(cfg_rsp_status_o),
      .cfg_rsp_page_generation_o(cfg_rsp_page_generation_o),
      .active_page_generation_o(active_page_generation_o),
      .fill_req_valid_o(fill_req_valid_o), .fill_req_ready_i(fill_req_ready_i),
      .fill_req_addr_o(fill_req_addr_o), .fill_data_valid_i(fill_data_valid_i),
      .fill_data_i(fill_data_i), .fill_refused_i(fill_refused_i),
      .pal_load_valid_i(pal_load_valid_i), .pal_load_ready_o(pal_load_ready_o),
      .pal_load_op_i(pal_load_op_i), .pal_load_slot_i(pal_load_slot_i),
      .pal_load_gen_i(pal_load_gen_i), .pal_load_idx_i(pal_load_idx_i),
      .pal_load_rgb565_i(pal_load_rgb565_i), .pal_load_crc_ok_i(pal_load_crc_ok_i),
      .sheet_req_valid_o(sheet_req_valid_o),
      .sheet_req_ready_i(sheet_req_ready_i), .sheet_req_op_o(sheet_req_op_o),
      .sheet_req_handle_o(sheet_req_handle_o), .sheet_req_texel_o(sheet_req_texel_o),
      .sheet_req_src_id_o(sheet_req_src_id_o),
      .pg_valid_i(pg_valid_i), .pg_ready_o(pg_ready_o), .pg_op_i(pg_op_i),
      .pg_status_i(pg_status_i), .pg_tag_i(pg_tag_i),
      .pg_strength_i(pg_strength_i), .pg_src_id_i(pg_src_id_i),
      .fb_valid_o(fb_valid_o), .fb_ready_i(fb_ready_i),
      .fb_rgb565_o(fb_rgb565_o), .fb_tag_o(fb_tag_o), .fb_addr_o(fb_addr_o),
      .fb_x_o(fb_x_o), .fb_y_o(fb_y_o), .fb_last_o(fb_last_o),
      .fb_src_id_o(fb_src_id_o), .tile_crc_o(tile_crc_o),
      .tile_crc_index_o(tile_crc_index_o), .tile_done_o(tile_done_o),
      .tile_cov_count_o(tile_cov_count_o), .tile_degenerate_o(tile_degenerate_o),
      .drain_busy_o(drain_busy_o), .drain_done_o(drain_done_o),
      .binner_initialized_o(binner_initialized_o),
      .binner_tile_references_o(binner_tile_references_o),
      .binner_max_tile_list_depth_o(binner_max_tile_list_depth_o),
      .binner_triangles_culled_o(binner_triangles_culled_o),
      .binner_overflow_o(binner_overflow_o),
      .binner_arena_full_o(binner_arena_full_o),
      .binner_arena_used_o(binner_arena_used_o),
      .jobs_taken_o(jobs_taken_o), .job_stall_clocks_o(job_stall_clocks_o),
      .quiet_o(quiet_o), .raster_abort_o(raster_abort_o),
      .local_attribute_abort_o(local_attribute_abort_o),
      .local_fault_pulse_o(local_fault_pulse_o),
      .local_fault_count_o(local_fault_count_o),
      .coordinate_fault_count_o(coordinate_fault_count_o),
      .range_fault_count_o(range_fault_count_o),
      .aux_profile_fault_count_o(aux_profile_fault_count_o),
      .candidate_cancel_count_o(candidate_cancel_count_o),
      .local_drop_count_o(local_drop_count_o),
      .raster_jobs_started_o(raster_jobs_started_o),
      .raster_jobs_sunk_o(raster_jobs_sunk_o),
      .sequence_abort_o(sequence_abort_o),
      .sequence_mismatch_o(sequence_mismatch_o),
      .sequence_drop_count_o(sequence_drop_count_o),
      .admission_sequence_o(admission_sequence_o),
      .expected_sequence_o(expected_sequence_o),
      .returned_sequence_o(returned_sequence_o),
      .packet_c_cand_fire_o(packet_c_cand_fire_o),
      .packet_c_fragment_fire_o(packet_c_fragment_fire_o),
      .packet_c_drop_fire_o(packet_c_drop_fire_o),
      .tilestore_references_o(tilestore_references_o),
      .resolved_tiles_o(resolved_tiles_o),
      .early_z_rejects_o(early_z_rejects_o),
      .early_z_covered_o(early_z_covered_o),
      .fragment_covered_o(fragment_covered_o),
      .blended_fragments_o(blended_fragments_o),
      .texture_fragments_o(texture_fragments_o),
      .texture_cache_hits_o(texture_cache_hits_o),
      .texture_cache_misses_o(texture_cache_misses_o),
      .texture_palette_lookups_o(texture_palette_lookups_o),
      .texture_plan_accepted_o(texture_plan_accepted_o),
      .texture_dispatch_accepted_o(texture_dispatch_accepted_o),
      .texture_combine_refused_o(texture_combine_refused_o),
      .texture_samples_o(texture_samples_o),
      .fragment_error_o(fragment_error_o),
      .coverage_hold_valid_o(coverage_hold_valid_o),
      .coverage_delivered_mask_o(coverage_delivered_mask_o),
      .start_delivered_mask_o(start_delivered_mask_o),
      .attribute_idle_o(attribute_idle_o),
      .earlyz_hold_valid_o(earlyz_hold_valid_o), .skid_level_o(skid_level_o),
      .stage_candidate_valid_o(stage_candidate_valid_o),
      .stage_candidate_data_o(stage_candidate_data_o),
      .stage_fragment_valid_o(stage_fragment_valid_o),
      .stage_fragment_addr_o(stage_fragment_addr_o),
      .stage_fragment_depth_o(stage_fragment_depth_o),
      .stage_fragment_state_o(stage_fragment_state_o),
      .stage_fragment_src_id_o(stage_fragment_src_id_o),
      .stage_fragment_texel_rgb_o(stage_fragment_texel_rgb_o),
      .stage_fragment_texel_a_o(stage_fragment_texel_a_o),
      .stage_fragment_texel_idx_o(stage_fragment_texel_idx_o),
      .stage_fragment_status_o(stage_fragment_status_o),
      .texture_quiet_o(texture_quiet_o), .fragment_idle_o(fragment_idle_o),
      .front_bank_o(front_bank_o), .bin_mask_o(bin_mask_o), .z_floor_o(z_floor_o),
      .test_start_enable_i(test_start_enable_i),
      .test_attr_cov_enable_i(test_attr_cov_enable_i),
      .test_stage_admit_enable_i(test_stage_admit_enable_i)
  );

  logic old_drain_busy_w;
  logic [31:0] old_binner_refs_w, old_tri_culled_w;
  logic [15:0] old_max_depth_w;
  logic old_overflow_w, old_arena_full_w;
  logic [31:0] old_jobs_taken_w, old_job_stalls_w;
  logic [31:0] old_earlyz_rejects_w;
  logic old_fragment_error_w;

  zhao_geom_bin_pipe u_old (
      .clk(clk), .rst_n(rst_n),
      .frame_begin_i(frame_begin_i && old_enable_i),
      .frame_end_i(frame_end_i && old_enable_i),
      .grid_w_i(grid_w_i), .grid_h_i(grid_h_i),
      .tri_valid_i(old_tri_valid_w), .tri_ready_o(old_tri_ready_w),
      .tri_kx0_i(tri_kx0_i), .tri_ky0_i(tri_ky0_i), .tri_kc0_i(tri_kc0_i),
      .tri_kx1_i(tri_kx1_i), .tri_ky1_i(tri_ky1_i), .tri_kc1_i(tri_kc1_i),
      .tri_kx2_i(tri_kx2_i), .tri_ky2_i(tri_ky2_i), .tri_kc2_i(tri_kc2_i),
      .tri_tl_i(tri_tl_i),
      .tri_ax_i(tri_ax_i), .tri_ay_i(tri_ay_i),
      .tri_bx_i(tri_bx_i), .tri_by_i(tri_by_i),
      .tri_cx_i(tri_cx_i), .tri_cy_i(tri_cy_i),
      .tri_min_x_i(tri_min_x_i), .tri_max_x_i(tri_max_x_i),
      .tri_min_y_i(tri_min_y_i), .tri_max_y_i(tri_max_y_i),
      .tri_src_id_i(tri_src_id_i),
      .tok_req_o(old_tok_req_w), .tok_grant_i(tok_grant_i),
      .job_fill_word_i(old_job_fill_word_i),
      .job_clear_word_i(old_clear_q),
      .job_state_i(old_job_state_i),
      .job_src_a_i(old_job_src_a_i),
      .job_texel_rgb_i(old_job_texel_rgb_i),
      .job_texel_a_i(old_job_texel_a_i),
      .job_texel_idx_i(old_job_texel_idx_i),
      .fb_valid_o(old_fb_valid_o), .fb_ready_i(fb_ready_i),
      .fb_rgb565_o(old_fb_rgb565_o), .fb_tag_o(old_fb_tag_o),
      .fb_addr_o(old_fb_addr_o), .fb_x_o(old_fb_x_o), .fb_y_o(old_fb_y_o),
      .fb_last_o(old_fb_last_o), .fb_src_id_o(old_fb_src_id_o),
      .tile_crc_o(old_tile_crc_o), .tile_crc_index_o(old_tile_crc_index_o),
      .tile_done_o(old_tile_done_o), .tile_cov_count_o(old_tile_cov_count_o),
      .tile_degenerate_o(old_tile_degenerate_o),
      .drain_busy_o(old_drain_busy_w), .drain_done_o(old_drain_done_o),
      .tile_references_o(old_binner_refs_w),
      .max_tile_list_depth_o(old_max_depth_w),
      .triangles_culled_o(old_tri_culled_w), .overflow_o(old_overflow_w),
      .arena_full_o(old_arena_full_w), .jobs_taken_o(old_jobs_taken_w),
      .job_stall_clocks_o(old_job_stalls_w),
      .early_z_rejects_o(old_earlyz_rejects_w),
      .fragment_error_o(old_fragment_error_w)
  );

  // Test-only oracle observability not promoted to the C++ boundary.
  logic unused_old;
  assign unused_old = ^{1'b0, old_tok_req_w, old_drain_busy_w,
                        old_binner_refs_w, old_max_depth_w, old_tri_culled_w,
                        old_overflow_w, old_arena_full_w,
                        old_jobs_taken_w, old_job_stalls_w,
                        old_earlyz_rejects_w, old_fragment_error_w};

endmodule : tb_geom_bin_pipe_v2

`default_nettype wire
