// GENERATED-BY-HAND ONCE, from zhao_cmd_exec's port list, and it is a
// DECLARATION list rather than a connection list: `.*` binds each of these
// to the port of the same name, so a port added to that block appears here as
// an ELABORATION ERROR rather than as a PINMISSING reading zero.
//
// The six names NOT here are the ones this harness drives itself: clk, rst_n,
// pkt_valid_i, pkt_byte_i, pkt_len_i, verdict_valid_i, verdict_error_i --
// plus pkt_fork_ready_i, which is the FORK and is assigned beside the
// include, and pkt_ready_o, which is that block's OWN ready and is connected
// EXPLICITLY to `exe_ready` -- the wrapper's own port of that name is the AND
// of both consumers, and binding the two together by `.*` would make the fork
// feed itself.

  // SEALPLAN 2026-09-26, console entry I56: the frame admission plan.
  logic        plan_valid_o;
  logic [ 7:0] plan_view_o;
  logic [ 7:0] plan_flags_o;
  logic [15:0] plan_res_gen_o;
  logic [15:0] plan_view_gen_o;
  logic [15:0] plan_giant_inst_o;
  logic [17:0] plan_verts_o;
  logic [17:0] plan_tris_o;
  logic [17:0] plan_chunks_o;
  logic [17:0] plan_refs_o;
  logic [17:0] plan_giant_refs_o;
  logic [31:0] plans_forwarded_o;
  logic [31:0] plans_malformed_o;

  logic proj_cfg_we_o;
  logic proj_cfg_ready_i;
  logic proj_cfg_view_o;
  logic [ 4:0] proj_cfg_addr_o;
  logic [31:0] proj_cfg_data_o;
  logic stamp_valid_o;
  logic stamp_ready_i;
  logic [31:0] stamp_patch_o;
  logic [ 7:0] stamp_operation_o;
  logic [ 7:0] stamp_tag_o;
  logic [15:0] stamp_strength_o;
  logic signed [31:0] stamp_tx_o;
  logic signed [31:0] stamp_ty_o;
  logic signed [31:0] stamp_radius_o;
  logic signed [31:0] stamp_ring_width_o;
  logic [15:0] stamp_src_id_o;
  logic draw_valid_o;
  logic draw_ready_i;
  logic [31:0] draw_form_o;
  logic [31:0] draw_material_set_o;
  logic [31:0] draw_transform_o;
  logic [ 7:0] draw_viewport_mask_o;
  logic [ 7:0] draw_semantic_weight_o;
  logic [15:0] draw_flags_o;
  logic [15:0] draw_src_id_o;
  logic draw_posed_o;
  logic [15:0] draw_clip_id_o;
  logic [15:0] draw_frame_no_o;
  logic [ 7:0] draw_sub_o;
  logic draw_warp_en_o;
  logic [31:0] draw_warp_program_o;
  logic [31:0] draw_warp_time_o;
  logic [127:0] draw_warp_par_o;
  logic [127:0] draw_warp_attr_o;
  logic [31:0] draw_warp_attr_res_o;
  logic [ 7:0] draw_warp_attr_mode_o;
  logic signed [31:0] draw_warp_bx_o;
  logic signed [31:0] draw_warp_by_o;
  logic signed [31:0] draw_warp_bz_o;
  logic upl_valid_o;
  logic upl_ready_i;
  logic [23:0] upl_index_o;
  logic [ 7:0] upl_kind_o;
  logic [63:0] upl_hps_addr_o;
  logic [31:0] upl_vram_addr_o;
  logic [31:0] upl_len_o;
  logic [15:0] upl_epoch_o;
  logic [ 7:0] upl_dst_slot_o;
  logic [15:0] upl_new_gen_o;
  logic [31:0] upl_crc_o;
  logic env_valid_o;
  logic env_ready_i;
  logic [15:0] env_sun_yaw_o;
  logic [15:0] env_sun_pitch_o;
  logic [15:0] env_sun_colour_o;
  logic [15:0] env_ambient_o;
  logic [31:0] envs_issued_o;
  logic pop_valid_o;
  logic pop_ready_i;
  logic [31:0] pop_population_o;
  logic [31:0] pop_origin_x_o;
  logic [31:0] pop_origin_y_o;
  logic [31:0] pop_origin_z_o;
  logic [31:0] pop_active_count_o;
  logic [31:0] pop_plane_c_o;
  logic [15:0] pop_plane_nx_o;
  logic [15:0] pop_plane_ny_o;
  logic [15:0] pop_plane_nz_o;
  logic [15:0] pop_flags_o;
  logic [31:0] pops_issued_o;
  logic tfld_valid_o;
  logic tfld_ready_i;
  logic signed [31:0] tfld_x0_o;
  logic signed [31:0] tfld_z0_o;
  logic signed [31:0] tfld_x1_o;
  logic signed [31:0] tfld_z1_o;
  logic [31:0] tfld_handle_o;
  logic [15:0] tfld_cmd_o;
  logic [31:0] tfld_start_tick_o;
  logic [31:0] tfld_duration_o;
  logic [255:0] tfld_params_o;
  logic tfld_last_o;
  logic [31:0] tflds_issued_o;
  logic forge_valid_o;
  logic forge_ready_i;
  logic [31:0] forge_program_o;
  logic [31:0] forge_material_o;
  logic [15:0] forge_material_id_o;
  logic [ 7:0] forge_kind_o;
  logic [15:0] forge_frame_tick_o;
  logic [15:0] forge_src_id_o;
  logic [31:0] forges_issued_o;
  logic [31:0] forge_overflow_o;
  logic [31:0] forge_src_truncated_o;
  logic [31:0] tfld_overflow_o;
  logic [31:0] tfld_src_truncated_o;
  logic tok_budget_valid_o;
  logic [31:0] tok_budget_geom0_o;
  logic [31:0] tok_budget_geom1_o;
  logic [31:0] tok_budget_frag0_o;
  logic [31:0] tok_budget_frag1_o;
  logic [31:0] tok_budget_shared_o;
  logic tok_vreq_valid_o;
  logic tok_vreq_view_o;
  logic [31:0] tok_vreq_geom_o;
  logic [31:0] tok_vreq_frag_o;
  logic [31:0] contracts_applied_o;
  logic [ 1:0] gov_view_count_o;
  logic [31:0] gov_px_err0_o;
  logic [31:0] gov_px_err1_o;
  logic [31:0] view_count_refused_o;
  logic post_idle_i;
  logic post_look_busy_o;
  logic [ 7:0] post_bloom_gain_o;
  logic post_grade_valid_o;
  logic post_echo_arm_o;
  logic signed [8:0] post_bias_r_o;
  logic signed [8:0] post_bias_g_o;
  logic signed [8:0] post_bias_b_o;
  logic [15:0] post_flash_rgb_o;
  logic [ 7:0] post_flash_amt_o;
  logic [15:0] post_ink_rgb_o;
  logic post_pv_we_o;
  logic [ 1:0] post_pv_sel_o;
  logic [ 5:0] post_pv_addr_o;
  logic [71:0] post_pv_data_o;
  logic dbg_trace_arm_we_o;
  logic [6:0] dbg_trace_arm_mask_o;
  logic dbg_trace_clear_o;
  logic [31:0] packets_committed_o;
  logic [31:0] packets_abandoned_o;
  logic [31:0] views_written_o;
  logic [31:0] stamps_issued_o;
  logic [31:0] stamp_overflow_o;
  logic [31:0] view_range_refused_o;
  logic [31:0] stamp_src_truncated_o;
  logic [31:0] draws_issued_o;
  logic [31:0] draw_overflow_o;
  logic [31:0] draw_src_truncated_o;
  logic [31:0] posed_draws_issued_o;
  logic [31:0] pose_clip_refused_o;
  logic [31:0] warp_draws_issued_o;
  logic [31:0] warp_draw_refused_o;
  logic [31:0] uploads_issued_o;
  logic [31:0] upload_overflow_o;
  logic [31:0] post_looks_applied_o;
  logic [31:0] grade_entries_written_o;
  logic [31:0] post_refused_o;
  logic [31:0] grade_overflow_o;
  logic [31:0] trace_arms_applied_o;
  logic [31:0] trace_arm_refused_o;
  logic [31:0] viewport_range_refused_o;
  logic tpl_valid_o;
  logic tpl_ready_i;
  logic [ 7:0] tpl_slot_o;
  logic [ 7:0] tpl_role_o;
  logic [ 7:0] tpl_blend_o;
  logic [ 7:0] tpl_opacity_o;
  logic [ 7:0] tpl_format_o;
  logic [ 7:0] tpl_wrap_o;
  logic [ 7:0] tpl_view_mask_o;
  logic [ 7:0] tpl_palette_o;
  logic [15:0] tpl_width_o;
  logic [15:0] tpl_height_o;
  logic [15:0] tpl_flags_o;
  logic [15:0] tpl_base_o;
  logic [ 7:0] tpl_lstride_o;
  logic [ 7:0] tpl_lheight_o;
  logic signed [31:0] tpl_a_o;
  logic signed [31:0] tpl_b_o;
  logic signed [31:0] tpl_c_o;
  logic signed [31:0] tpl_d_o;
  logic signed [31:0] tpl_u0_o;
  logic signed [31:0] tpl_v0_o;
  logic signed [31:0] tpl_line_scroll_o;
  logic tsp_valid_o;
  logic tsp_ready_i;
  logic signed [15:0] tsp_x_o;
  logic signed [15:0] tsp_y_o;
  logic [15:0] tsp_w_o;
  logic [15:0] tsp_h_o;
  logic [15:0] tsp_base_o;
  logic [ 7:0] tsp_lstride_o;
  logic [ 7:0] tsp_lheight_o;
  logic [ 7:0] tsp_format_o;
  logic [ 7:0] tsp_palette_o;
  logic [ 7:0] tsp_blend_o;
  logic [ 7:0] tsp_view_mask_o;
  logic [15:0] tsp_tint_o;
  logic [ 7:0] tsp_order_o;
  logic [ 7:0] tsp_flags_o;
  logic [15:0] tsp_src_id_o;
  logic signed [31:0] tsp_u_o;
  logic signed [31:0] tsp_v_o;
  logic signed [31:0] tsp_a00_o;
  logic signed [31:0] tsp_a01_o;
  logic signed [31:0] tsp_a10_o;
  logic signed [31:0] tsp_a11_o;
  logic twod_pkt_commit_o;
  logic twod_pkt_abandon_o;
  logic tld_valid_o;
  logic tld_ready_i;
  logic [23:0] tld_index_o;
  logic [63:0] tld_hps_addr_o;
  logic [31:0] tld_len_o;
  logic [31:0] tld_crc_o;
  logic [15:0] tld_epoch_o;
  logic [ 7:0] tld_dst_slot_o;
  logic [31:0] twod_planes_staged_o;
  logic [31:0] twod_sprites_staged_o;
  logic [31:0] twod_dropped_o;
  logic [31:0] twod_loads_issued_o;
  logic [31:0] unsupported_o;
// count: 213
