// render_golden.cpp — W3.5 golden canvas: a synthetic TWO-VIEW Duo frame
// exercising every promoted command (SetPresentationContract, SetView x2,
// DrawSky, TerrainField via a hand-built earth program, SurfaceStamp,
// DrawProcedural island, DrawForm x2, DrawPopulation, EmitAudioEvent x2)
// renders to a COMMITTED golden canvas CRC (both the canvas CRC and the
// video_rules §4 displayed-stream CRC), with run-twice determinism and a
// fresh-instance determinism check.
//
// Law: plan W3.5 acceptance ("synthetic 2-view frame rendering to a
// committed golden canvas CRC"), spec/video_rules.md §3.1/§4, the D7
// command set, spec/form/field-ir.md §5/§7.1 (a hand-built earth .zprog
// consumed through the ONE zfield interpreter).

#include "render_helpers.hpp"

#include "zfield/zfield.hpp"

#include <cstdio>
#include <cstring>

namespace {

int failures = 0;
void check(bool ok, const char* what) {
  if (!ok) {
    std::fprintf(stderr, "FAIL: %s\n", what);
    ++failures;
  }
}

// ---- committed golden values (regenerated by deleting + rerunning once; any
// renderer change that moves these MUST be justified in the commit message)
// Regenerated 2026-08-15, twice:
//   CRITICAL-1 drum-angle fix — the 1536 band triangles were degenerate and
//     rasterised NOTHING; the drum now renders (15AB7655 -> 4D179BE6).
//   CRITICAL-2 sun alpha (wrapped 256 -> 0, sun invisible) + MAJOR-4 pass-6
//     sub-order (sun now rasters BEFORE cloud) (4D179BE6 -> 5475D2D1).
//   MAJOR-2 §8 fill rule `E' + bias >= 0` — the strict `>` dropped every
//     shared-edge pixel on BOTH sides (5475D2D1 -> B56D4F2A).
//   §8 raster COVERAGE fixes (user-reported 1px cracks): the scan bbox is the
//     pixel-CENTRE range, not ceil/floor of the vertex extent, and the
//     top-left bias applies to the exact s64 E0, not to the floored E' =
//     E0>>8 (B56D4F2A -> 6396C558).
//   heightfield shading normal rescale(cross, 32) -> rescale(cross, 16): the
//     cross of two Q16.16 edge vectors is Q32.32, so >>32 quantised the
//     normal to whole world-units^2 (black below ~1 m spacing). The golden
//     island is 17x17 over +-8 m = exactly 1 m, so its shading moves from the
//     quantised normal to the exact one (6396C558 -> 803958B5).
//   Duo PACKED two-block layout ratified (review MAJOR-3): view 0 at slot
//     bytes [0,0x18000), view 1 at [0x18000,0x30000), each contiguous — the
//     canvas bytes are rearranged, the displayed CRC is now assembled at
//     scanout, and view 1's marker (wall-clamped with viewport-relative
//     bounds and then scissored) becomes VISIBLE for the first time
//     (803958B5 -> D56BB9F4).
//   sky §1.2 perspective amendment (2026-08-16, owner report "ovals, not
//     sky"): the sky path now projects with w = the rotation's z row instead
//     of w = 1, so the behind-camera drum half culls instead of overpainting
//     the far half, and the under-plane is an 8x8 grid. Every sky pixel of
//     this synthetic frame moves (D56BB9F4 -> 2BCCF8FB), and the cap fan
//     re-pitched to the drum's 48 yawed columns closes the rim slivers
//     (2BCCF8FB -> 41C51A73).
//   resolve white-rail fix (2026-08-16, found by the star compositor): the
//     green dither overflowed the 6-bit field for g >= 252 at Bayer >= 8,
//     wrapping full white to magenta on half the phases; the white spark
//     particles in this frame carried the wrap (41C51A73 -> 47893F4C).
//   resolve GREEN AMPLITUDE corrected (2026-08-18, owner: "we do it right from
//     the start"): green dithered at (B*32 + 16), double the threshold
//     resolve.cpp's own header states. One quantization step is 255 numerator
//     units for every channel, so (B+0.5)/16 of a step is (B*16 + 8)
//     throughout. The doubled value lifted pure black to 0x0020 on half the
//     Bayer phases and, at the other rail, produced the 64 that the 2026-08-16
//     clamp was added to catch. Correcting the amplitude closes both, and this
//     frame's blacks and near-blacks move with it
//     (B1B5171A -> B36E44B2 / 2B73E8CB -> E514CD5C).
constexpr uint32_t kGoldenCanvasCrc = 0xB36E44B2u;  // [w3.5-golden] re-pinned
// 2026-08-16: kBandRows 8->16 (dcb32ff, the banding fix) moved both goldens;
// the constants before that were 0x47893F4C / 0xC3ED350F.
constexpr uint32_t kGoldenDisplayedCrc = 0xE514CD5Cu;  // [w3.5-golden] re-pinned
constexpr uint32_t kGoldenFieldOffCanvasCrc = 0x0u;    // filled below if 0

// view-projections: simple perspective (w = z + 32 m) — view 1 shifts the
// camera (w = z + 40, eye 14 m) so the two Duo views differ
zhao_abi::ZhMat4fx vp_view(uint32_t view) {
  const int32_t eye = view == 0 ? 12 : 14;
  const int32_t camz = view == 0 ? 32 : 40;
  const int32_t m[16] = {2 << 16, 0, 0,       0, 0, -2 << 16, 0,       (2 * eye) << 16,
                         0,       0, 1 << 16, 0, 0, 0,        1 << 16, camz << 16};
  return rtest::mat(m);
}

zhao_abi::ZhMat4fx sky_rot(uint32_t view) {
  // tilted rotation-only drum view (tilt differs per view)
  const int32_t a = 12 + static_cast<int32_t>(view);
  const int32_t b = 9 - static_cast<int32_t>(view);
  const int32_t m[16] = {a, 0, 0, 0, 0, b, -b, 0, 0, b, b, 0, 0, 0, 0, 1 << 16};
  return rtest::mat(m);
}

struct Scene {
  zref::render::TerrainPatch patch;
  zref::render::Material mat{96, 128, 72};
  zref::render::FormPattern wizard;
  zref::render::Population sparks;
  zref::sky::SkySet sky;
  zfield::DecodeResult prog;

  Scene() {
    patch = rtest::bump_patch(17, 17, 8, 10);  // +-8 m, 10 m peak
    for (int i = 0; i < 64; ++i) {
      wizard.mask[i] = static_cast<uint8_t>((i / 8) % 2 == (i % 8) % 2 ? 1 : 0);
      wizard.rgb[i * 3 + 0] = 240;
      wizard.rgb[i * 3 + 1] = 200;
      wizard.rgb[i * 3 + 2] = 60;
    }
    sparks.parts.push_back({-2 << 16, 3 << 16, -2 << 16, 96, 255, 80, 80});
    sparks.parts.push_back({3 << 16, 4 << 16, -1 << 16, 64, 80, 120, 255});
    sparks.parts.push_back({0, 5 << 16, -3 << 16, 48, 255, 255, 255});
    sky.background = {6, 10, 20};
    sky.band_lower_horizon = {96, 128, 208};
    sky.band_lower_top = {150, 176, 236};
    sky.band_upper_bottom = {150, 176, 236};
    sky.band_upper_top = {236, 246, 255};
    sky.cap = {248, 250, 255};
    sky.under = {18, 28, 40};
    sky.cloud = {252, 252, 252};
    sky.sun = {255, 238, 196};
    sky.cloud_max_alpha = zref::fx16{0xB000};
    sky.sun_energy = zref::fx16{1 << 16};
    sky.sun_dir_x = zref::fx16{INT32_C(-3) * 8192};
    sky.sun_dir_z = zref::fx16{-1 * 32768};
    const std::vector<uint8_t> bytes = rtest::make_earth_prog();
    prog = zfield::decode(bytes.data(), bytes.size());
  }
};

std::vector<uint8_t> golden_packet(uint32_t frame_id, bool with_field) {
  return rtest::seal_frame(frame_id, [&](zhao::ZhaoFrameBuilder& b) {
    auto spc = zhao_abi::zhao_sample_set_presentation_contract();
    spc.payload.mode = zhao_abi::VIDEO_DUO;
    spc.payload.view_count = 2;
    std::vector<uint8_t> v0;
    zhao_abi::zhao_pack_set_presentation_contract(spc, v0);
    b.append_record(v0);
    for (uint32_t v = 0; v < 2; ++v) {
      auto sv = zhao_abi::zhao_sample_set_view();
      sv.payload.view_id = static_cast<uint8_t>(v);
      sv.payload.view_projection = vp_view(v);
      std::vector<uint8_t> v1;
      zhao_abi::zhao_pack_set_view(sv, v1);
      b.append_record(v1);
    }
    auto sk = zhao_abi::zhao_sample_draw_sky();
    sk.payload.sky_set = 2;
    sk.payload.rot_proj[0] = sky_rot(0);
    sk.payload.rot_proj[1] = sky_rot(1);
    sk.payload.cloud_scroll_u = 0;  // tick-driven scroll lives in the tick
    sk.payload.cloud_scroll_v = 0;
    sk.payload.drum_yaw = 0x0200;
    sk.payload.viewport_mask = 3;
    sk.payload.flags = zref::sky::kLayerUnder | zref::sky::kLayerCloud | zref::sky::kLayerSun |
                       zref::sky::kLayerCap;
    std::vector<uint8_t> v2;
    zhao_abi::zhao_pack_draw_sky(sk, v2);
    b.append_record(v2);

    if (with_field) {
      auto tf = zhao_abi::zhao_sample_terrain_field();
      tf.payload.program = 5;  // the hand-built earth program
      tf.payload.footprint.x0 = -4 * (1 << 16);
      tf.payload.footprint.y0 = -4 * (1 << 16);
      tf.payload.footprint.x1 = 4 * (1 << 16);
      tf.payload.footprint.y1 = 4 * (1 << 16);
      tf.payload.start_tick = 100;
      tf.payload.duration_ticks = 600;
      // p0 = 2.0 m (LE Q16.16: 00 00 02 00), rest zero (the blob law)
      std::memset(tf.payload.parameters, 0, 64);
      tf.payload.parameters[2] = 2;
      std::vector<uint8_t> v3;
      zhao_abi::zhao_pack_terrain_field(tf, v3);
      b.append_record(v3);
    }

    auto st = zhao_abi::zhao_sample_surface_stamp();
    st.payload.patch = 44;
    st.payload.tag = 1;  // crack-ring scar
    st.payload.strength = 0xD000;
    st.payload.transform = rtest::xform_identity();
    st.payload.radius = 5 << 16;
    st.payload.ring_width = 2 << 16;
    std::vector<uint8_t> v4;
    zhao_abi::zhao_pack_surface_stamp(st, v4);
    b.append_record(v4);

    auto dp = zhao_abi::zhao_sample_draw_procedural();
    dp.payload.program = 44;
    dp.payload.material = 45;
    dp.payload.transform = rtest::xform_identity();
    dp.payload.screen_error = 1 << 16;
    dp.payload.kind = zhao_abi::FORGE_HEIGHTFIELD_PATCH;
    std::vector<uint8_t> v5;
    zhao_abi::zhao_pack_draw_procedural(dp, v5);
    b.append_record(v5);

    // the two wizards: view masks separate, in front of the island (z=-4)
    for (int w = 0; w < 2; ++w) {
      auto df = zhao_abi::zhao_sample_draw_form();
      df.payload.form = 7;
      df.payload.transform = static_cast<uint32_t>(8 + w);
      df.payload.viewport_mask = static_cast<uint8_t>(1 << w);
      df.payload.flags = 0x0002;  // screen-space marker law
      std::vector<uint8_t> v6;
      zhao_abi::zhao_pack_draw_form(df, v6);
      b.append_record(v6);
    }

    auto dpop = zhao_abi::zhao_sample_draw_population();
    dpop.payload.population = 3;
    dpop.payload.viewport_mask = 3;
    dpop.payload.flags = 0x0003;
    std::vector<uint8_t> v7;
    zhao_abi::zhao_pack_draw_population(dpop, v7);
    b.append_record(v7);

    for (uint32_t e = 0; e < 2; ++e) {
      auto ea = zhao_abi::zhao_sample_emit_audio_event();
      ea.payload.event_id = 10 + e;
      ea.payload.pan_fx = static_cast<int16_t>(e == 0 ? -4096 : 4096);
      ea.payload.gain = 0xA000;
      ea.payload.sample_handle = e;
      ea.payload.timestamp = frame_id;
      std::vector<uint8_t> v8;
      zhao_abi::zhao_pack_emit_audio_event(ea, v8);
      b.append_record(v8);
    }
  });
}

zref::render::RenderResources golden_resources(const Scene& sc) {
  zref::render::RenderResources res;
  res.field_programs.push_back({5, &sc.prog.prog});
  res.terrain_patches.push_back({44, &sc.patch});
  res.materials.push_back({45, sc.mat});
  res.forms.push_back({7, sc.wizard});
  res.transforms.push_back({8, zref::render::FormTransform{-3 << 16, 2 << 16, -4 << 16, 12 << 16}});
  res.transforms.push_back({9, zref::render::FormTransform{3 << 16, 2 << 16, -4 << 16, 12 << 16}});
  res.populations.push_back({3, sc.sparks});
  res.sky_sets.push_back({2, sc.sky});
  return res;
}

}  // namespace

int main() {
  Scene sc;
  check(sc.prog.error == zfield::DecodeError::kOk,
        "hand-built earth program decodes (the ONE interpreter input)");
  const zref::render::RenderResources res = golden_resources(sc);
  const std::vector<uint8_t> pkt = golden_packet(150, true);

  // frame 1 latches Duo but renders Z60 (§1.1) — run one throwaway frame
  zref::render::RenderCanvas canvas;
  zref::render::SoftwareRenderer rend;
  zref::render::RenderResult warm = rend.render_frame(pkt, 0, canvas, res);
  check(warm.status == zhao_abi::ZH_ABI_OK, "warm-up frame ok");

  // the golden frame (frame 2 renders Duo)
  const zref::render::RenderResult r = rend.render_frame(pkt, 0, canvas, res);
  check(r.status == zhao_abi::ZH_ABI_OK, "golden frame renders");
  check(r.frame_id == 150, "frame id carried");
  check(r.audio_events.size() == 2 && r.audio_events[1].pan_fx == 4096,
        "audio events collected in stream order");
  // TerrainField evaluated over the +-4 m footprint: 17 columns at 1 m
  // spacing -> 9 x 9 = 81 samples, recorded ONCE (first view)
  check(r.terrain_velocity.size() == 81, "velocity lane recorded per footprint column (once)");

  // run-twice determinism: a second identical frame byte-identical canvas
  std::vector<uint8_t> snapshot(canvas.slot[0].begin(), canvas.slot[0].end());
  const zref::render::RenderResult r2 = rend.render_frame(pkt, 0, canvas, res);
  check(r2.canvas_crc32c == r.canvas_crc32c && r2.displayed_crc32c == r.displayed_crc32c,
        "run-twice CRC determinism");
  check(std::memcmp(snapshot.data(), canvas.slot[0].data(), snapshot.size()) == 0,
        "run-twice canvas byte-identical");

  // fresh instance determinism (no hidden state)
  zref::render::RenderCanvas fresh_canvas;
  zref::render::SoftwareRenderer fresh;
  fresh.render_frame(pkt, 0, fresh_canvas, res);  // Z60 warm-up
  const zref::render::RenderResult r3 = fresh.render_frame(pkt, 0, fresh_canvas, res);
  check(r3.canvas_crc32c == r.canvas_crc32c, "fresh renderer instance: same golden CRC");

  // the field actually moved terrain: no-field variant CRC differs
  const std::vector<uint8_t> pkt_nofield = golden_packet(150, false);
  zref::render::RenderCanvas nf_canvas;
  zref::render::SoftwareRenderer nf_rend;
  nf_rend.render_frame(pkt_nofield, 0, nf_canvas, res);
  const zref::render::RenderResult nf = nf_rend.render_frame(pkt_nofield, 0, nf_canvas, res);
  check(nf.status == zhao_abi::ZH_ABI_OK && nf.terrain_velocity.empty() &&
            nf.canvas_crc32c != r.canvas_crc32c,
        "TerrainField off: no velocities, different canvas");

  // golden compare (the committed constants)
  if (kGoldenCanvasCrc != 0) {
    if (r.canvas_crc32c != kGoldenCanvasCrc)
      std::fprintf(stderr, "  canvas CRC got %08X want %08X\n", r.canvas_crc32c, kGoldenCanvasCrc);
    if (r.displayed_crc32c != kGoldenDisplayedCrc)
      std::fprintf(stderr, "  displayed CRC got %08X want %08X\n", r.displayed_crc32c,
                   kGoldenDisplayedCrc);
    check(r.canvas_crc32c == kGoldenCanvasCrc, "golden canvas CRC");
    check(r.displayed_crc32c == kGoldenDisplayedCrc, "golden displayed CRC");
  } else {
    std::printf(
        "render_golden: RECORD goldens { canvas %08X displayed %08X "
        "fieldoff %08X }\n",
        r.canvas_crc32c, r.displayed_crc32c, nf.canvas_crc32c);
  }
  (void)kGoldenFieldOffCanvasCrc;

  if (failures == 0) std::printf("render_golden: all green\n");
  return failures == 0 ? 0 : 1;
}
