#!/usr/bin/env python3
r"""Cut tests/mutants/zhao_vram_arbiter_blkalign_mutant.sv from production.

WHAT THE MUTANT IS FOR
----------------------
Owner ruling R243 / D-SDRAM-A made `sim/models/zhao_sdram_model.sv` wrap like a
JEDEC BL8 SEQUENTIAL device (col[10:3] held, col[2:0] advancing) and then made
`zhao_vram_arbiter.burst_words` clamp every burst to the aligned eight-column
block, so no burst the arbiter offers can reach that wrap.

The pair is correct, and being correct is what makes the wrap UNREACHABLE WITH
LEGAL STIMULUS. CLAUDE.md: a guard you cannot reach with legal stimulus needs a
COMMITTED MUTANT, because otherwise "the model wraps now" is an argument about
a line nothing has ever been seen to exercise, and a repair nobody can watch
fail is indistinguishable from a repair to nothing.

THE ONE SUBSTANTIVE CHANGE is `burst_words`, reverted to the ROW clamp it
carried before R243 -- `min(rem, 8, 2048 - col)`, which aligns to the 2048-word
row and to nothing finer. Everything else in the file is production, character
for character, which is what `tools/budget/mutant_copy_drift.py` checks.

WHY A GENERATOR AND NOT A HAND COPY. mutant_copy_drift found thirteen combiner
copies whose "one substantive line" had become a hundred and forty while every
control stayed green -- the mutations were intact and the BODY around them was
stale. A refresh has to be a command rather than an act of transcription.

USAGE
    python tools/rtl/gen_vram_arbiter_blkalign_mutant.py          # write
    python tools/rtl/gen_vram_arbiter_blkalign_mutant.py --check  # RC 1 if stale

The file is RENAMED (not just the module) so that no production source list can
elaborate it by mistake; the module name inside stays `zhao_vram_arbiter`
because the mutant is compiled INSTEAD of production, in its own CMake target.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SRC = REPO / "fpga" / "rtl" / "memory" / "zhao_vram_arbiter.sv"
DST = REPO / "tests" / "mutants" / "zhao_vram_arbiter_blkalign_mutant.sv"

# The production text this replaces. If it stops matching, production's
# `burst_words` changed shape and the mutant must be re-thought, not re-cut --
# so the script FAILS rather than emitting something that looks plausible.
PROD = """  function automatic logic [3:0] burst_words(input logic [5:0] rem,
                                              input logic [2:0] col_lo);
    logic [3:0] blk_tail;
    blk_tail = 4'd8 - {1'b0, col_lo};
    if (rem >= {2'b0, blk_tail}) burst_words = blk_tail;
    else                         burst_words = rem[3:0];
  endfunction
"""

MUT = """  // ##### THE MUTATION -- THE ONLY SUBSTANTIVE DIFFERENCE IN THIS FILE #####
  // `burst_words` reverted to the pre-R243 ROW clamp: min(rem, 8, row tail).
  // It aligns to the 2048-word row and to nothing finer, so a burst started at
  // a column that is not a multiple of 8 runs off the end of its aligned
  // eight-column block -- and the (now truthful) behavioural model wraps it
  // back to the block's own first column, writing or reading the wrong words.
  //
  // The signature keeps production's 11-bit column because the row clamp needs
  // all of it; production narrowed the argument to `col_lo` precisely because
  // the block clamp does not. The call site is patched to match, below.
  function automatic logic [3:0] burst_words(input logic [5:0] rem,
                                              input logic [10:0] col);
    logic [11:0] row_tail;
    row_tail = 12'd2048 - {1'b0, col};
    if (row_tail >= {6'b0, rem}) begin
      if (rem >= 6'd8) burst_words = 4'd8;
      else             burst_words = rem[3:0];
    end else begin
      if (row_tail >= 12'd8) burst_words = 4'd8;
      else                   burst_words = row_tail[3:0];
    end
  endfunction
"""

PROD_CALL = "      bw_all[k] = burst_words(pend_words[k], pend_addr[k][3:1]);"
MUT_CALL = "      bw_all[k] = burst_words(pend_words[k], pend_addr[k][11:1]);"

HEADER = """// zhao_vram_arbiter_blkalign_mutant.sv -- A POSITIVE CONTROL, NOT A DESIGN.
//
// GENERATED by tools/rtl/gen_vram_arbiter_blkalign_mutant.py from production,
// so a refresh is a command rather than an act of transcription. RENAMED so no
// production source list can elaborate it; the MODULE keeps production's name
// because this file is compiled INSTEAD of production in its own target.
//
// DRIVEN-BY: tests/memory/mem_blkalign_mut.cpp, built twice --
//   mem_blkalign_mut_fires   against THIS file, INVERTED POLARITY: it passes
//                            when a misaligned 64-byte write LANDS WRONG.
//   mem_blkalign_mut_silent  against UNMUTATED production, DIRECT POLARITY:
//                            memory must be intact.
// Both halves are required. Without the silent run a seam that never engaged
// would compile two things that behave identically and both would agree.
//
// WHY IT EXISTS (owner ruling R243 / D-SDRAM-A). The behavioural SDRAM model
// now wraps like the part -- a JEDEC BL8 SEQUENTIAL burst holds col[10:3] and
// advances col[2:0] -- and production's `burst_words` clamps to the aligned
// eight-column block, so NO burst the arbiter offers can reach that wrap. The
// repair is correct and that is precisely what makes the wrap unreachable with
// legal stimulus, which is the state CLAUDE.md says owes a committed mutant.
//
// WHAT WAS CHANGED: `burst_words` and its one call site, back to the row
// clamp. See the block comment at the mutation. Everything else in this file
// is production, character for character -- tools/budget/mutant_copy_drift.py
// will say when that stops being true.
// ===========================================================================
"""


def build() -> str:
    text = SRC.read_text(encoding="utf-8")
    if PROD not in text:
        sys.exit("gen_vram_arbiter_blkalign_mutant: production `burst_words` no longer "
                 "matches the text this mutant reverts. Re-think the mutant; do not re-cut it.")
    if PROD_CALL not in text:
        sys.exit("gen_vram_arbiter_blkalign_mutant: production call site no longer matches.")
    text = text.replace(PROD, MUT, 1)
    text = text.replace(PROD_CALL, MUT_CALL, 1)
    return HEADER + text


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the committed copy differs from a fresh cut")
    args = ap.parse_args()
    want = build()
    if args.check:
        have = DST.read_text(encoding="utf-8") if DST.exists() else ""
        if have != want:
            print(f"STALE: {DST.relative_to(REPO)} differs from a fresh cut of "
                  f"{SRC.relative_to(REPO)}")
            return 1
        print(f"current: {DST.relative_to(REPO)}")
        return 0
    DST.write_text(want, encoding="utf-8", newline="\r\n")
    print(f"wrote {DST.relative_to(REPO)} ({len(want.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
