"""PARAMARENA: regenerate GEOM.PARAMBUF's arena positive control from current
production.  A COPY with a rename and ONE substantive change.

`zhao_geom_paramarena`'s `addr_view_bad_o` differences the view the HELD
address lies in against the view the LEASE names.  Its two operands load on
different enables -- `m_addr_q` when the engine takes an op, `view_q` at the
frame seal -- so it is not the lockstep-blind kind of check CLAUDE.md's
metadata-bank law is about.  But while the DRAIN PRECONDITION is correct the
view cannot move while anything is in flight, so the two are equal by
construction and NO LEGAL STIMULUS CAN MOVE THE COUNTER.  That leaves "it can
fire" as an argument forever.

So the drain precondition is removed HERE, in a committed file, renamed so no
production source list can elaborate it, and driven by
`tests/geometry/geom_paramarena_drainmut.cpp` with INVERTED POLARITY.

Run from the worktree root, or with the root as argv[1].
"""
import pathlib
import sys

ROOT = (pathlib.Path(sys.argv[1]) if len(sys.argv) > 1
        else pathlib.Path(__file__).resolve().parents[2])
PROD = ROOT / "fpga/rtl/geometry/zhao_geom_paramarena.sv"
src = PROD.read_text(encoding="utf-8")

OLD = """  wire drained_c   = (wr_words_q == '0) && (mstate_q == M_IDLE);
  wire seal_ok_c   = drained_c && !reader_busy_i && !pub_pending_q;
"""

NEW = """  // ============ THE MUTATION, AND IT IS THIS ONE TERM ============
  // Production writes
  //     wire seal_ok_c = drained_c && !reader_busy_i && !pub_pending_q;
  // and `drained_c` is the whole of item 4's "a chunk must not be reused while
  // a previous reader or outstanding transaction still owns it".  This copy
  // drops it, so a seal takes effect WITH WRITES STILL OUTSTANDING: `view_q`
  // flips while `m_addr_q` still holds an address allocated under the previous
  // view, and `pb_wr_view` -- a GLOBAL selector the guard is combinational
  // over -- moves under a request the guard has not yet accepted.  That is
  // precisely the hazard `zhao_mem_guard`'s header says MEM.GUARD cannot close
  // on its own and that this block closes at the producer.
  //
  // `drained_c` itself is KEPT, so the copy differs from production in one
  // expression rather than in a deleted declaration and a refresh merge has one
  // hunk to carry forward.  It has no reader here, hence the pragma.
  /* verilator lint_off UNUSEDSIGNAL */
  wire drained_c   = (wr_words_q == '0) && (mstate_q == M_IDLE);
  /* verilator lint_on UNUSEDSIGNAL */
  wire seal_ok_c   = !reader_busy_i && !pub_pending_q;
"""

HEAD = """// zhao_geom_paramarena_drain_mutant.sv -- A POSITIVE CONTROL, NOT A DESIGN.
//
// DRIVEN-BY: tests/geometry/geom_paramarena_drainmut.cpp, INVERTED POLARITY:
//            the `geom_paramarena_drainmut_fires` ctest PASSES when
//            `addr_view_bad_o` FIRES against this copy, and the
//            `geom_paramarena_drainmut_silent` ctest beside it builds the SAME
//            driver against UNMUTATED production and requires SILENCE.  That
//            pair is the negative control CLAUDE.md asks for: without it a seam
//            that never engaged would compile production twice and both runs
//            would agree, saying nothing.
//
// WHY THE COUNTER NEEDS ONE.  `addr_view_bad_o` differences the view the HELD
// request address lies in against the view the LEASE names.  Its two operands
// move on DIFFERENT enables -- `m_addr_q` when the engine takes an op, `view_q`
// at the frame seal -- so the comparison is structurally able to see a request
// that outlived its selector, which is the whole reason it was written down.
// But production's own drain precondition makes that state UNREACHABLE: a seal
// is held pending while `wr_words_q != 0` or the engine is not idle, so the two
// are equal by construction and NO LEGAL STIMULUS CAN MOVE THE COUNTER.  A
// counter asserted zero that has never been seen to move is a claim, not an
// instrument.
//
// WHAT ONE TERM WAS CHANGED: `drained_c` is dropped from `seal_ok_c`, so the
// view flips with writes still outstanding.  Everything else in this file is
// production, character for character.
//
// GENERATED by tools/rtl/gen_paramarena_mutants.py from production, so a
// refresh is a command rather than an act of transcription.
//
// REGENERATE IT if zhao_geom_paramarena.sv changes shape: it is a COPY, and
// tools/budget/mutant_copy_drift.py will say when it is stale -- a copy of an
// old version is a positive control for a block that no longer exists.
// RENAMED so no production source list can elaborate it.
// ===========================================================================
"""

if OLD not in src:
    raise SystemExit("PRODUCTION TEXT NOT FOUND -- the copy cannot be generated"
                     " from a version it does not match.")
body = src.replace(OLD, NEW, 1)

MOD_OLD = "module zhao_geom_paramarena\n"
MOD_NEW = "module zhao_geom_paramarena_drain_mutant\n"
if MOD_OLD not in body:
    raise SystemExit("module declaration not found")
body = body.replace(MOD_OLD, MOD_NEW, 1)

END_OLD = "endmodule : zhao_geom_paramarena\n"
END_NEW = "endmodule : zhao_geom_paramarena_drain_mutant\n"
if END_OLD not in body:
    raise SystemExit("endmodule label not found")
body = body.replace(END_OLD, END_NEW, 1)

if MOD_NEW not in body or END_NEW not in body:
    raise SystemExit("module rename failed")

out = ROOT / "tests/mutants/zhao_geom_paramarena_drain_mutant.sv"
out.write_text(HEAD + body, encoding="utf-8", newline="\n")
print("wrote", out)
