"""PARAMARENA: regenerate the FOUR MEM.GUARD positive controls from current
production.  Each is a COPY with a rename and ONE substantive change.
Run from the worktree root."""
import pathlib
import sys

ROOT = (pathlib.Path(sys.argv[1]) if len(sys.argv) > 1
        else pathlib.Path(__file__).resolve().parents[2])
PROD = ROOT / "fpga/rtl/memory/zhao_mem_guard.sv"
src = PROD.read_text(encoding="utf-8")

# ---------------------------------------------------------------- resbound --
RES_OLD = """  assign res_in_pool = res_valid
                     && (res_base  >= ZHAO_RENDER_ASSET_BASE)
                     && (res_end33 <= {1'b0, ZHAO_RENDER_ASSET_BASE + ZHAO_RENDER_ASSET_SPAN});
"""
RES_NEW = """  // ======================= THE MUTATION, AND IT IS THIS ONE LINE ===========
  // Production requires the configured region to lie WHOLLY INSIDE
  // RENDER.ASSET_POOL. This copy trusts it: any configured region opens.
  assign res_in_pool = res_valid;
  /* verilator lint_off UNUSEDSIGNAL */
  wire mut_res_end_unused = |res_end33;
  /* verilator lint_on UNUSEDSIGNAL */
"""

RES_HEAD = """// zhao_mem_guard_resbound_mutant.sv -- A POSITIVE CONTROL, NOT A DESIGN.
//
// DRIVEN-BY: tests/formal/mem_guard_resbound_mutant.sby -- INVERTED POLARITY:
//            that proof is declared `expect fail` and PASSES when the
//            no-escape theorem FAILS against this copy.
//
// WHAT ONE LINE WAS CHANGED. Owner ruling R32 (2026-09-19) gave TERRAIN_BUILD
// a WRITE arm into RENDER.ASSET_POOL, bounded to the host-configured published-
// resource region, and production refuses a region that does not lie wholly
// inside the pool. This copy drops that containment term, so a region
// configured over a framebuffer slot opens a write into it. If the proof still
// passed against this copy, `a1_map` / `a1_region` / `a1_resource_bounded`
// could not see the bound they claim to prove -- a detector that has not been
// seen to fire is a claim, not an instrument.
//
// REFRESHED 2026-09-22 (DEVSDRAM) from production at that date, because
// `zhao_mem_guard.sv` gained ruling R242's TERRAIN.DEVSTORE window and this
// copy had ALSO been stale since POST.ECHO landed -- a copy of an old version
// is a positive control for a block that no longer exists. Regenerated by
// tools/rtl/gen_mem_guard_mutants.py so the next refresh is a command and not
// an act of transcription.
//
// REGENERATE IT if zhao_mem_guard.sv changes shape: it is a COPY, and
// tools/budget/mutant_copy_drift.py will say when it is stale. RENAMED so no
// production source list can elaborate it.
// ===========================================================================
"""

# ---------------------------------------------------------------- devbound --
DEV_OLD = """  assign devstore_wr_ok = req.write
                        && (addr32 >= ZHAO_TERRAIN_DEVSTORE_BASE)
                        && (end32  <= ZHAO_TERRAIN_DEVSTORE_BASE
                                      + ZHAO_TERRAIN_DEVSTORE_SPAN);
  assign devstore_rd_ok = !req.write
                        && (addr32 >= ZHAO_TERRAIN_DEVSTORE_BASE)
                        && (end32  <= ZHAO_TERRAIN_DEVSTORE_BASE
                                      + ZHAO_TERRAIN_DEVSTORE_SPAN);
"""
DEV_NEW = """  // ============== THE MUTATION, AND IT IS THE UPPER BOUND ==================
  // Production requires `end32 <= BASE + SPAN`. This copy keeps only the lower
  // bound, so EVERY address at or above 0x0586_0000 -- the rest of bank 2, all
  // of POST.ECHO's capture, all of bank 3, GEOM.PARAMBUF and RENDER.ASSET_POOL
  // -- is admitted for TERRAIN_BUILD in both directions. It is written twice
  // because production writes the bound twice (two arms, two theorems); it is
  // ONE substantive change.
  assign devstore_wr_ok = req.write
                        && (addr32 >= ZHAO_TERRAIN_DEVSTORE_BASE);
  assign devstore_rd_ok = !req.write
                        && (addr32 >= ZHAO_TERRAIN_DEVSTORE_BASE);
"""

DEV_HEAD = """// zhao_mem_guard_devbound_mutant.sv -- A POSITIVE CONTROL, NOT A DESIGN.
//
// DRIVEN-BY: tests/formal/mem_guard_devbound_mutant.sby -- INVERTED POLARITY:
//            that proof is declared `expect fail` and PASSES when the
//            no-escape theorem FAILS against this copy.
//
// WHAT WAS CHANGED, AND WHY THIS ONE. Owner ruling R242 (2026-09-22) moved the
// terrain deviation and history store out of 185 M10K and into SDRAM, which
// needed a new guarded region. R242 requires the guarded-region act to follow
// the 2026-09-22 item 4 pattern exactly: extend `mem_guard_no_escape`, never
// bypass it, AND include a deliberate fault that makes the proof FAIL.
//
// This copy removes TERRAIN.DEVSTORE's UPPER bound. The lower bound is kept,
// so the window stops being a window: every address from 0x0586_0000 upwards
// becomes legal for client 6 in both directions -- POST.ECHO's capture, bank
// 3's PARAMBUF, RENDER.ASSET_POOL, and everything past the top of the map.
// If the proof still passed against this copy, the three `a1_devstore_*`
// theorems and the widened `a1_region` arm would all be holding on a bound
// nothing checks. A detector that has not been seen to fire is a claim, not an
// instrument.
//
// WHICH THEOREM ACTUALLY FIRES, MEASURED RATHER THAN PREDICTED, AND IT HAS
// MOVED TWICE. The first draft of this header said `a1_map`. On 2026-09-22
// (DEVSDRAM) the measured answer was `a1_resource_bounded`: the shortest
// counterexample was a TERRAIN_BUILD write landing inside RENDER.ASSET_POOL,
// legal to the mutated arm and outside any published-resource region. On
// 2026-09-22 (PARAMARENA), after item 4 added fourteen `a1_pb_*` theorems to
// the same harness, it is `a1_region`.
//
// NOTHING ABOUT THE FAULT CHANGED. bmc reports the FIRST assertion it
// violates and stops, so which name appears is a fact about the solver's
// search order and the set of theorems present, not about the mutation. That
// is worth writing down rather than quietly re-editing, because "the proof
// fails at X" reads like a property of the defect and is not one: the
// stable claim is that the proof FAILS, and the theorem name is evidence
// about the run. A header that names a theorem the run no longer produces is
// exactly the confident one-line summary this repository's rules say to
// check.
//
// WHY THE UPPER BOUND AND NOT THE CLIENT TERM: removing the client term would
// be caught by `a1_client` and `a1_devstore_owner`, which are cheap theorems
// about an enum. The bound is the expensive one -- it is arithmetic, it is
// where the blit's wrap defect lived, and it is the half a reviewer skims.
//
// GENERATED by tools/rtl/gen_mem_guard_mutants.py from production, so a
// refresh is a command rather than an act of transcription.
//
// REGENERATE IT if zhao_mem_guard.sv changes shape: it is a COPY, and
// tools/budget/mutant_copy_drift.py will say when it is stale. RENAMED so no
// production source list can elaborate it.
// ===========================================================================
"""


# ----------------------------------------------------------------- pbview --
PBVIEW_OLD = """  assign pb_wr_ok  = req.write && pb_lease_valid
                   && (pb_wr_view ? pb_in_view1 : pb_in_view0);
"""
PBVIEW_NEW = """  // ============ THE MUTATION, AND IT IS THE VIEW SELECTION =================
  // Production admits a WRITE only into the view the lease NAMES. This copy
  // keeps the containment and drops the naming: either view opens, so the
  // producer may write the view the walker is currently reading. That is the
  // exact fault the two-view split exists to prevent, and it is invisible to
  // any test that only ever builds one view.
  /* verilator lint_off UNUSEDSIGNAL */
  wire mut_pb_wr_view_unused = pb_wr_view;
  /* verilator lint_on UNUSEDSIGNAL */
  assign pb_wr_ok  = req.write && pb_lease_valid
                   && (pb_in_view0 || pb_in_view1);
"""

PBVIEW_HEAD = """// zhao_mem_guard_pbview_mutant.sv -- A POSITIVE CONTROL, NOT A DESIGN.
//
// DRIVEN-BY: tests/formal/mem_guard_pbview_mutant.sby -- INVERTED POLARITY:
//            that proof is declared `expect fail` and PASSES when the
//            no-escape theorem FAILS against this copy.
//
// WHAT WAS CHANGED, AND WHY THIS ONE. The owner's completion ruling of
// 2026-09-22, item 4, opened GEOM.PARAMBUF to ENGINE1 and required a
// deliberate fault "that defeats a required protection and makes the
// test/proof fail". The required protection here is CORRECT VIEW SELECTION:
// the two 4 MiB views are disjoint "for the same reason the two FB slots are"
// because one is being BUILT while the other is being READ.
//
// This copy keeps the containment test and removes the naming -- `pb_wr_view`
// becomes an unused input and a write into EITHER view passes. Every address
// remains inside the ruled map, so `a1_map` is untroubled; what fails is
// `a1_pb_wr_view0` / `a1_pb_wr_view1` / `a1_region`, which is the point. A
// mutation that broke the map would have proved only that the map is checked.
//
// MEASURED 2026-09-22: the proof fails at `a1_pb_wr_view0`. Recorded because
// bmc reports the FIRST assertion it violates and stops, so this name is
// evidence about the run and the set of theorems present -- the stable claim
// is that the proof FAILS.
//
// WHY NOT THE LEASE TERM: removing `pb_lease_valid` would be caught by
// `a1_pb_lease`, a cheap theorem about one bit. The SELECTION is the
// expensive one -- it is the only non-constant bound this window has, it is
// the half a reviewer reads as "it is contained, so it is fine", and a
// workload that only ever fills view 0 can never tell the two apart.
//
// GENERATED by tools/rtl/gen_mem_guard_mutants.py from production, so a
// refresh is a command rather than an act of transcription.
//
// REGENERATE IT if zhao_mem_guard.sv changes shape: it is a COPY, and
// tools/budget/mutant_copy_drift.py will say when it is stale. RENAMED so no
// production source list can elaborate it.
// ===========================================================================
"""

# ---------------------------------------------------------------- pbunion --
PBUNION_OLD = """  assign pb_in_view0   = (addr32 >= ZHAO_PARAMBUF_VIEW0_BASE)
                       && (end32  <= ZHAO_PARAMBUF_VIEW0_BASE
                                     + ZHAO_PARAMBUF_VIEW_SPAN);
  assign pb_in_view1   = (addr32 >= ZHAO_PARAMBUF_VIEW1_BASE)
                       && (end32  <= ZHAO_PARAMBUF_VIEW1_BASE
                                     + ZHAO_PARAMBUF_VIEW_SPAN);
  assign pb_in_scratch = (addr32 >= ZHAO_PARAMBUF_SCRATCH_BASE)
                       && (end32  <= ZHAO_PARAMBUF_SCRATCH_BASE
                                     + ZHAO_PARAMBUF_SCRATCH_SPAN);
"""
PBUNION_NEW = """  // ========== THE MUTATION: THREE CONTAINMENT TESTS BECOME THEIR UNION ======
  // Production tests each region separately, so a request must lie wholly
  // inside ONE of them. This copy tests the UNION [VIEW0_BASE, SCRATCH_END)
  // once and answers every region with it -- which is item 4's forbidden
  // reading, "a request crossing a per-view or scratch boundary is allowed
  // because both endpoints lie somewhere in the union of permitted ranges",
  // written as RTL. It is identical to production for every request that lies
  // inside a single region, and it ADDITIONALLY admits every request that
  // spans a seam.
  wire pb_in_union = (addr32 >= ZHAO_PARAMBUF_VIEW0_BASE)
                   && (end32  <= ZHAO_PARAMBUF_SCRATCH_BASE
                                 + ZHAO_PARAMBUF_SCRATCH_SPAN);
  assign pb_in_view0   = pb_in_union;
  assign pb_in_view1   = pb_in_union;
  assign pb_in_scratch = pb_in_union;
"""

PBUNION_HEAD = """// zhao_mem_guard_pbunion_mutant.sv -- A POSITIVE CONTROL, NOT A DESIGN.
//
// DRIVEN-BY: tests/formal/mem_guard_pbunion_mutant.sby -- INVERTED POLARITY:
//            that proof is declared `expect fail` and PASSES when the
//            no-escape theorem FAILS against this copy.
//
// WHAT WAS CHANGED. The owner's completion ruling of 2026-09-22, item 4, says
// in as many words: "A request crossing a per-view or scratch boundary is not
// allowed merely because both endpoints lie somewhere in the union of
// permitted ranges." This copy implements the sentence it forbids. The three
// separate containment tests become ONE test of [0x0600_0000, 0x06A0_0000),
// and all three region signals answer with it.
//
// IT IS THE SUBTLEST OF THE FOUR MEM.GUARD MUTANTS AND THAT IS WHY IT EXISTS.
// Every request that lies inside a single region behaves IDENTICALLY to
// production, so every ordinary workload, every directed test that stays
// inside a view, and every cover in the proof still passes. Only a burst that
// SPANS A SEAM tells them apart -- and a seam-spanning write is the producer
// writing into the view the walker is reading, or off the top of the arena
// into the shared scratch. A design defect whose only symptom is a corner is
// the one a formal proof is for, and if `mem_guard_no_escape` could not see
// this one it would not be evidence about the boundary clause at all.
//
// WHICH THEOREM FIRES, MEASURED RATHER THAN PREDICTED. This header's draft
// expected `a1_map` -- reasoning that a seam-spanning burst is inside none of
// the harness's three region wires and so escapes the map. IT IS NOT THE ONE
// THAT DOES. Measured 2026-09-22: `a1_pb_wr_view0`. The shortest
// counterexample the engine finds is not a seam-spanning burst at all but a
// WRITE wholly inside view 0 while the lease names view 1 -- because the
// union answers `pb_in_view1` TRUE for a view-0 address, so the mutated write
// arm stops distinguishing the views as a side effect of stopping
// distinguishing the regions. The fault is caught, the reach is shorter than
// predicted, and the prediction is left here rather than tidied away.
//
// GENERATED by tools/rtl/gen_mem_guard_mutants.py from production, so a
// refresh is a command rather than an act of transcription.
//
// REGENERATE IT if zhao_mem_guard.sv changes shape: it is a COPY, and
// tools/budget/mutant_copy_drift.py will say when it is stale. RENAMED so no
// production source list can elaborate it.
// ===========================================================================
"""


def emit(path, head, module, old, new):
    if old not in src:
        raise SystemExit("PRODUCTION TEXT NOT FOUND for %s -- the copy cannot be"
                         " generated from a version it does not match." % path)
    body = src.replace(old, new, 1)
    body = body.replace("module zhao_mem_guard\n", "module %s\n" % module, 1)
    if "module %s\n" % module not in body:
        raise SystemExit("module rename failed for %s" % path)
    (ROOT / path).write_text(head + body, encoding="utf-8", newline="\n")
    print("wrote", path)


emit("tests/mutants/zhao_mem_guard_resbound_mutant.sv", RES_HEAD,
     "zhao_mem_guard_resbound_mutant", RES_OLD, RES_NEW)
emit("tests/mutants/zhao_mem_guard_devbound_mutant.sv", DEV_HEAD,
     "zhao_mem_guard_devbound_mutant", DEV_OLD, DEV_NEW)
emit("tests/mutants/zhao_mem_guard_pbview_mutant.sv", PBVIEW_HEAD,
     "zhao_mem_guard_pbview_mutant", PBVIEW_OLD, PBVIEW_NEW)
emit("tests/mutants/zhao_mem_guard_pbunion_mutant.sv", PBUNION_HEAD,
     "zhao_mem_guard_pbunion_mutant", PBUNION_OLD, PBUNION_NEW)
