"""DEVSDRAM: regenerate TERRAIN.DEVSTORE's positive control from current
production.  A COPY with a rename and ONE substantive change.
Run from the worktree root, or with the root as argv[1]."""
import pathlib
import sys

ROOT = (pathlib.Path(sys.argv[1]) if len(sys.argv) > 1
        else pathlib.Path(__file__).resolve().parents[2])
PROD = ROOT / "fpga/rtl/terrain/zhao_terrain_devstore.sv"
src = PROD.read_text(encoding="utf-8")

OLD = """          m_addr_q     <= mo_rd_c ? rq_a_c : wq_a_c;
"""
NEW = """          // ============ THE MUTATION, AND IT IS THIS ONE LINE ============
          // Production reloads the held address for EVERY op.  This copy
          // loads it once and then keeps it forever, which is the
          // register-an-address-unconditionally-and-then-not shape of the
          // metadata-swap defect CLAUDE.md records: the engine goes on
          // serving one address while the read FSM walks four bursts and a
          // history row.  `slot_addr_bad_o` is the only thing in the block
          // that can see it -- every handshake still balances, every burst is
          // still eight beats, and the guard still says the address is legal,
          // because it IS legal, just not this patch's.
          if (m_addr_q == 27'd0) m_addr_q <= mo_rd_c ? rq_a_c : wq_a_c;
"""

HEAD = """// zhao_terrain_devstore_addrlatch_mutant.sv -- A POSITIVE CONTROL, NOT A
// DESIGN.
//
// DRIVEN-BY: tests/terrain/terrain_devstore_addrmut.cpp, INVERTED POLARITY:
//            the `terrain_devstore_addrmut_fires` ctest PASSES when
//            `slot_addr_bad_o` FIRES against this copy, and the
//            `terrain_devstore_addrmut_silent` ctest beside it builds the
//            SAME driver against UNMUTATED production and requires SILENCE.
//            That pair is the negative control CLAUDE.md asks for: without it
//            a macro seam that never engaged would compile production twice
//            and both runs would agree, saying nothing.
//
// WHY THE COUNTER NEEDS ONE.  `slot_addr_bad_o` differences the address the
// memory engine is holding against the address the read FSM requires for the
// patch and burst it is serving.  While the block is correct those two
// quantities are equal by construction, so NO LEGAL STIMULUS CAN MOVE IT --
// which leaves "it can fire" as an argument forever, and a counter asserted
// zero that has never been seen to move is a claim, not an instrument.
//
// WHAT ONE LINE WAS CHANGED: the engine loads `m_addr_q` only while it is
// zero, so the first address it ever takes is the address it serves for the
// rest of time.
//
// GENERATED by tools/rtl/gen_devstore_mutants.py from production, so a refresh
// is a command rather than an act of transcription.
//
// REGENERATE IT if zhao_terrain_devstore.sv changes shape: it is a COPY, and
// tools/budget/mutant_copy_drift.py will say when it is stale.  RENAMED so no
// production source list can elaborate it.
// ===========================================================================
"""

if OLD not in src:
    raise SystemExit("PRODUCTION TEXT NOT FOUND -- the copy cannot be generated"
                     " from a version it does not match.")
body = src.replace(OLD, NEW, 1)
body = body.replace("module zhao_terrain_devstore\n",
                    "module zhao_terrain_devstore_addrlatch_mutant\n", 1)
if "module zhao_terrain_devstore_addrlatch_mutant\n" not in body:
    raise SystemExit("module rename failed")
out = ROOT / "tests/mutants/zhao_terrain_devstore_addrlatch_mutant.sv"
out.write_text(HEAD + body, encoding="utf-8", newline="\n")
print("wrote", out)
