"""DEVSDRAM: regenerate the two MEM.GUARD positive controls from current
production.  Each is a COPY with a rename and ONE substantive change.
Run from the worktree root."""
import pathlib
import sys

ROOT = (pathlib.Path(sys.argv[1]) if len(sys.argv) > 1
        else pathlib.Path(__file__).resolve().parents[2])
PROD = ROOT / "fpga/rtl/memory/zhao_mem_guard.sv"
src = PROD.read_text(encoding="utf-8")

# ---------------------------------------------------------------- resbound --
RES_OLD = """  assign res_in_pool = res_valid
                     && (res_base  >= ZHAO_RENDER_ASSET_BASE)
                     && (res_end33 <= {1'b0, ZHAO_RENDER_ASSET_BASE + ZHAO_RENDER_ASSET_SPAN});
"""
RES_NEW = """  // ======================= THE MUTATION, AND IT IS THIS ONE LINE ===========
  // Production requires the configured region to lie WHOLLY INSIDE
  // RENDER.ASSET_POOL. This copy trusts it: any configured region opens.
  assign res_in_pool = res_valid;
  /* verilator lint_off UNUSEDSIGNAL */
  wire mut_res_end_unused = |res_end33;
  /* verilator lint_on UNUSEDSIGNAL */
"""

RES_HEAD = """// zhao_mem_guard_resbound_mutant.sv -- A POSITIVE CONTROL, NOT A DESIGN.
//
// DRIVEN-BY: tests/formal/mem_guard_resbound_mutant.sby -- INVERTED POLARITY:
//            that proof is declared `expect fail` and PASSES when the
//            no-escape theorem FAILS against this copy.
//
// WHAT ONE LINE WAS CHANGED. Owner ruling R32 (2026-09-19) gave TERRAIN_BUILD
// a WRITE arm into RENDER.ASSET_POOL, bounded to the host-configured published-
// resource region, and production refuses a region that does not lie wholly
// inside the pool. This copy drops that containment term, so a region
// configured over a framebuffer slot opens a write into it. If the proof still
// passed against this copy, `a1_map` / `a1_region` / `a1_resource_bounded`
// could not see the bound they claim to prove -- a detector that has not been
// seen to fire is a claim, not an instrument.
//
// REFRESHED 2026-09-22 (DEVSDRAM) from production at that date, because
// `zhao_mem_guard.sv` gained ruling R242's TERRAIN.DEVSTORE window and this
// copy had ALSO been stale since POST.ECHO landed -- a copy of an old version
// is a positive control for a block that no longer exists. Regenerated by
// tools/rtl/gen_mem_guard_mutants.py so the next refresh is a command and not
// an act of transcription.
//
// REGENERATE IT if zhao_mem_guard.sv changes shape: it is a COPY, and
// tools/budget/mutant_copy_drift.py will say when it is stale. RENAMED so no
// production source list can elaborate it.
// ===========================================================================
"""

# ---------------------------------------------------------------- devbound --
DEV_OLD = """  assign devstore_wr_ok = req.write
                        && (addr32 >= ZHAO_TERRAIN_DEVSTORE_BASE)
                        && (end32  <= ZHAO_TERRAIN_DEVSTORE_BASE
                                      + ZHAO_TERRAIN_DEVSTORE_SPAN);
  assign devstore_rd_ok = !req.write
                        && (addr32 >= ZHAO_TERRAIN_DEVSTORE_BASE)
                        && (end32  <= ZHAO_TERRAIN_DEVSTORE_BASE
                                      + ZHAO_TERRAIN_DEVSTORE_SPAN);
"""
DEV_NEW = """  // ============== THE MUTATION, AND IT IS THE UPPER BOUND ==================
  // Production requires `end32 <= BASE + SPAN`. This copy keeps only the lower
  // bound, so EVERY address at or above 0x0586_0000 -- the rest of bank 2, all
  // of POST.ECHO's capture, all of bank 3, GEOM.PARAMBUF and RENDER.ASSET_POOL
  // -- is admitted for TERRAIN_BUILD in both directions. It is written twice
  // because production writes the bound twice (two arms, two theorems); it is
  // ONE substantive change.
  assign devstore_wr_ok = req.write
                        && (addr32 >= ZHAO_TERRAIN_DEVSTORE_BASE);
  assign devstore_rd_ok = !req.write
                        && (addr32 >= ZHAO_TERRAIN_DEVSTORE_BASE);
"""

DEV_HEAD = """// zhao_mem_guard_devbound_mutant.sv -- A POSITIVE CONTROL, NOT A DESIGN.
//
// DRIVEN-BY: tests/formal/mem_guard_devbound_mutant.sby -- INVERTED POLARITY:
//            that proof is declared `expect fail` and PASSES when the
//            no-escape theorem FAILS against this copy.
//
// WHAT WAS CHANGED, AND WHY THIS ONE. Owner ruling R242 (2026-09-22) moved the
// terrain deviation and history store out of 185 M10K and into SDRAM, which
// needed a new guarded region. R242 requires the guarded-region act to follow
// the 2026-09-22 item 4 pattern exactly: extend `mem_guard_no_escape`, never
// bypass it, AND include a deliberate fault that makes the proof FAIL.
//
// This copy removes TERRAIN.DEVSTORE's UPPER bound. The lower bound is kept,
// so the window stops being a window: every address from 0x0586_0000 upwards
// becomes legal for client 6 in both directions -- POST.ECHO's capture, bank
// 3's PARAMBUF, RENDER.ASSET_POOL, and everything past the top of the map.
// If the proof still passed against this copy, the three `a1_devstore_*`
// theorems and the widened `a1_region` arm would all be holding on a bound
// nothing checks. A detector that has not been seen to fire is a claim, not an
// instrument.
//
// WHICH THEOREM ACTUALLY FIRES, MEASURED RATHER THAN PREDICTED. The first
// draft of this header said "`a1_map` is the theorem that must catch it".
// IT IS NOT THE ONE THAT DOES. Run on 2026-09-22 the proof fails at
// `a1_resource_bounded`, because the shortest counterexample the engine finds
// is a TERRAIN_BUILD write that lands inside RENDER.ASSET_POOL -- legal to the
// mutated arm, and a write into the asset pool outside any published-resource
// region. `a1_map` catches the escape PAST THE TOP OF THE MAP, which is a
// longer reach for the solver; bmc reports the first assertion it violates and
// stops. The fault is caught either way, and the difference is recorded
// because a header that names the wrong theorem is the kind of confident
// one-line summary this repository's own rules say to check.
//
// WHY THE UPPER BOUND AND NOT THE CLIENT TERM: removing the client term would
// be caught by `a1_client` and `a1_devstore_owner`, which are cheap theorems
// about an enum. The bound is the expensive one -- it is arithmetic, it is
// where the blit's wrap defect lived, and it is the half a reviewer skims.
//
// GENERATED by tools/rtl/gen_mem_guard_mutants.py from production, so a
// refresh is a command rather than an act of transcription.
//
// REGENERATE IT if zhao_mem_guard.sv changes shape: it is a COPY, and
// tools/budget/mutant_copy_drift.py will say when it is stale. RENAMED so no
// production source list can elaborate it.
// ===========================================================================
"""


def emit(path, head, module, old, new):
    if old not in src:
        raise SystemExit("PRODUCTION TEXT NOT FOUND for %s -- the copy cannot be"
                         " generated from a version it does not match." % path)
    body = src.replace(old, new, 1)
    body = body.replace("module zhao_mem_guard\n", "module %s\n" % module, 1)
    if "module %s\n" % module not in body:
        raise SystemExit("module rename failed for %s" % path)
    (ROOT / path).write_text(head + body, encoding="utf-8", newline="\n")
    print("wrote", path)


emit("tests/mutants/zhao_mem_guard_resbound_mutant.sv", RES_HEAD,
     "zhao_mem_guard_resbound_mutant", RES_OLD, RES_NEW)
emit("tests/mutants/zhao_mem_guard_devbound_mutant.sv", DEV_HEAD,
     "zhao_mem_guard_devbound_mutant", DEV_OLD, DEV_NEW)
