// GENERATED by tests/prod/smoke_geom_fixture_gen.cpp -- DO NOT EDIT.
// Regenerate: build `smoke_geom_fixture_gen` and run it with the path of
// this file. The ctest `smoke_geom_fixture_fresh` fails if it is stale.
//
// Every SGF_EXP_* below is DERIVED FROM THE REFERENCE, not read off a run:
// zref::render::project_vertex -> zref::Clip -> zref::Setup ->
// zref::Binner, union of tiles x 256 (whole-tile resolve).
localparam int unsigned SGF_N_VERTS = 8;
localparam int unsigned SGF_N_TRIS  = 8;
localparam int unsigned SGF_N_MESHLETS = 3;
localparam int unsigned SGF_MESH_FIRST [0:2] = '{0, 3, 6};
localparam int unsigned SGF_MESH_NTRI  [0:2] = '{3, 3, 2};
localparam logic signed [31:0] SGF_VX [0:7] = '{32'shFFFF8000, 32'sh00008000, 32'sh00000000, 32'shFFFF3334, 32'sh0000CCCC, 32'sh00004CCC, 32'sh00000000, 32'sh0000E666};
localparam logic signed [31:0] SGF_VY [0:7] = '{32'shFFFF8000, 32'shFFFF8000, 32'sh00008000, 32'sh00009999, 32'sh0000B333, 32'shFFFF3334, 32'sh00000000, 32'sh0000E666};
localparam logic signed [31:0] SGF_VZ [0:7] = '{32'sh00010000, 32'sh00010000, 32'sh00018000, 32'sh00020000, 32'sh00020000, 32'sh00030000, 32'shFFFF0000, 32'sh00014000};
localparam logic signed [15:0] SGF_VU [0:7] = '{16'sh0800, 16'shF000, 16'sh2400, 16'sh0100, 16'shD000, 16'sh1800, 16'sh0000, 16'sh7000};
localparam logic signed [15:0] SGF_VV [0:7] = '{16'shFC00, 16'sh0C00, 16'sh2000, 16'shD800, 16'sh3400, 16'sh0600, 16'sh0000, 16'sh9000};
localparam logic [7:0] SGF_IX [0:23] = '{8'd0, 8'd1, 8'd2, 8'd0, 8'd2, 8'd3, 8'd1, 8'd4, 8'd2, 8'd3, 8'd2, 8'd4, 8'd5, 8'd1, 8'd0, 8'd0, 8'd1, 8'd6, 8'd7, 8'd4, 8'd1, 8'd3, 8'd4, 8'd7};
localparam logic signed [31:0] SGF_MAT [0:15] = '{32'sh00010000, 32'sh00000000, 32'sh00000000, 32'sh00000000, 32'sh00000000, 32'sh00010000, 32'sh00000000, 32'sh00000000, 32'sh00000000, 32'sh00000000, 32'sh00010000, 32'sh00000000, 32'sh00000000, 32'sh00000000, 32'sh00010000, 32'sh00000000};
localparam logic [31:0] SGF_VP0_ORG = 32'h00000000;  // x0=0 y0=0
localparam logic [31:0] SGF_VP0_EXT = 32'h00400020;  // w=32 h=64
localparam logic [31:0] SGF_VP1_ORG = 32'h00000020;  // x0=32 y0=0
localparam logic [31:0] SGF_VP1_EXT = 32'h00400020;  // w=32 h=64
localparam int unsigned SGF_EXP_REPLAYED = 16;  // view-triangles out of GEOM.REPLAY
localparam int unsigned SGF_EXP_CLIPPED  = 2;  // GEOM.CLIP `clipped` (near plane / empty box)
localparam int unsigned SGF_EXP_CULLED   = 0;  // GEOM.CLIP `culled` (zero area / backface)
localparam int unsigned SGF_EXP_ACCEPTED = 14;  // into GEOM.SETUP
localparam int unsigned SGF_TERR_RECORDS = 3;
localparam int SGF_TERR_IX0 = 0;  // record r: patch_ix = r + this
localparam int SGF_TERR_IZ0 = 1;  // record r: patch_iz = r + this
localparam int SGF_TERR_PITCH_LOG2 = 0;  // pitch = 2^this metres
localparam logic signed [15:0] SGF_TERR_BASE_H16 = -16'sd5120, SGF_TERR_TILTX_H16 = 16'sd256, SGF_TERR_TILTZ_H16 = 16'sd128;  // layer A = BASE + TILTX*vi + TILTZ*vj, height16 raw (256 = 1 m)
localparam int unsigned SGF_TERR_JOBS = 1;  // subpatch jobs, MEASURED (`SMOKE: terrjob`)
localparam int unsigned SGF_TERR_LEVEL = 0;  // every job's LOD level
localparam int unsigned SGF_EXP_TERR_TRIS     = 128;  // TERRAIN.CLIPFEED emits (1 job x 128)
localparam int unsigned SGF_EXP_TERR_CLIPPED  = 67;  // sub-pixel: no pixel centre inside
localparam int unsigned SGF_EXP_TERR_CULLED   = 0;  // ZERO AREA -- must stay 0
localparam int unsigned SGF_EXP_TERR_ACCEPTED = 61;  // into GEOM.SETUP
localparam int unsigned SGF_EXP_TERR_TILES    = 2;  // tiles TERRAIN touches
localparam int unsigned SGF_EXP_MESH_TILES    = 10;  // tiles the MESH touches
localparam int unsigned SGF_EXP_TILES    = 11;  // UNION, mesh + terrain, over both views
localparam int unsigned SGF_EXP_PIXELS   = 2816;  // tiles x 16 x 16 (was 2560, mesh only, before terrain drew)
localparam int unsigned SGF_EXP_TILE_REFS  = 101;  // GEOM.BINNER catalog id 18, references PUSHED
localparam int unsigned SGF_EXP_TILE_DEPTH = 59;  // GEOM.BINNER catalog id 19, the deepest tile list
localparam int unsigned SGF_BINNER_TRI_CAP = 128;  // zhao_geom_bin_pipe_v2 TRI_CAP, triangles per frame
localparam logic [15:0] SGF_ENV_YAW = 16'h4000, SGF_ENV_PITCH = 16'h1000, SGF_ENV_SUN = 16'hFD0C, SGF_ENV_AMB = 16'h10C4;  // the SetEnvironment record
localparam logic [16:0] SGF_EXP_LIT_R = 17'd64406, SGF_EXP_LIT_G = 17'd44459, SGF_EXP_LIT_B = 17'd31863;  // bank_of(record) -> L=(60547,25080,0), ndl 60547
// Mesh tiles, (tx,ty): (0,1) (0,2) (1,1) (1,2) (1,3) (2,1) (2,2) (3,1) (3,2) (3,3)
// Terrain tiles, (tx,ty): (1,0) (1,1)
