#!/usr/bin/env python3
"""gen_calib.py -- generate the Quartus calibration microbenches.

WHY
===
`design/budgets/dsp.md` was corrected on 2026-08-23 because its rule was
half wrong.  The measured half stands -- Quartus 17.0.2 Lite packs nothing, so
DSP count tracks OPERATOR count -- but the qualifier "whatever the operand
widths" does not survive `reports/QUARTUS_GOTCHAS.md` 5, which records the
SAME `zhao_geom_lod` source costing **28 DSPs at 72-bit operands and 18 at
64-bit**.  Width changes the cost, discontinuously.

So the corrected rule says operator count is a **LOWER BOUND**, and leaves the
audit with no way to turn "three signed 33x32 products, input and output
registered" into a number.  This generates the modules that answer that
question on **this exact tool and this exact device**, rather than from a
datasheet or from memory.

WHAT IT GENERATES
=================
multiply grid
  widths 8/9/16/18/19/24/26/27/28/31/32/33/40/48/64, signed and unsigned, at 1
  and 4 operators, input+output registered.  The 1-vs-4 pair is the PACKING
  test: if four operators cost four times one, Lite packs nothing at that
  width, which is what the corrected rule claims and what this either confirms
  or refutes.  The 26/27/28 cluster locates the cliff -- the design-derived
  curve in reports/BUDGET_HEATMAP.md shows 21- and 23-bit products taking ONE
  DSP block in the tool's `Independent 27x27` mode and 32-bit products taking
  THREE, so the interesting boundary is between 27 and 32, not at 18.

register grid
  widths 18/32/64 signed, one operator, combinational vs input-registered vs
  input+output-registered.  A DSP block's own input and output registers are
  free only if the RTL puts registers where the block expects them; this says
  whether that is happening.

widening-idiom control
  `{{32{a[31]}}, a} * {{32{b[31]}}, b}` -- the SystemVerilog idiom for a
  widening signed product -- against a plain `signed 32 x signed 32`.  This
  exists because the first draft of `scan_rtl.py` flagged the idiom as
  extension slack, and the claim that Quartus folds it away needs a measurement
  rather than an inference from one module's total.

RAM grid
  sync vs async read, reset vs no reset, four depth/width shapes, one and two
  ports, plus byte enables.  `blockMemoryBits > 0` is the only evidence an
  array became a memory; `zhao_field_seq` reports zero while spending 8,901
  ALMs, and `Allow Any RAM Size For Recognition` is DISABLED in this project's
  settings, so inference cannot be assumed anywhere.

Each module has REGISTERED PORTS wherever the point is not about registering,
so the fitter sees a real boundary rather than several hundred virtual pins
feeding raw combinational logic.
"""

from __future__ import annotations

import argparse
import json
import os

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
OUTDIR = os.path.join(REPO, "build-budget", "calib")

# 26/27/28 were added after the design-derived cost curve showed the boundary
# is NOT at 18. zhao_geom_setup's 21-bit and zhao_raster_edgewalk's 23-bit
# products each take ONE DSP block and the tool's own decomposition calls them
# `Independent 27x27` -- so Cyclone V has a 27x27 mode and the interesting
# cliff is between 27 and 32, not between 18 and 19. Sampling only 24 and 31
# would have bracketed it without locating it.
WIDTHS = [8, 9, 16, 18, 19, 24, 26, 27, 28, 31, 32, 33, 40, 48, 64]
REG_WIDTHS = [18, 32, 64]


def mul_module(name, width, signed, nops, style):
    """style: 'comb' | 'inreg' | 'ioreg'."""
    s = "signed " if signed else ""
    rw = 2 * width
    L = []
    L.append("// GENERATED by tools/budget/gen_calib.py -- calibration microbench.")
    L.append("// %s: %d operator(s), %s%d-bit operands, %s." % (
        name, nops, "signed " if signed else "unsigned ", width, style))
    L.append("module %s (" % name)
    L.append("    input  logic clk,")
    L.append("    input  logic rst_n,")
    for i in range(nops):
        L.append("    input  logic %s[%d:0] a%d_i," % (s, width - 1, i))
        L.append("    input  logic %s[%d:0] b%d_i," % (s, width - 1, i))
    L.append("    output logic %s[%d:0] y_o" % (s, rw - 1))
    L.append(");")
    if style == "comb":
        # Operands straight from the pins; result straight to the pin.
        terms = " + ".join("(a%d_i * b%d_i)" % (i, i) for i in range(nops))
        L.append("  assign y_o = %s;" % terms)
    else:
        for i in range(nops):
            L.append("  logic %s[%d:0] a%d_r, b%d_r;" % (s, width - 1, i, i))
        L.append("  logic %s[%d:0] p_c;" % (s, rw - 1))
        terms = " + ".join("(a%d_r * b%d_r)" % (i, i) for i in range(nops))
        L.append("  always_comb p_c = %s;" % terms)
        if style == "ioreg":
            L.append("  logic %s[%d:0] p_r;" % (s, rw - 1))
        L.append("  always_ff @(posedge clk or negedge rst_n) begin")
        L.append("    if (!rst_n) begin")
        for i in range(nops):
            L.append("      a%d_r <= '0; b%d_r <= '0;" % (i, i))
        if style == "ioreg":
            L.append("      p_r <= '0;")
        L.append("    end else begin")
        for i in range(nops):
            L.append("      a%d_r <= a%d_i; b%d_r <= b%d_i;" % (i, i, i, i))
        if style == "ioreg":
            L.append("      p_r <= p_c;")
        L.append("    end")
        L.append("  end")
        L.append("  assign y_o = %s;" % ("p_r" if style == "ioreg" else "p_c"))
    L.append("endmodule")
    return "\n".join(L) + "\n"


def widening_idiom_module(name, explicit):
    """The widening-signed-multiply control pair.

    explicit=True writes the SystemVerilog idiom with the sign extension
    spelled out, which is what zhao_geom_project's mul32 does nine times.
    explicit=False writes the plain signed product and lets the language widen
    it. If the two map to the same DSP count, the idiom is free and
    scan_rtl.py is right not to flag it.
    """
    L = ["// GENERATED by tools/budget/gen_calib.py -- widening-idiom control.",
         "module %s (" % name,
         "    input  logic clk,",
         "    input  logic rst_n,",
         "    input  logic signed [31:0] a_i,",
         "    input  logic signed [31:0] b_i,",
         "    output logic signed [63:0] y_o",
         ");",
         "  logic signed [31:0] a_r, b_r;",
         "  logic signed [63:0] p_r;"]
    if explicit:
        L.append("  logic signed [63:0] p_c;")
        L.append("  always_comb p_c = $signed({{32{a_r[31]}}, a_r}) * $signed({{32{b_r[31]}}, b_r});")
    else:
        L.append("  logic signed [63:0] p_c;")
        L.append("  always_comb p_c = 64'(a_r) * 64'(b_r);")
    L += ["  always_ff @(posedge clk or negedge rst_n) begin",
          "    if (!rst_n) begin a_r <= '0; b_r <= '0; p_r <= '0; end",
          "    else begin a_r <= a_i; b_r <= b_i; p_r <= p_c; end",
          "  end",
          "  assign y_o = p_r;",
          "endmodule"]
    return "\n".join(L) + "\n"


def ram_rdw_module(name, depth, width, shared, read_enable):
    """The two axes the original RAM grid never varied, and which SURFACE.SHEET
    turns out to depend on.

    Every `sync` point in the grid above writes in one `always_ff` and reads in
    ANOTHER, with NO read enable:

        always_ff @(posedge clk) if (we_i) mem[waddr_i] <= wdata_i;
        always_ff @(posedge clk) rdata_o <= mem[raddr_i];

    Real blocks do not look like that. `zhao_surface_sheet` puts both accesses
    in ONE process, which is what makes read-during-write return the OLD word
    (its contract's C5 states that semantic rather than leaving it to the
    synthesiser), and it gates the read with an enable so a stalled response
    does not lose its word. Neither variation was measured, so "it infers" was
    not actually known for the shape that matters.

      shared=True   read and write in one `always_ff` -> read-during-write
                    returns the PRE-write word (Intel's own single-clock simple
                    dual-port template).
      shared=False  read in its own `always_ff`.
      read_enable   gate the read with `if (re_i)`.

    Depth/width default to 8192x8 at the call site: that is one byte plane of
    SURFACE.SHEET at `Slots = 2`, i.e. the array this run proposes to build.
    """
    aw = max(1, (depth - 1).bit_length())
    L = ["// GENERATED by tools/budget/gen_calib.py -- RAM read-during-write template.",
         "// %s: %dx%d, sync read, no reset, 1 port, %s process, read enable %s." % (
             name, depth, width,
             "SHARED read/write" if shared else "separate read",
             "YES" if read_enable else "no"),
         "module %s (" % name,
         "    input  logic clk,",
         "    input  logic we_i,"]
    if read_enable:
        L.append("    input  logic re_i,")
    L += ["    input  logic [%d:0] waddr_i," % (aw - 1),
          "    input  logic [%d:0] wdata_i," % (width - 1),
          "    input  logic [%d:0] raddr_i," % (aw - 1),
          "    output logic [%d:0] rdata_o" % (width - 1),
          ");",
          "  logic [%d:0] mem [0:%d];" % (width - 1, depth - 1)]
    rd = "    %srdata_o <= mem[raddr_i];" % ("if (re_i) " if read_enable else "")
    wr = "    if (we_i) mem[waddr_i] <= wdata_i;"
    if shared:
        L += ["  always_ff @(posedge clk) begin", rd, wr, "  end"]
    else:
        L += ["  always_ff @(posedge clk) begin", wr, "  end",
              "  always_ff @(posedge clk) begin", rd, "  end"]
    L.append("endmodule")
    return "\n".join(L) + "\n"


def ram_module(name, depth, width, read_style, reset, ports, byteen):
    """read_style: 'sync' | 'async'.  ports: 1 | 2."""
    aw = max(1, (depth - 1).bit_length())
    L = ["// GENERATED by tools/budget/gen_calib.py -- RAM template microbench.",
         "// %s: %dx%d, %s read, %s, %d port(s)%s." % (
             name, depth, width, read_style,
             "reset-touched" if reset else "no reset", ports,
             ", byte enables" if byteen else "")]
    L.append("module %s (" % name)
    L.append("    input  logic clk,")
    L.append("    input  logic rst_n,")
    L.append("    input  logic we_i,")
    if byteen:
        L.append("    input  logic [%d:0] be_i," % (width // 8 - 1))
    L.append("    input  logic [%d:0] waddr_i," % (aw - 1))
    L.append("    input  logic [%d:0] wdata_i," % (width - 1))
    L.append("    input  logic [%d:0] raddr_i," % (aw - 1))
    L.append("    output logic [%d:0] rdata_o%s" % (width - 1, "," if ports == 2 else ""))
    if ports == 2:
        L.append("    input  logic [%d:0] raddr2_i," % (aw - 1))
        L.append("    output logic [%d:0] rdata2_o" % (width - 1))
    L.append(");")
    L.append("  logic [%d:0] mem [0:%d];" % (width - 1, depth - 1))
    if reset:
        L.append("  integer i;")
        L.append("  always_ff @(posedge clk or negedge rst_n) begin")
        L.append("    if (!rst_n) begin")
        L.append("      for (i = 0; i <= %d; i = i + 1) mem[i] <= '0;" % (depth - 1))
        L.append("    end else if (we_i) begin")
        if byteen:
            for b in range(width // 8):
                L.append("      if (be_i[%d]) mem[waddr_i][%d:%d] <= wdata_i[%d:%d];"
                         % (b, b * 8 + 7, b * 8, b * 8 + 7, b * 8))
        else:
            L.append("      mem[waddr_i] <= wdata_i;")
        L.append("    end")
        L.append("  end")
    else:
        L.append("  always_ff @(posedge clk) begin")
        L.append("    if (we_i) begin")
        if byteen:
            for b in range(width // 8):
                L.append("      if (be_i[%d]) mem[waddr_i][%d:%d] <= wdata_i[%d:%d];"
                         % (b, b * 8 + 7, b * 8, b * 8 + 7, b * 8))
        else:
            L.append("      mem[waddr_i] <= wdata_i;")
        L.append("    end")
        L.append("  end")
    if read_style == "async":
        L.append("  assign rdata_o = mem[raddr_i];")
        if ports == 2:
            L.append("  assign rdata2_o = mem[raddr2_i];")
    else:
        L.append("  always_ff @(posedge clk) rdata_o <= mem[raddr_i];")
        if ports == 2:
            L.append("  always_ff @(posedge clk) rdata2_o <= mem[raddr2_i];")
    L.append("endmodule")
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--outdir", default=OUTDIR)
    args = ap.parse_args()
    os.makedirs(args.outdir, exist_ok=True)

    points = []

    def emit(name, src, **meta):
        path = os.path.join(args.outdir, name + ".sv")
        with open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(src)
        rec = {"module": name, "file": os.path.relpath(path, REPO).replace(os.sep, "/")}
        rec.update(meta)
        points.append(rec)

    # ---- multiply grid: width x signedness x {1,4} operators -------------
    for w in WIDTHS:
        for signed in (False, True):
            for nops in (1, 4):
                nm = "calib_mul_%s%d_n%d_ioreg" % ("s" if signed else "u", w, nops)
                emit(nm, mul_module(nm, w, signed, nops, "ioreg"),
                     family="multiply", width=w, signed=signed, operators=nops,
                     style="ioreg")

    # ---- registering grid -----------------------------------------------
    for w in REG_WIDTHS:
        for style in ("comb", "inreg"):
            nm = "calib_mul_s%d_n1_%s" % (w, style)
            emit(nm, mul_module(nm, w, True, 1, style),
                 family="multiply", width=w, signed=True, operators=1, style=style)

    # ---- widening-idiom control pair ------------------------------------
    emit("calib_widen_explicit", widening_idiom_module("calib_widen_explicit", True),
         family="widening", width=32, signed=True, operators=1, style="ioreg",
         note="sign extension spelled out, as zhao_geom_project's mul32 writes it")
    emit("calib_widen_implicit", widening_idiom_module("calib_widen_implicit", False),
         family="widening", width=32, signed=True, operators=1, style="ioreg",
         note="plain widened signed product")

    # ---- RAM grid --------------------------------------------------------
    shapes = [(64, 32), (256, 16), (1024, 32), (2048, 18)]
    for (d, w) in shapes:
        for read_style in ("sync", "async"):
            for reset in (False, True):
                for ports in (1, 2):
                    nm = "calib_ram_%dx%d_%s_%s_p%d" % (
                        d, w, read_style, "rst" if reset else "norst", ports)
                    emit(nm, ram_module(nm, d, w, read_style, reset, ports, False),
                         family="ram", depth=d, width=w, readStyle=read_style,
                         reset=reset, ports=ports, byteEnables=False,
                         expectedBits=d * w)
    for (d, w) in [(1024, 32), (2048, 32)]:
        nm = "calib_ram_%dx%d_sync_norst_p1_be" % (d, w)
        emit(nm, ram_module(nm, d, w, "sync", False, 1, True),
             family="ram", depth=d, width=w, readStyle="sync", reset=False,
             ports=1, byteEnables=True, expectedBits=d * w)

    # ---- read-during-write / read-enable grid ----------------------------
    # RUN-20260824-0317. The `ram` grid above reads in a SEPARATE always_ff
    # with NO read enable, so it does not actually cover the template real
    # blocks use. SURFACE.SHEET shares one process (that is what makes
    # read-during-write return the OLD word -- its contract states the
    # semantic) and gates the read with an enable. Two axes, four points, at
    # 8192x8: one byte plane of SURFACE.SHEET at Slots = 2.
    for shared in (True, False):
        for re_ in (True, False):
            nm = "calib_ram_8192x8_%s_%s" % (
                "shared" if shared else "split", "re" if re_ else "nore")
            emit(nm, ram_rdw_module(nm, 8192, 8, shared, re_),
                 family="ram_rdw", depth=8192, width=8, readStyle="sync",
                 reset=False, ports=1, byteEnables=False,
                 sharedProcess=shared, readEnable=re_, expectedBits=8192 * 8)

    man = os.path.join(args.outdir, "manifest.json")
    with open(man, "w", encoding="utf-8", newline="\n") as fh:
        json.dump({"schemaVersion": 1, "generator": "tools/budget/gen_calib.py",
                   "points": points}, fh, indent=1)
        fh.write("\n")
    print("generated %d microbench module(s) into %s" % (len(points), args.outdir))
    fams = {}
    for p in points:
        fams[p["family"]] = fams.get(p["family"], 0) + 1
    for k, v in sorted(fams.items()):
        print("  %-10s %d" % (k, v))


if __name__ == "__main__":
    main()
