"""Mutants for tools/sweep_field_dsp.sh — the Field IR shared arithmetic engine.

Held in Python rather than in the shell for the reason
sweep_terrain_lod_mutants.py already gives: multi-line anchors inside a bash
array are a quoting hazard, and this sweep spans SEVEN files rather than one.

EACH ENTRY IS (name, file, old, new). The anchors are exact and must be UNIQUE
in their file; the preflight refuses to start otherwise, which is what stops a
mutation from silently landing in the wrong place.

WHAT IS BEING SWEPT, and why these and not the old list. The 2026-08-23
rearchitecture replaced ten parallel op units, each with its own multiplier,
with ONE shared lane, ONE integer root, ONE sine table and ONE reciprocal.
Almost none of the engine's previous mutants reach that logic, because it did
not exist. The families here are the new ones:

  * the LANE itself -- operand holding, product width, valid timing;
  * the READ-WALK ACCUMULATOR -- and specifically LOAD-versus-ACCUMULATE, which
    is the defect a shared accumulator can have and a parallel design cannot.
    It is invisible to every test that runs one op at a time, so it is the
    reason section 13 of field_seq_directed exists, and the reason it must be
    proven to FAIL on a mutant rather than merely pass on the shipped code;
  * the MUXES -- the root's, the sine table's, the reciprocal's and the lane's.
    Each selects on the executing opcode because only one instruction is ever
    live; a mux that leaks another unit's request is the shape of defect this
    architecture newly admits;
  * the SCHEDULE -- Q_LATCH reading from `ins_*_i`, Q_GATH existing at all, the
    slot indices. These are what keep MUL/MAD/DOT2/DOT3 at six clocks, and
    every one of them is a silent latency regression if it breaks;
  * the PER-OP WALKS that were rewritten around the lane's two-cycle latency --
    RCP's split correction product, NORMALIZE's four-step correction chain,
    RING's two reciprocal calls, CURVE's Horner chain, NOISE's and ROT's issue
    lists.
"""

import io
import os
import sys

F_MUL = 'fpga/rtl/field/zhao_field_mul.sv'
F_EXEC = 'fpga/rtl/field/zhao_field_exec_shared.sv'
F_SEQ = 'fpga/rtl/field/zhao_field_seq.sv'
F_RCP = 'fpga/rtl/field/zhao_field_rcp.sv'
F_NRM = 'fpga/rtl/field/zhao_field_normalize.sv'
F_LEN = 'fpga/rtl/field/zhao_field_len.sv'
F_RING = 'fpga/rtl/field/zhao_field_ring.sv'
F_CURVE = 'fpga/rtl/field/zhao_field_curve.sv'
F_NOISE = 'fpga/rtl/field/zhao_field_noise.sv'
F_ROT = 'fpga/rtl/field/zhao_field_rot.sv'

MUTS = [
    # ---- the lane -----------------------------------------------------------
    ("M01 lane operands not held between issues", F_MUL,
     """      if (issue_i) begin
        a_q <= a_i;
        b_q <= b_i;
      end""",
     """      begin
        a_q <= a_i;
        b_q <= b_i;
      end"""),
    ("M02 lane product arrives halved", F_MUL,
     """      p_o <= 66'(a_q) * 66'(b_q);""",
     """      p_o <= (66'(a_q) * 66'(b_q)) >>> 1;"""),
    ("M03 lane valid pulses a cycle early", F_MUL,
     """      p_valid_o <= v_q;""",
     """      p_valid_o <= v_q || issue_i;"""),
    # The 33rd bit is the whole reason the lane is 33 wide rather than 32: it is
    # what lets a u32 zero-extend and stay positive. Dropping it is the width
    # defect the header's argument is about.
    #
    # THIS REPLACED AN EARLIER M04 (`66'(33'(a_q) * 33'(b_q))`) THAT WAS
    # DISCARDED, not scored: Verilator generated byte-identical model sources
    # for it, so the sweep's guard refused to score a build that had not
    # changed. That is the guard working. The lesson is that a "truncation"
    # written as a size cast inside a wider assignment is not one.
    ("M04 lane treats its B operand as unsigned", F_MUL,
     """      p_o <= 66'(a_q) * 66'(b_q);""",
     """      p_o <= 66'(a_q) * 66'($unsigned(b_q));"""),

    # ---- the read-walk accumulator ------------------------------------------
    ("M05 accumulator ADDED to rather than LOADED (contamination)", F_EXEC,
     """          p_ab <= mul_p;
          acc  <= mul_p;""",
     """          p_ab <= mul_p;
          acc  <= acc + mul_p;"""),
    ("M06 prod_ab takes the accumulator instead of its own product", F_EXEC,
     """          p_ab <= mul_p;
          acc  <= mul_p;""",
     """          p_ab <= acc;
          acc  <= mul_p;"""),
    ("M07 slot shadow one stage deep, so products land a cycle early", F_EXEC,
     """      sp1_v   <= sp0_v;""",
     """      sp1_v   <= sp0_v || slot_issue_i;"""),
    ("M08 dot3 drops its third product", F_EXEC,
     """  assign dot3_w = acc + mul_p;""",
     """  assign dot3_w = acc;"""),

    # ---- the muxes ----------------------------------------------------------
    ("M09 root mux never starts NORMALIZE", F_EXEC,
     """  assign sqrt_valid  = op_is_len ? len_sq_valid  : (op_is_norm && nrm_sq_valid);""",
     """  assign sqrt_valid  = op_is_len ? len_sq_valid  : (op_is_len && nrm_sq_valid);"""),
    ("M10 root operand always NORMALIZE's", F_EXEC,
     """  assign sqrt_n      = op_is_len ? len_sq_n      : nrm_sq_n;""",
     """  assign sqrt_n      = op_is_norm ? len_sq_n     : nrm_sq_n;"""),
    ("M11 reciprocal operand ignores RING's span", F_EXEC,
     """  assign rcp_a      = op_is_ring ? rg_rcp_a      : a0_i;""",
     """  assign rcp_a      = op_is_ring ? a0_i          : rg_rcp_a;"""),
    ("M12 sine table ignores ROT's angle", F_EXEC,
     """  assign sin_angle  = op_is_rot ? rt_sin_angle : a0_i[15:0];""",
     """  assign sin_angle  = op_is_rot ? a0_i[15:0] : rt_sin_angle;"""),
    ("M13 lane mux drops the read-walk slots", F_EXEC,
     """    if (slot_issue_i) begin
      mul_issue = 1'b1;""",
     """    if (1'b0) begin
      mul_issue = 1'b1;"""),
    ("M14 lane mux never issues the shared reciprocal's products", F_EXEC,
     """    end else if (rcp_mul_issue) begin
      mul_issue = 1'b1;""",
     """    end else if (rcp_mul_issue) begin
      mul_issue = 1'b0;"""),
    ("M15 unit mux leaks LEN's request for every opcode", F_EXEC,
     """    if (op_is_len) begin
      unit_issue = len_mul_issue;""",
     """    if (1'b1) begin
      unit_issue = len_mul_issue;"""),

    # ---- the schedule -------------------------------------------------------
    # Re-anchored 2026-08-24: the register file became block memory, so a read
    # is answered one edge after its address and slot 0 first issues in Q_RD1.
    # Q_LATCH now only ADDRESSES group 0. Intent unchanged.
    ("M16 first slot labelled as the second", F_SEQ,
     """      Q_RD1:   begin slot_issue = 1'b1; slot_idx = 2'd0; end""",
     """      Q_RD1:   begin slot_issue = 1'b1; slot_idx = 2'd1; end"""),
    ("M17 Q_LATCH reads the PREVIOUS instruction's operand addresses", F_SEQ,
     """      Q_LATCH: begin
        ra = ins_a_i;
        rb = ins_b_i;
        rc = ins_c_i;
      end""",
     """      Q_LATCH: begin
        ra = i_a;
        rb = i_b;
        rc = ins_c_i;
      end"""),
    ("M18 the gather state is skipped", F_SEQ,
     """        Q_RD3: begin
          a2 <= rd_a;       // group 2
          b2 <= rd_b;
          state <= Q_GATH;
        end""",
     """        Q_RD3: begin
          a2 <= rd_a;       // group 2
          b2 <= rd_b;
          state <= Q_EXEC;
        end"""),
    ("M19 the third slot never issues", F_SEQ,
     """      Q_RD3:   begin slot_issue = 1'b1; slot_idx = 2'd2; end""",
     """      Q_RD3:   begin slot_issue = 1'b0; slot_idx = 2'd2; end"""),
    ("M20 multi-cycle ops also write back in Q_EXEC", F_SEQ,
     """        if ((state == Q_EXEC) && exec_writes && !exec_is_end && !exec_unsupported
             && !multi_op) begin
          rf_wen = 1'b1; rf_waddr = i_dst;        rf_wdata = exec_result;""",
     """        if ((state == Q_EXEC) && exec_writes && !exec_is_end && !exec_unsupported
             ) begin
          rf_wen = 1'b1; rf_waddr = i_dst;        rf_wdata = exec_result;"""),

    # ---- the per-op walks ---------------------------------------------------
    ("M21 RCP swaps the two halves of its split correction product", F_RCP,
     """      S_CLO: begin
        mul_issue_o = 1'b1;
        mul_a_o     = $signed({17'd0, h_seed});
        mul_b_o     = $signed({1'b0, corr[31:0]});
      end
      S_CHI: begin
        mul_issue_o = 1'b1;
        mul_a_o     = $signed({17'd0, h_seed});
        mul_b_o     = $signed({16'd0, corr[48:32]});
      end""",
     """      S_CLO: begin
        mul_issue_o = 1'b1;
        mul_a_o     = $signed({17'd0, h_seed});
        mul_b_o     = $signed({16'd0, corr[48:32]});
      end
      S_CHI: begin
        mul_issue_o = 1'b1;
        mul_a_o     = $signed({1'b0, corr[31:0]});
        mul_b_o     = $signed({17'd0, h_seed});
      end"""),
    ("M22 RCP recombines the split product at the wrong weight", F_RCP,
     """            xc        <= xc + (66'(mul_p_i[63:0]) <<< 32);""",
     """            xc        <= xc + (66'(mul_p_i[63:0]) <<< 31);"""),
    ("M23 NORMALIZE's square accumulator carries over (contamination)", F_NRM,
     """            n2 <= (got_cnt == 2'd0) ? p_unsigned : (n2 + p_unsigned);""",
     """            n2 <= n2 + p_unsigned;"""),
    ("M24 NORMALIZE's second correction reuses the first seed", F_NRM,
     """      N_R3: begin
        mul_issue_o = 1'b1;
        mul_a_o = $signed({1'b0, x1_q});
        mul_b_o = $signed({1'b0, corr1});
      end""",
     """      N_R3: begin
        mul_issue_o = 1'b1;
        mul_a_o = $signed({2'd0, seed});
        mul_b_o = $signed({1'b0, corr1});
      end"""),
    ("M25 LEN's square accumulator carries over (contamination)", F_LEN,
     """            n2 <= (got_cnt == 2'd0) ? mul_p_i[63:0] : (n2 + mul_p_i[63:0]);""",
     """            n2 <= n2 + mul_p_i[63:0];"""),
    ("M26 RING takes the reciprocal's answer a state early", F_RING,
     """  assign rcp_rready_o = (state == G_SPANW);""",
     """  assign rcp_rready_o = (state == G_SPAN);"""),
    ("M27 RING's second smoothstep skips its reciprocal", F_RING,
     """              half <= 1'b1;
              e0 <= m_val;
              e1 <= h_r1;
              state <= G_SPAN;""",
     """              half <= 1'b1;
              e0 <= m_val;
              e1 <= h_r1;
              state <= G_T;"""),
    ("M28 CURVE's Horner steps two and three multiply by c3", F_CURVE,
     """      default: begin
        // S_H2 and S_H3 both walk `tt * u`, which is what makes this Horner.
        mul_a = tt;
        mul_b = u_reg;
      end""",
     """      default: begin
        // S_H2 and S_H3 both walk `tt * u`, which is what makes this Horner.
        mul_a = tt;
        mul_b = c3;
      end"""),
    ("M29 NOISE never issues its xor-shift product", F_NOISE,
     """  assign mul_issue_o = (state == S_MIX_X) || (state == S_MIX_Y) ||
                       (state == S_LCG)   || (state == S_RXS);""",
     """  assign mul_issue_o = (state == S_MIX_X) || (state == S_MIX_Y) ||
                       (state == S_LCG);"""),
    ("M30 ROT never issues its s*q product", F_ROT,
     """  assign mul_issue_o = (state == R_CP) || (state == R_SQ) ||
                       (state == R_SP) || (state == R_CQ);""",
     """  assign mul_issue_o = (state == R_CP) ||
                       (state == R_SP) || (state == R_CQ);"""),

    # ---- the ALU's new seam: it consumes products it no longer forms ---------
    ("M31 ALU's MUL and MAD swap the shared product for the dot", 'fpga/rtl/field/zhao_field_alu.sv',
     """    prod_ab = prod_ab_i;
    mad_ab  = prod_ab + (ext32(c_i) <<< 16);""",
     """    prod_ab = dot2_i;
    mad_ab  = prod_ab_i + (ext32(c_i) <<< 16);"""),
    ("M32 ALU's DOT2 and DOT3 swapped", 'fpga/rtl/field/zhao_field_alu.sv',
     """    dot2    = dot2_i;
    dot3    = dot3_i;""",
     """    dot2    = dot3_i;
    dot3    = dot2_i;"""),

    # ---- WHEN a long operation commits, which is not the same as WHAT --------
    #
    # M20 above removes the `!multi_op` term from the Q_EXEC write-back guard
    # and is PROVABLY EQUIVALENT (see the sweep header). That means the guard
    # was never actually tested, and the coordinator was right that a sequenced
    # engine needs the commit CYCLE pinned rather than only the commit VALUE.
    #
    # M33 is the mutant that tests it. Lane 0 is written in Q_MISS -- tens of
    # clocks before the unit has an answer -- and then overwritten by the real
    # value in Q_MWAIT. Every ANSWER in the suite stays correct, because nothing
    # reads reg[dst] in between: the decoder proves dst does not overlap this
    # instruction's sources, and the next instruction does not read the file
    # until after retirement.
    #
    # Section 14 of the differential is the only thing that catches it, and it
    # catches it by watching the register file DURING the walk with a sentinel
    # the early write destroys.
    ("M33 lane 0 commits in Q_MISS, before the unit has an answer", F_SEQ,
     """        end else if ((state == Q_MWAIT) && multi_rvalid) begin
          rf_wen = 1'b1; rf_waddr = i_dst;        rf_wdata = multi_o0;""",
     """        end else if ((state == Q_MISS) || ((state == Q_MWAIT) && multi_rvalid)) begin
          rf_wen = 1'b1; rf_waddr = i_dst;        rf_wdata = multi_o0;"""),

    # ---- the leading-zero count that replaced the critical path -------------
    #
    # The two 64-iteration loops these five mutants replace were the whole
    # design's worst setup path (78 logic levels, 8.59 MHz). The closed form is
    # bit-identical to them by an argument written out in the block, and an
    # argument is exactly the kind of thing that is wrong in one corner. These
    # aim at the corners: the exponent offset, the direction of the shift, the
    # zero guard, and the binary search's stages.
    ("M34 exponent offset off by one", F_NRM,
     """    d_exp = 8'sd40 - $signed({2'd0, lz});""",
     """    d_exp = 8'sd39 - $signed({2'd0, lz});"""),
    ("M35 the normalised slice is taken from the wrong bits", F_NRM,
     """  assign m_val = (h_rt == 64'd0) ? 24'd0 : lz_t[63:40];""",
     """  assign m_val = (h_rt == 64'd0) ? 24'd0 : lz_t[62:39];"""),
    ("M36 the zero-length guard is dropped", F_NRM,
     """  assign m_val = (h_rt == 64'd0) ? 24'd0 : lz_t[63:40];""",
     """  assign m_val = lz_t[63:40];"""),
    ("M37 the leading-zero search loses its last stage", F_NRM,
     """      if (lz_t[63] == 1'b0)     begin lz = lz + 6'd1;  lz_t = lz_t << 1;  end""",
     """      if (lz_t[63] == 1'b0)     begin lz = lz + 6'd0;  lz_t = lz_t << 1;  end"""),
    ("M38 a leading-zero stage tests the wrong half", F_NRM,
     """      if (lz_t[63:32] == 32'd0) begin lz = lz + 6'd32; lz_t = lz_t << 32; end""",
     """      if (lz_t[63:33] == 31'd0) begin lz = lz + 6'd32; lz_t = lz_t << 32; end"""),
]


def _nl(raw):
    return '\r\n' if '\r\n' in raw else '\n'


def files():
    seen = []
    for _, f, _, _ in MUTS:
        if f not in seen:
            seen.append(f)
    return seen


def apply(k):
    name, path, old, new = MUTS[k]
    raw = io.open(path, encoding='utf-8', newline='').read()
    nl = _nl(raw)
    o = old.replace('\n', nl)
    n = new.replace('\n', nl)
    if raw.count(o) != 1:
        sys.stderr.write('%s: ANCHOR NOT UNIQUE (%d) in %s\n' % (name, raw.count(o), path))
        return False
    if o == n:
        sys.stderr.write('%s: MUTANT IDENTICAL TO BASE\n' % name)
        return False
    io.open(path, 'w', encoding='utf-8', newline='').write(raw.replace(o, n, 1))
    os.utime(path, None)   # NOW, never the future -- see the sweep's header
    return True


def main():
    if len(sys.argv) >= 2 and sys.argv[1] == '--count':
        print(len(MUTS))
        return 0
    if len(sys.argv) >= 2 and sys.argv[1] == '--files':
        for f in files():
            print(f)
        return 0
    if len(sys.argv) >= 3 and sys.argv[1] == '--name':
        print(MUTS[int(sys.argv[2])][0])
        return 0
    if len(sys.argv) >= 3 and sys.argv[1] == '--file':
        print(MUTS[int(sys.argv[2])][1])
        return 0
    if len(sys.argv) >= 3 and sys.argv[1] == '--apply':
        return 0 if apply(int(sys.argv[2])) else 9
    sys.stderr.write('usage: --count | --files | --name K | --file K | --apply K\n')
    return 2


if __name__ == '__main__':
    sys.exit(main())
