"""Mutants for tools/sweep_field_dsp.sh — the Field IR shared arithmetic engine.

Held in Python rather than in the shell for the reason
sweep_terrain_lod_mutants.py already gives: multi-line anchors inside a bash
array are a quoting hazard, and this sweep spans SEVEN files rather than one.

EACH ENTRY IS (name, file, old, new). The anchors are exact and must be UNIQUE
in their file; the preflight refuses to start otherwise, which is what stops a
mutation from silently landing in the wrong place.

WHAT IS BEING SWEPT, and why these and not the old list. The 2026-08-23
rearchitecture replaced ten parallel op units, each with its own multiplier,
with ONE shared lane, ONE integer root, ONE sine table and ONE reciprocal.
Almost none of the engine's previous mutants reach that logic, because it did
not exist. The families here are the new ones:

  * the LANE itself -- operand holding, product width, valid timing;
  * the READ-WALK ACCUMULATOR -- and specifically LOAD-versus-ACCUMULATE, which
    is the defect a shared accumulator can have and a parallel design cannot.
    It is invisible to every test that runs one op at a time, so it is the
    reason section 13 of field_seq_directed exists, and the reason it must be
    proven to FAIL on a mutant rather than merely pass on the shipped code;
  * the MUXES -- the root's, the sine table's, the reciprocal's and the lane's.
    Each selects on the executing opcode because only one instruction is ever
    live; a mux that leaks another unit's request is the shape of defect this
    architecture newly admits;
  * the SCHEDULE -- Q_LATCH reading from `ins_*_i`, Q_GATH existing at all, the
    slot indices. These are what keep MUL/MAD/DOT2/DOT3 at six clocks, and
    every one of them is a silent latency regression if it breaks;
  * the PER-OP WALKS that were rewritten around the lane's two-cycle latency --
    RCP's split correction product, NORMALIZE's four-step correction chain,
    RING's two reciprocal calls, CURVE's Horner chain, NOISE's and ROT's issue
    lists.
"""

import io
import os
import sys

F_MUL = 'fpga/rtl/field/zhao_field_mul.sv'
F_EXEC = 'fpga/rtl/field/zhao_field_exec_shared.sv'
F_SEQ = 'fpga/rtl/field/zhao_field_seq.sv'
F_RCP = 'fpga/rtl/field/zhao_field_rcp.sv'
F_NRM = 'fpga/rtl/field/zhao_field_normalize.sv'
F_LEN = 'fpga/rtl/field/zhao_field_len.sv'
F_RING = 'fpga/rtl/field/zhao_field_ring.sv'
F_CURVE = 'fpga/rtl/field/zhao_field_curve.sv'
F_NOISE = 'fpga/rtl/field/zhao_field_noise.sv'
F_ROT = 'fpga/rtl/field/zhao_field_rot.sv'
F_SINK = 'fpga/rtl/field/zhao_field_sinks.sv'
F_SIN = 'fpga/rtl/field/zhao_field_sin.sv'
F_PROG = 'fpga/rtl/field/zhao_field_progcache.sv'
F_V2 = 'fpga/rtl/field/zhao_field_v2_core.sv'
F_LMUX = 'fpga/rtl/field/zhao_field_v2_lanemux.sv'
F_FRONT = 'fpga/rtl/field/zhao_field_v2_front.sv'

MUTS = [
    # ---- the lane -----------------------------------------------------------
    ("M01 lane operands not held between issues", F_MUL,
     """      if (issue_i) begin
        a_q <= a_i;
        b_q <= b_i;
      end""",
     """      begin
        a_q <= a_i;
        b_q <= b_i;
      end"""),
    ("M02 lane product arrives halved", F_MUL,
     """      p_o <= 66'(a_q) * 66'(b_q);""",
     """      p_o <= (66'(a_q) * 66'(b_q)) >>> 1;"""),
    ("M03 lane valid pulses a cycle early", F_MUL,
     """      p_valid_o <= v_q;""",
     """      p_valid_o <= v_q || issue_i;"""),
    # The 33rd bit is the whole reason the lane is 33 wide rather than 32: it is
    # what lets a u32 zero-extend and stay positive. Dropping it is the width
    # defect the header's argument is about.
    #
    # THIS REPLACED AN EARLIER M04 (`66'(33'(a_q) * 33'(b_q))`) THAT WAS
    # DISCARDED, not scored: Verilator generated byte-identical model sources
    # for it, so the sweep's guard refused to score a build that had not
    # changed. That is the guard working. The lesson is that a "truncation"
    # written as a size cast inside a wider assignment is not one.
    ("M04 lane treats its B operand as unsigned", F_MUL,
     """      p_o <= 66'(a_q) * 66'(b_q);""",
     """      p_o <= 66'(a_q) * 66'($unsigned(b_q));"""),

    # ---- the read-walk accumulator ------------------------------------------
    ("M05 accumulator ADDED to rather than LOADED (contamination)", F_EXEC,
     """          p_ab <= mul_p;
          acc  <= mul_p;""",
     """          p_ab <= mul_p;
          acc  <= acc + mul_p;"""),
    ("M06 prod_ab takes the accumulator instead of its own product", F_EXEC,
     """          p_ab <= mul_p;
          acc  <= mul_p;""",
     """          p_ab <= acc;
          acc  <= mul_p;"""),
    ("M07 slot shadow one stage deep, so products land a cycle early", F_EXEC,
     """      sp1_v   <= sp0_v;""",
     """      sp1_v   <= sp0_v || slot_issue_i;"""),
    ("M08 dot3 drops its third product", F_EXEC,
     """  assign dot3_w = acc + mul_p;""",
     """  assign dot3_w = acc;"""),

    # ---- the muxes ----------------------------------------------------------
    ("M09 root mux never starts NORMALIZE", F_EXEC,
     """  assign sqrt_valid  = op_is_len ? len_sq_valid  : (op_is_norm && nrm_sq_valid);""",
     """  assign sqrt_valid  = op_is_len ? len_sq_valid  : (op_is_len && nrm_sq_valid);"""),
    ("M10 root operand always NORMALIZE's", F_EXEC,
     """  assign sqrt_n      = op_is_len ? len_sq_n      : nrm_sq_n;""",
     """  assign sqrt_n      = op_is_norm ? len_sq_n     : nrm_sq_n;"""),
    ("M11 reciprocal operand ignores RING's span", F_EXEC,
     """  assign rcp_a      = op_is_ring ? rg_rcp_a      : a0_i;""",
     """  assign rcp_a      = op_is_ring ? a0_i          : rg_rcp_a;"""),
    ("M12 sine table ignores ROT's angle", F_EXEC,
     """  assign sin_angle  = op_is_rot ? rt_sin_angle : a0_i[15:0];""",
     """  assign sin_angle  = op_is_rot ? a0_i[15:0] : rt_sin_angle;"""),
    ("M13 lane mux drops the read-walk slots", F_EXEC,
     """    if (slot_issue_i) begin
      mul_issue = 1'b1;""",
     """    if (1'b0) begin
      mul_issue = 1'b1;"""),
    ("M14 lane mux never issues the shared reciprocal's products", F_EXEC,
     """    end else if (rcp_mul_issue) begin
      mul_issue = 1'b1;""",
     """    end else if (rcp_mul_issue) begin
      mul_issue = 1'b0;"""),
    ("M15 unit mux leaks LEN's request for every opcode", F_EXEC,
     """    if (op_is_len) begin
      unit_issue = len_mul_issue;""",
     """    if (1'b1) begin
      unit_issue = len_mul_issue;"""),

    # ---- the schedule -------------------------------------------------------
    # Re-anchored 2026-08-24: the register file became block memory, so a read
    # is answered one edge after its address and slot 0 first issues in Q_RD1.
    # Q_LATCH now only ADDRESSES group 0. Intent unchanged.
    ("M16 first slot labelled as the second", F_SEQ,
     """      Q_RD1:   begin slot_issue = 1'b1; slot_idx = 2'd0; end""",
     """      Q_RD1:   begin slot_issue = 1'b1; slot_idx = 2'd1; end"""),
    ("M17 Q_LATCH reads the PREVIOUS instruction's operand addresses", F_SEQ,
     """      Q_LATCH: begin
        ra = ins_a_i;
        rb = ins_b_i;
        rc = ins_c_i;
      end""",
     """      Q_LATCH: begin
        ra = i_a;
        rb = i_b;
        rc = ins_c_i;
      end"""),
    ("M18 the gather state is skipped", F_SEQ,
     """        Q_RD3: begin
          a2 <= rd_a;       // group 2
          b2 <= rd_b;
          state <= Q_GATH;
        end""",
     """        Q_RD3: begin
          a2 <= rd_a;       // group 2
          b2 <= rd_b;
          state <= Q_EXEC;
        end"""),
    ("M19 the third slot never issues", F_SEQ,
     """      Q_RD3:   begin slot_issue = 1'b1; slot_idx = 2'd2; end""",
     """      Q_RD3:   begin slot_issue = 1'b0; slot_idx = 2'd2; end"""),
    ("M20 multi-cycle ops also write back in Q_EXEC", F_SEQ,
     """        if ((state == Q_EXEC) && exec_writes && !exec_is_end && !exec_unsupported
             && !multi_op) begin
          rf_wen = 1'b1; rf_waddr = i_dst;        rf_wdata = exec_result;""",
     """        if ((state == Q_EXEC) && exec_writes && !exec_is_end && !exec_unsupported
             ) begin
          rf_wen = 1'b1; rf_waddr = i_dst;        rf_wdata = exec_result;"""),

    # ---- the per-op walks ---------------------------------------------------
    ("M21 RCP swaps the two halves of its split correction product", F_RCP,
     """      S_CLO: begin
        mul_issue_o = 1'b1;
        mul_a_o     = $signed({17'd0, h_seed});
        mul_b_o     = $signed({1'b0, corr[31:0]});
      end
      S_CHI: begin
        mul_issue_o = 1'b1;
        mul_a_o     = $signed({17'd0, h_seed});
        mul_b_o     = $signed({16'd0, corr[48:32]});
      end""",
     """      S_CLO: begin
        mul_issue_o = 1'b1;
        mul_a_o     = $signed({17'd0, h_seed});
        mul_b_o     = $signed({16'd0, corr[48:32]});
      end
      S_CHI: begin
        mul_issue_o = 1'b1;
        mul_a_o     = $signed({1'b0, corr[31:0]});
        mul_b_o     = $signed({17'd0, h_seed});
      end"""),
    ("M22 RCP recombines the split product at the wrong weight", F_RCP,
     """            xc        <= xc + (66'(mul_p_i[63:0]) <<< 32);""",
     """            xc        <= xc + (66'(mul_p_i[63:0]) <<< 31);"""),
    ("M23 NORMALIZE's square accumulator carries over (contamination)", F_NRM,
     """            n2 <= (got_cnt == 2'd0) ? p_unsigned : (n2 + p_unsigned);""",
     """            n2 <= n2 + p_unsigned;"""),
    ("M24 NORMALIZE's second correction reuses the first seed", F_NRM,
     """      N_R3: begin
        mul_issue_o = 1'b1;
        mul_a_o = $signed({1'b0, x1_q});
        mul_b_o = $signed({1'b0, corr1});
      end""",
     """      N_R3: begin
        mul_issue_o = 1'b1;
        mul_a_o = $signed({2'd0, seed});
        mul_b_o = $signed({1'b0, corr1});
      end"""),
    ("M25 LEN's square accumulator carries over (contamination)", F_LEN,
     """            n2 <= (got_cnt == 2'd0) ? mul_p_i[63:0] : (n2 + mul_p_i[63:0]);""",
     """            n2 <= n2 + mul_p_i[63:0];"""),
    ("M26 RING takes the reciprocal's answer a state early", F_RING,
     """  assign rcp_rready_o = (state == G_SPANW);""",
     """  assign rcp_rready_o = (state == G_SPAN);"""),
    ("M27 RING's second smoothstep skips its reciprocal", F_RING,
     """              half <= 1'b1;
              e0 <= m_val;
              e1 <= h_r1;
              state <= G_SPAN;""",
     """              half <= 1'b1;
              e0 <= m_val;
              e1 <= h_r1;
              state <= G_T;"""),
    ("M28 CURVE's Horner steps two and three multiply by c3", F_CURVE,
     """      default: begin
        // S_H2 and S_H3 both walk `tt * u`, which is what makes this Horner.
        mul_a = tt;
        mul_b = u_reg;
      end""",
     """      default: begin
        // S_H2 and S_H3 both walk `tt * u`, which is what makes this Horner.
        mul_a = tt;
        mul_b = c3;
      end"""),
    ("M29 NOISE never issues its xor-shift product", F_NOISE,
     """  assign mul_issue_o = (state == S_MIX_X) || (state == S_MIX_Y) ||
                       (state == S_LCG)   || (state == S_RXS);""",
     """  assign mul_issue_o = (state == S_MIX_X) || (state == S_MIX_Y) ||
                       (state == S_LCG);"""),
    ("M30 ROT never issues its s*q product", F_ROT,
     """  assign mul_issue_o = (state == R_CP) || (state == R_SQ) ||
                       (state == R_SP) || (state == R_CQ);""",
     """  assign mul_issue_o = (state == R_CP) ||
                       (state == R_SP) || (state == R_CQ);"""),

    # ---- the ALU's new seam: it consumes products it no longer forms ---------
    ("M31 ALU's MUL and MAD swap the shared product for the dot", 'fpga/rtl/field/zhao_field_alu.sv',
     """    prod_ab = prod_ab_i;
    mad_ab  = prod_ab + (ext32(c_i) <<< 16);""",
     """    prod_ab = dot2_i;
    mad_ab  = prod_ab_i + (ext32(c_i) <<< 16);"""),
    ("M32 ALU's DOT2 and DOT3 swapped", 'fpga/rtl/field/zhao_field_alu.sv',
     """    dot2    = dot2_i;
    dot3    = dot3_i;""",
     """    dot2    = dot3_i;
    dot3    = dot2_i;"""),

    # ---- WHEN a long operation commits, which is not the same as WHAT --------
    #
    # M20 above removes the `!multi_op` term from the Q_EXEC write-back guard
    # and is PROVABLY EQUIVALENT (see the sweep header). That means the guard
    # was never actually tested, and the coordinator was right that a sequenced
    # engine needs the commit CYCLE pinned rather than only the commit VALUE.
    #
    # M33 is the mutant that tests it. Lane 0 is written in Q_MISS -- tens of
    # clocks before the unit has an answer -- and then overwritten by the real
    # value in Q_MWAIT. Every ANSWER in the suite stays correct, because nothing
    # reads reg[dst] in between: the decoder proves dst does not overlap this
    # instruction's sources, and the next instruction does not read the file
    # until after retirement.
    #
    # Section 14 of the differential is the only thing that catches it, and it
    # catches it by watching the register file DURING the walk with a sentinel
    # the early write destroys.
    ("M33 lane 0 commits in Q_MISS, before the unit has an answer", F_SEQ,
     """        end else if ((state == Q_MWAIT) && multi_rvalid) begin
          rf_wen = 1'b1; rf_waddr = i_dst;        rf_wdata = multi_o0;""",
     """        end else if ((state == Q_MISS) || ((state == Q_MWAIT) && multi_rvalid)) begin
          rf_wen = 1'b1; rf_waddr = i_dst;        rf_wdata = multi_o0;"""),

    # ---- the leading-zero count that replaced the critical path -------------
    #
    # The two 64-iteration loops these five mutants replace were the whole
    # design's worst setup path (78 logic levels, 8.59 MHz). The closed form is
    # bit-identical to them by an argument written out in the block, and an
    # argument is exactly the kind of thing that is wrong in one corner. These
    # aim at the corners: the exponent offset, the direction of the shift, the
    # zero guard, and the binary search's stages.
    ("M34 exponent offset off by one", F_NRM,
     """    d_exp = 8'sd40 - $signed({2'd0, lz});""",
     """    d_exp = 8'sd39 - $signed({2'd0, lz});"""),
    ("M35 the normalised slice is taken from the wrong bits", F_NRM,
     """  assign m_val = (h_rt == 64'd0) ? 24'd0 : lz_t[63:40];""",
     """  assign m_val = (h_rt == 64'd0) ? 24'd0 : lz_t[62:39];"""),
    ("M36 the zero-length guard is dropped", F_NRM,
     """  assign m_val = (h_rt == 64'd0) ? 24'd0 : lz_t[63:40];""",
     """  assign m_val = lz_t[63:40];"""),
    ("M37 the leading-zero search loses its last stage", F_NRM,
     """      if (lz_t[63] == 1'b0)     begin lz = lz + 6'd1;  lz_t = lz_t << 1;  end""",
     """      if (lz_t[63] == 1'b0)     begin lz = lz + 6'd0;  lz_t = lz_t << 1;  end"""),
    ("M38 a leading-zero stage tests the wrong half", F_NRM,
     """      if (lz_t[63:32] == 32'd0) begin lz = lz + 6'd32; lz_t = lz_t << 32; end""",
     """      if (lz_t[63:33] == 31'd0) begin lz = lz + 6'd32; lz_t = lz_t << 32; end"""),

    # ---- the three Earth sinks ---------------------------------------------
    # The laws are the owner ruling of 2026-08-24. Each mutant is a DIFFERENT
    # defensible-looking rule, because that is the failure mode here: every one
    # of these is what a reasonable implementer might have written instead.
    ("M39 material ignores the enable, so a disabled write wins", F_SINK,
     """      if (wr_mat_en_i) begin""",
     """      if (1'b1) begin"""),
    ("M40 nav floors at zero PER STEP instead of once on the way out", F_SINK,
     """      nav_q <= nav_sat;""",
     """      nav_q <= (nav_sat < 32'sd0) ? 32'sd0 : nav_sat;"""),
    ("M41 nav wraps instead of saturating at the high rail", F_SINK,
     """  wire signed [31:0] nav_sat = (nav_sum > 33'sh0_7FFFFFFF) ? 32'sh7FFFFFFF""",
     """  wire signed [31:0] nav_sat = (nav_sum > 33'sh0_FFFFFFFF) ? 32'sh7FFFFFFF"""),
    ("M42 nav floors the ANSWER at one rather than zero", F_SINK,
     """  assign nav_o = (nav_q < 32'sd0) ? 32'sd0 : nav_q;""",
     """  assign nav_o = (nav_q < 32'sd1) ? 32'sd1 : nav_q;"""),
    ("M43 hazard SUMS severities instead of taking the maximum", F_SINK,
     """      if (haz_u8 > haz_q) haz_q <= haz_u8;""",
     """      haz_q <= (({1'b0, haz_q} + {1'b0, haz_u8}) > 9'd255)
                 ? 8'd255 : (haz_q + haz_u8);"""),
    ("M44 hazard lets a weak field LOWER authored danger", F_SINK,
     """      if (haz_u8 > haz_q) haz_q <= haz_u8;""",
     """      haz_q <= haz_u8;"""),
    ("M45 hazard does not floor a negative severity", F_SINK,
     """      lo = (s < 32'sd0) ? 32'sd0 : s;""",
     """      lo = s;"""),
    ("M46 hazard does not clamp at 1.0", F_SINK,
     """      cl = (lo > 32'sd65536) ? 17'd65536 : lo[16:0];""",
     """      cl = lo[16:0];"""),
    ("M47 hazard truncates instead of rounding half up", F_SINK,
     """      sev_to_u8 = 8'((({cl, 8'd0} - {8'd0, cl}) + 25'd32768) >> 16);""",
     """      sev_to_u8 = 8'((({cl, 8'd0} - {8'd0, cl}) + 25'd0) >> 16);"""),
    ("M48 hazard scales by 256 instead of 255", F_SINK,
     """      sev_to_u8 = 8'((({cl, 8'd0} - {8'd0, cl}) + 25'd32768) >> 16);""",
     """      sev_to_u8 = 8'(({cl, 8'd0} + 25'd32768) >> 16);"""),
    ("M49 the authored layer is not preserved when no write arrives", F_SINK,
     """      nav_q    <= auth_nav_i;""",
     """      nav_q    <= 32'sd0;"""),

    # ---- wave 5: the sine interpolation summed as a tree ---------------------
    # The restructure claims to be the SAME NUMBER, bit for bit. These attack
    # that claim: a dropped term, a duplicated one, a wrong weight, and the
    # rounding constant lost or negated. All are invisible to a reader and all
    # are caught by the exhaustive 65,536-angle differential.
    ("M50 the sine tree drops the top term", F_SIN,
     """    pair2 = term[4] + term[5];""",
     """    pair2 = term[4];"""),
    ("M51 the sine tree duplicates a term instead of summing two", F_SIN,
     """    pair1 = term[2] + term[3];""",
     """    pair1 = term[2] + term[2];"""),
    ("M52 a sine term is weighted by the wrong power of two", F_SIN,
     """    for (int k = 0; k < 6; k++) term[k] = t_q[k] ? (25'(d) <<< k) : 25'sd0;""",
     """    for (int k = 0; k < 6; k++) term[k] = t_q[k] ? (25'(d) <<< (k + 1)) : 25'sd0;"""),
    ("M53 the sine rounding constant is lost in the tree", F_SIN,
     """    pair3 = 25'sd32 + (25'($signed({1'b0, base})) <<< 6);""",
     """    pair3 = 25'sd0 + (25'($signed({1'b0, base})) <<< 6);"""),
    ("M54 the sine rounding constant rounds half DOWN", F_SIN,
     """    pair3 = 25'sd32 + (25'($signed({1'b0, base})) <<< 6);""",
     """    pair3 = -25'sd32 + (25'($signed({1'b0, base})) <<< 6);"""),
    # ---- wave 6: `base` folded into the tree --------------------------------
    # The fold claims ((base<<6) + X) >>> 6 == base + (X >>> 6). These attack
    # the claim at the only place it can fail: the shift amount, and whether
    # `base` reaches the sum at all.
    ("M56 the folded base is shifted by five instead of six", F_SIN,
     """    pair3 = 25'sd32 + (25'($signed({1'b0, base})) <<< 6);""",
     """    pair3 = 25'sd32 + (25'($signed({1'b0, base})) <<< 5);"""),
    ("M57 the folded base is not shifted at all", F_SIN,
     """    pair3 = 25'sd32 + (25'($signed({1'b0, base})) <<< 6);""",
     """    pair3 = 25'sd32 + 25'($signed({1'b0, base}));"""),
    ("M58 the folded base is dropped, so only the slope survives", F_SIN,
     """    pair3 = 25'sd32 + (25'($signed({1'b0, base})) <<< 6);""",
     """    pair3 = 25'sd32;"""),
    ("M59 the endpoint arm returns the interpolation instead of base", F_SIN,
     """    s_quarter = (i_q == 9'd256) ? 32'($signed({1'b0, base})) : 32'(interp);""",
     """    s_quarter = (i_q == 9'd256) ? 32'(interp) : 32'(interp);"""),
    ("M55 the sine tree SUBTRACTS one half instead of adding it", F_SIN,
     """    dt    = quad0 + quad1;""",
     """    dt    = quad0 - quad1;"""),
    # ---- wave 7: the rescale rounds with one bit instead of a 65-bit add -----
    # The claim is (v + 2^(k-1)) >> k == (v >>> k) + v[k-1], EXACTLY. These
    # attack the only places it can fail: which bit is read, whether it is read
    # at all, and the sign-extension guard for k-1 >= 64.
    ("M60 the rescale rounds from the wrong bit", F_NRM,
     """                            : v[6'(k - 8'd1)];""",
     """                            : v[6'(k)];"""),
    ("M61 the rescale truncates instead of rounding", F_NRM,
     """                            : v[6'(k - 8'd1)];""",
     """                            : 1'b0;"""),
    ("M62 the rescale always rounds up", F_NRM,
     """                            : v[6'(k - 8'd1)];""",
     """                            : 1'b1;"""),
    ("M63 the rescale shifts by one too many", F_NRM,
     """      sh     = (k == 8'd0) ? 65'(v) : (65'(v) >>> k);""",
     """      sh     = (k == 8'd0) ? 65'(v) : (65'(v) >>> (k + 8'd1));"""),
    ("M64 the sign-extension guard returns zero instead of the sign", F_NRM,
     """             : (k >= 8'd65) ? v[63]""",
     """             : (k >= 8'd65) ? 1'b0"""),
    # ---- wave 8: the sine result is registered, and ROT waits for it ---------
    # The pipeline boundary is only safe if every consumer waits. These attack
    # the two that must: ROT captures a state too early, and the latency itself.
    ("M65 ROT captures the cosine answer into the sine register", F_ROT,
     """        R_COSW: begin
          c_val <= trig_out;
          state <= R_SINW;
        end""",
     """        R_COSW: begin
          s_val <= trig_out;
          state <= R_SINW;
        end"""),
    ("M66 ROT skips the sine capture state, taking a stale answer", F_ROT,
     """        R_SINW: begin
          s_val <= trig_out;
          state <= R_CP;
        end""",
     """        R_SINW: begin
          s_val <= c_val;
          state <= R_CP;
        end"""),
    # M70 as first written ADDED a capture in R_SIN while leaving the correct
    # one in R_COSW. Two writes to the same register in successive states: the
    # later, correct one wins, so the mutant was EQUIVALENT BY CONSTRUCTION and
    # survived. It was a malformed mutant, not a coverage hole -- moving the
    # capture rather than duplicating it fails 1,158 of 3,495 checks.
    ("M70 ROT captures the cosine one clock early, before the table answers", F_ROT,
     """        R_SIN: begin
          state <= R_COSW;
        end

        R_COSW: begin
          c_val <= trig_out;
          state <= R_SINW;
        end""",
     """        R_SIN: begin
          c_val <= trig_out;
          state <= R_COSW;
        end

        R_COSW: begin
          state <= R_SINW;
        end"""),
    ("M67 the sine table answers two clocks late instead of one", F_SIN,
     """  always_ff @(posedge clk) result_o <= result_c;""",
     """  logic signed [31:0] result_d2;
  always_ff @(posedge clk) begin
    result_d2 <= result_c;
    result_o  <= result_d2;
  end"""),
    # ---- wave 9: the shift amount is registered ------------------------------
    # Removing the register is the OLD code and would be equivalent, so these
    # attack the value instead: never loading it, and loading it wrong.
    ("M68 the registered shift amount lags by TWO cycles instead of one", F_NRM,
     """  always_ff @(posedge clk) shift_amt_q <= shift_amt;""",
     """  logic [7:0] shift_amt_d;
  always_ff @(posedge clk) begin
    shift_amt_d <= shift_amt;
    shift_amt_q <= shift_amt_d;
  end"""),
    ("M69 the registered shift amount is off by one", F_NRM,
     """  always_ff @(posedge clk) shift_amt_q <= shift_amt;""",
     """  always_ff @(posedge clk) shift_amt_q <= shift_amt + 8'd1;"""),
    # ---- wave 10: the decode must travel with the registered table read ------
    # This is the one way the change breaks silently. A decode left LIVE against
    # a delayed read answers correctly whenever the input stands still, and is
    # wrong only when consecutive requests differ -- which is exactly ROT.
    ("M71 the travelling interpolation weight is the wrong value", F_SIN,
     """    t_q      <= t;""",
     """    t_q      <= t >> 1;"""),
    ("M72 the travelling sign is inverted", F_SIN,
     """    q_sign_q <= q[1];""",
     """    q_sign_q <= ~q[1];"""),
    ("M73 the travelling endpoint index is the NEXT index", F_SIN,
     """    i_q      <= i;""",
     """    i_q      <= i_next;"""),
    ("M75 the decode travels ONE CLOCK BEHIND the table read", F_SIN,
     """  always_ff @(posedge clk) begin
    q_sign_q <= q[1];
    t_q      <= t;
    i_q      <= i;
  end""",
     """  logic       q_sign_d;
  logic [5:0] t_d;
  logic [8:0] i_d;
  always_ff @(posedge clk) begin
    q_sign_d <= q[1];
    t_d      <= t;
    i_d      <= i;
    q_sign_q <= q_sign_d;
    t_q      <= t_d;
    i_q      <= i_d;
  end"""),
    ("M74 the two table ports are swapped", F_SIN,
     """      .val_a_o(base),
      .val_b_o(next_v)""",
     """      .val_a_o(next_v),
      .val_b_o(base)"""),
    # ---- FIELD.PROGCACHE, which the sweep never covered ---------------------
    # The audit of 2026-08-25 found this block has a directed test, RTL, and
    # NEITHER sweep coverage NOR an ENFORCED-BY marker. It was not deliberately
    # excluded; it was simply never added. These attack the four laws its header
    # states: hit restamps LRU, miss inserts into a free slot else evicts the
    # LEAST recently used, and the counters follow.
    ("M76 the victim is the MOST recently used entry", F_PROG,
     """      if (ent_valid[i] && ent_lru[i] <= best_lru) begin""",
     """      if (ent_valid[i] && ent_lru[i] >= best_lru) begin"""),
    ("M77 eviction is preferred over a free slot", F_PROG,
     """  assign victim = free_any ? free_idx : lru_idx;""",
     """  assign victim = lru_idx;"""),
    ("M78 a free slot is claimed even when the entry is valid", F_PROG,
     """      if (!ent_valid[i]) begin
        free_any = 1'b1;
        free_idx = IDXW'(i);
      end""",
     """      begin
        free_any = 1'b1;
        free_idx = IDXW'(i);
      end"""),
    ("M79 a lookup and a commit may fire on the same clock", F_PROG,
     """  assign cm_ready_o = (!cm_resp_valid_o || cm_resp_ready_i) && !lu_fire;""",
     """  assign cm_ready_o = (!cm_resp_valid_o || cm_resp_ready_i);"""),
    # ---- FIELD v2: the invariants a barrel core NEWLY admits ----------------
    # v1 could not have these defects because it had one instruction in flight
    # by construction. v2 has a scoreboard, wavefront tags and independent
    # lanes, and each of those is a new way to be wrong.
    ("M80 a wavefront may reissue while its instruction is still in flight", F_V2,
     """  assign ready = active & ~inflight & ~finished;""",
     """  assign ready = active & ~(inflight & finished) & ~finished;"""),
    ("M81 write-back uses the ISSUING wavefront, not the retiring one", F_V2,
     """      wb_addr = {s2_wf, s2_dst};""",
     """      wb_addr = {sel, s2_dst};"""),
    ("M82 every lane is written lane 0's result", F_V2,
     """        wb_data[wl] = alu_y[wl];""",
     """        wb_data[wl] = alu_y[0];"""),
    ("M83 an unsupported opcode is SKIPPED instead of refused", F_V2,
     """        default:   unsupported = 1'b1;     // REFUSED, not skipped and not zero""",
     """        default:   unsupported = 1'b0;     // MUTANT: silently skipped"""),
    # M84's anchor moved when CURVE landed: the clear now carries the long-op
    # guard. Rewritten onto the live line rather than relaxed -- the defect it
    # names (a wavefront that never comes back) is unchanged.
    ("M84 the retiring wavefront's in-flight bit is never cleared", F_V2,
     """        inflight[s2_wf] <= 1'b0;""",
     """        inflight[s2_wf] <= 1'b1;"""),
    # ---- v2's tagged lane serialiser ---------------------------------------
    # The tag is the whole point: v1 needed none because one instruction was in
    # flight, so a reply could only belong to the one thing waiting. These
    # attack the tag, the lane index, and the request/reply conservation.
    ("M85 the reply is tagged with the LIVE request, not the captured one", F_LMUX,
     """  assign rsp_wf_o    = wf_q;""",
     """  assign rsp_wf_o    = (state == S_DONE) ? req_wf_i : wf_q;"""),
    ("M86 the destination tag is taken live rather than carried", F_LMUX,
     """  assign rsp_dst_o   = dst_q;""",
     """  assign rsp_dst_o   = (state == S_DONE) ? req_dst_i : dst_q;"""),
    ("M87 a lane's answer is written to the NEXT lane's slot", F_LMUX,
     """          y_q[lane]  <= u_result_i;""",
     """          y_q[(lane + LW'(1)) & LW'(LANES-1)]  <= u_result_i;"""),
    ("M88 the last lane is skipped, so one lane keeps a stale answer", F_LMUX,
     """          if (lane == LW'(LANES-1)) begin""",
     """          if (lane >= LW'(LANES-2)) begin"""),
    ("M89 the unit is presented the wrong lane's operand", F_LMUX,
     """  assign u_a_o       = a_q[lane];""",
     """  assign u_a_o       = a_q[0];"""),
    # ---- v2's FIRST LONG OPERATION: the request/reply seam ------------------
    # CURVE/DCURVE/SPLINE are one unit in three modes, reached over a tagged
    # request/reply. That seam is where v2 can be wrong in ways neither v1 nor
    # v2's short-op core could be: a mode lost in translation, a reply written
    # to the wrong lanes, a wavefront released before its answer came back, or
    # a long op counted twice because it passes the retire logic twice.
    # M90 and M96 were re-anchored when the length family landed: the mode case
    # gained a unit selector and issue_fire gained the steal stall. Rewritten
    # onto the live lines, defects unchanged.
    ("M90 every curve mode collapses to plain CURVE", F_V2,
     """      OP_DCURVE: begin s1_mode = 2'd1; s1_unit = UNIT_CURVE; end
      OP_SPLINE: begin s1_mode = 2'd2; s1_unit = UNIT_CURVE; end""",
     """      OP_DCURVE: begin s1_mode = 2'd0; s1_unit = UNIT_CURVE; end
      OP_SPLINE: begin s1_mode = 2'd0; s1_unit = UNIT_CURVE; end"""),
    ("M91 the long-op reply broadcasts lane 0 to every lane", F_V2,
     """          wbq_y[l][0] <= lm_rsp_y[l];""",
     """          wbq_y[l][0] <= lm_rsp_y[0];"""),
    ("M92 a long op enters stage 2, so it is released at DISPATCH", F_V2,
     """      s2_valid <= s1_short;""",
     """      s2_valid <= s1_valid;"""),
    ("M93 a REFUSED op is counted as retired", F_V2,
     """  wire                retire_s2   = s2_valid && !s2_unsup;""",
     """  wire                retire_s2   = s2_valid;"""),
    ("M94 the unit is given the LIVE mode rather than the captured one", F_LMUX,
     """  assign u_mode_o    = mode_q;""",
     """  assign u_mode_o    = (lane == '0) ? req_mode_i : mode_q;"""),
    ("M95 a request retires without the serialiser having accepted it", F_V2,
     """      end else if (lq_valid && lm_req_ready) begin""",
     """      end else if (lq_valid || !lm_req_ready) begin"""),
    # M96 is the interlock the sweep itself produced. M93/M94/M95 survived the
    # single-wavefront sections, section 8 was written to reach them, and it
    # HUNG on the shipped RTL: the two-cycle-late guard below let a second long
    # op overwrite a pending request. This mutant restores that guard, so the
    # defect can never come back unnoticed.
    ("M96 the long-op interlock reverts to its two-cycle-late form", F_V2,
     """  assign issue_fire = sel_valid && !pc_overrun && !steal_now && !wbq_busy &&
                      !(ins_is_long && long_slot_busy);""",
     """  assign issue_fire = sel_valid && !pc_overrun && !steal_now && !wbq_busy &&
                      !(ins_is_long && long_slot_busy && lq_valid);"""),
    # ---- THE LENGTH FAMILY, and the second read pass -----------------------
    # LEN2/LEN3/DIST2 are the first ops that want more operands than the
    # register file hands out. The core spends one clock redirecting its three
    # read ports at {a+1, a+2, b+1} rather than growing two more ports. Every
    # mutant below attacks that trade: the addresses, the saved first pass, the
    # stall that protects the stolen cycle, and the routing to a SECOND unit.
    ("M97 the steal cycle no longer stalls issue", F_V2,
     """  assign issue_fire = sel_valid && !pc_overrun && !steal_now && !wbq_busy &&
                      !(ins_is_long && long_slot_busy);""",
     """  assign issue_fire = sel_valid && !pc_overrun && !wbq_busy &&
                      !(ins_is_long && long_slot_busy);"""),
    ("M98 the second pass reads from the WRONG base register", F_V2,
     """  wire [RW-1:0] addr_a = steal_now ? RW'(s1_a + RW'(1)) : ins_a_i;""",
     """  wire [RW-1:0] addr_a = steal_now ? RW'(s1_b + RW'(1)) : ins_a_i;"""),
    ("M99 the second pass reads a+1 twice instead of a+1 and a+2", F_V2,
     """  wire [RW-1:0] addr_b = steal_now ? RW'(s1_a + RW'(2)) : ins_b_i;""",
     """  wire [RW-1:0] addr_b = steal_now ? RW'(s1_a + RW'(1)) : ins_b_i;"""),
    ("M100 the first pass's a is not saved before the steal overwrites it", F_V2,
     """          s2_a0[l] <= rd_a[l];
          s2_b0[l] <= rd_b[l];""",
     """          s2_a0[l] <= rd_b[l];
          s2_b0[l] <= rd_b[l];"""),
    ("M101 a length dispatches from stage 1, before its second pass lands", F_V2,
     """      if (s1_is_curve || s1_is_ring || s1_is_ridge) begin
        lq_valid <= 1'b1;""",
     """      if (s1_is_long) begin
        lq_valid <= 1'b1;"""),
    ("M102 the interlock forgets the length's dispatch window", F_V2,
     """  wire long_slot_busy = lq_valid || (s1_valid && s1_is_long) || steal_now || steal_q;""",
     """  wire long_slot_busy = lq_valid || (s1_valid && s1_is_long);"""),
    ("M103 the steal reads the wrong wavefront's registers", F_V2,
     """  wire [WFW-1:0] rd_wf = steal_now ? s1_wf : sel;""",
     """  wire [WFW-1:0] rd_wf = sel;"""),
    ("M104 every long op is routed to the curve unit", F_V2,
     """  wire to_len  = (u_unit == UNIT_LEN);""",
     """  wire to_len  = (u_unit != UNIT_LEN);"""),
    ("M105 the multiplier is always given the curve unit's request", F_V2,
     """    end else if (to_len) begin
      mul_issue = ln_mul_issue;
      mul_a     = ln_mul_a;
      mul_b     = ln_mul_b;
    end else begin
      mul_issue = cv_mul_issue;
      mul_a     = cv_mul_a;
      mul_b     = cv_mul_b;
    end""",
     """    end else if (to_len) begin
      mul_issue = cv_mul_issue;
      mul_a     = cv_mul_a;
      mul_b     = cv_mul_b;
    end else begin
      mul_issue = ln_mul_issue;
      mul_a     = ln_mul_a;
      mul_b     = ln_mul_b;
    end"""),
    ("M106 the length's saturation never reaches the ledger", F_V2,
     """      if (cv_sat_add  || ln_sat_add  || rg_sat_add ||
          nz_sat_add   || rt_sat_add)                 sat_add_o     <= 1'b1;""",
     """      if ((cv_sat_add || rg_sat_add || nz_sat_add || rt_sat_add) &&
          ln_sat_add)                                 sat_add_o     <= 1'b1;"""),
    ("M107 LEN3 and DIST2 collapse to LEN2's mode", F_V2,
     """      OP_LEN3:   begin s1_mode = 2'd1; s1_unit = UNIT_LEN;   end
      OP_DIST2:  begin s1_mode = 2'd2; s1_unit = UNIT_LEN;   end""",
     """      OP_LEN3:   begin s1_mode = 2'd0; s1_unit = UNIT_LEN;   end
      OP_DIST2:  begin s1_mode = 2'd0; s1_unit = UNIT_LEN;   end"""),
    # ---- the serialiser's operand bundle ------------------------------------
    ("M108 a bundle component is taken LIVE rather than carried", F_LMUX,
     """  assign u_a1_o      = a1_q[lane];""",
     """  assign u_a1_o      = (lane == '0) ? req_a1_i[lane] : a1_q[lane];"""),
    ("M109 two bundle components are crossed", F_LMUX,
     """  assign u_a1_o      = a1_q[lane];
  assign u_a2_o      = a2_q[lane];""",
     """  assign u_a1_o      = a2_q[lane];
  assign u_a2_o      = a1_q[lane];"""),
    ("M110 the unit selector is taken LIVE rather than carried", F_LMUX,
     """  assign u_unit_o    = unit_q;""",
     """  assign u_unit_o    = (lane == '0) ? req_unit_i : unit_q;"""),
    ("M111 every lane is shown lane 0's b operand", F_LMUX,
     """  assign u_b0_o      = b0_q[lane];""",
     """  assign u_b0_o      = b0_q[0];"""),
    # ---- RING: a third unit, and the multiplier's PRIORITY CHAIN -----------
    # RING is the first operation with two consumers inside it -- the ring unit
    # and the reciprocal it calls twice -- so the multiplier stopped being a mux
    # and became a priority chain. These attack the routing, the operands, that
    # chain, and RING's ledger lanes. The ledger ones exist because M106 proved
    # a unit can be value-correct and account-wrong, and nothing noticed.
    ("M112 RING is routed to whichever unit is not RING", F_V2,
     """  wire to_ring  = (u_unit == UNIT_RING);""",
     """  wire to_ring  = (u_unit != UNIT_RING);"""),
    ("M113 RING's inner radius is handed the outer one", F_V2,
     """          lq_a1[l] <= (s1_is_ring || s1_is_ridge) ? rd_b[l] : 32'sd0;""",
     """          lq_a1[l] <= (s1_is_ring || s1_is_ridge) ? rd_c[l] : 32'sd0;"""),
    ("M114 the reciprocal loses its precedence on the multiplier", F_V2,
     """    if (rc_mul_issue) begin
      mul_issue = rc_mul_issue;
      mul_a     = rc_mul_a;
      mul_b     = rc_mul_b;
    end else if (to_norm) begin""",
     """    if (to_ring && rg_mul_issue) begin
      mul_issue = rg_mul_issue;
      mul_a     = rg_mul_a;
      mul_b     = rg_mul_b;
    end else if (rc_mul_issue) begin
      mul_issue = rc_mul_issue;
      mul_a     = rc_mul_a;
      mul_b     = rc_mul_b;
    end else if (to_norm) begin"""),
    ("M115 the band's two radii are swapped at the unit", F_V2,
     """      .d_i(u_a), .r0_i(u_a1), .r1_i(u_a2),""",
     """      .d_i(u_a), .r0_i(u_a2), .r1_i(u_a1),"""),
    ("M116 a reciprocal of zero reaches the ledger only if BOTH report it", F_V2,
     """      if (rg_rcp0    || rc_rcp0    || nm_rcp0)       rcp_zero_o    <= 1'b1;""",
     """      if (rg_rcp0    && rc_rcp0    || nm_rcp0)       rcp_zero_o    <= 1'b1;"""),
    ("M117 RING's multiply saturation reaches the ledger only beside a curve's", F_V2,
     """      if (cv_sat_mul  || rg_sat_mul  || rt_sat_mul)  sat_mul_o     <= 1'b1;""",
     """      if (cv_sat_mul  && rg_sat_mul  || rt_sat_mul)  sat_mul_o     <= 1'b1;"""),
    ("M118 RING never dispatches at all", F_V2,
     """      if (s1_is_curve || s1_is_ring || s1_is_ridge) begin""",
     """      if (s1_is_curve || s1_is_ridge) begin"""),
    # ---- the IMMEDIATE, and RIDGE ------------------------------------------
    # v2's instruction word grew its first new field since the engine was
    # written. The immediate is a hash SEED here and an AXIS SELECT for ROT3
    # later, and the axis is the dangerous one: dropped, it rotates about the
    # wrong axis and the world stays plausible. These attack the capture, the
    # carry, the routing and the mode.
    ("M119 the immediate is taken LIVE rather than carried", F_LMUX,
     """  assign u_imm_o     = imm_q;""",
     """  assign u_imm_o     = (lane == '0) ? req_imm_i : imm_q;"""),
    ("M120 the immediate loses its low half on the way to the unit", F_V2,
     """        lq_imm   <= s1_imm;""",
     """        lq_imm   <= s1_imm & 32'hFFFF_0000;"""),
    ("M121 RIDGE is routed to whichever unit is not the noise unit", F_V2,
     """  wire to_noise = (u_unit == UNIT_NOISE);""",
     """  wire to_noise = (u_unit != UNIT_NOISE);"""),
    ("M122 RIDGE's second coordinate is never carried", F_V2,
     """          lq_a1[l] <= (s1_is_ring || s1_is_ridge) ? rd_b[l] : 32'sd0;""",
     """          lq_a1[l] <= s1_is_ring ? rd_b[l] : 32'sd0;"""),
    ("M123 the noise unit is always told it is NOISE2, never RIDGE", F_V2,
     """      .is_ridge_i(u_mode[0]),""",
     """      .is_ridge_i(1'b0),"""),
    ("M124 the noise unit's saturation reaches the ledger only beside another", F_V2,
     """      if (cv_sat_add  || ln_sat_add  || rg_sat_add ||
          nz_sat_add   || rt_sat_add)                 sat_add_o     <= 1'b1;""",
     """      if ((cv_sat_add || ln_sat_add || rg_sat_add || rt_sat_add) &&
          nz_sat_add)                                 sat_add_o     <= 1'b1;"""),
    # ---- THE MULTI-RESULT REPLY, and NOISE2 as its first user --------------
    # Every long op before NOISE2 returned one value. Four of the remaining six
    # return two or three, and they write CONSECUTIVE registers -- which is
    # exactly where the next instruction's operands live, so a write that lands
    # in the wrong place or does not land at all is a wrong answer somewhere
    # else entirely.
    ("M125 a multi-result op writes only its first register", F_V2,
     """        wbq_cnt <= lm_rsp_nres;""",
     """        wbq_cnt <= (lm_rsp_nres != 2'd0) ? 2'd1 : 2'd0;"""),
    ("M126 the two results are swapped between dst and dst+1", F_V2,
     """          wbq_y[l][0] <= lm_rsp_y[l];
          wbq_y[l][1] <= lm_rsp_y1[l];""",
     """          wbq_y[l][0] <= lm_rsp_y1[l];
          wbq_y[l][1] <= lm_rsp_y[l];"""),
    ("M127 the second result lands on dst instead of dst+1", F_V2,
     """      wb_addr = {wbq_wf, RW'(wbq_dst + RW'(wbq_idx))};""",
     """      wb_addr = {wbq_wf, wbq_dst};"""),
    ("M128 every op claims a single result", F_V2,
     """  wire [1:0]  s1_nres = (s1_is_rot3 || s1_is_nrm3)              ? 2'd3
                      : (s1_is_noise2 || s1_is_rot2 || s1_is_nrm2) ? 2'd2
                                                                   : 2'd1;""",
     """  wire [1:0]  s1_nres = (s1_is_rot3 || s1_is_nrm3)              ? 2'd1
                      : (s1_is_noise2 || s1_is_rot2 || s1_is_nrm2) ? 2'd1
                                                                   : 2'd1;"""),
    ("M129 the second read pass is for lengths only again", F_V2,
     """  wire s1_needs_pass2 = s1_is_len || s1_is_noise2 || s1_is_rot || s1_is_nrm;""",
     """  wire s1_needs_pass2 = s1_is_len || s1_is_rot || s1_is_nrm;"""),
    ("M130 the pass-2 path still hard-wires the length unit", F_V2,
     """        lq_unit  <= ln_unit;
        lq_nres  <= ln_nres;""",
     """        lq_unit  <= ln_unit ^ 3'd1;
        lq_nres  <= ln_nres;"""),
    ("M131 a pass-2 op loses its immediate", F_V2,
     """        lq_imm   <= ln_imm;  // NOISE2 takes this path AND reads a seed""",
     """        lq_imm   <= ~ln_imm;"""),
    # ---- the serialiser's half of it ---------------------------------------
    ("M132 the result count is taken LIVE rather than carried", F_LMUX,
     """  assign rsp_nres_o  = nres_q;""",
     """  assign rsp_nres_o  = (state == S_DONE) ? req_nres_i : nres_q;"""),
    ("M133 the second result lane is captured for the NEXT lane", F_LMUX,
     """          y1_q[lane] <= u_result1_i;""",
     """          y1_q[(lane + LW'(1)) & LW'(LANES-1)] <= u_result1_i;"""),
    ("M134 the reply carries lane 0's second result to every lane", F_LMUX,
     """      rsp_y1_o[l] = y1_q[l];""",
     """      rsp_y1_o[l] = y1_q[0];"""),
    # ---- ROT2/ROT3, the sine table, and the widened unit selector ----------
    # ROT3's immediate is an AXIS. A dropped axis still rotates the right vector
    # by the right angle, so it is a plausible world -- these attack the axis,
    # the mode, the angle's source, the third register, and the fifth shared
    # resource.
    ("M135 the axis is dropped and every ROT3 rotates about X", F_V2,
     """      .is_rot3_i(u_mode[0]), .axis_i(u_imm[1:0]),""",
     """      .is_rot3_i(u_mode[0]), .axis_i(2'(u_imm[1:0] & 2'd0)),"""),
    ("M136 ROT3 is told it is ROT2", F_V2,
     """      .is_rot3_i(u_mode[0]), .axis_i(u_imm[1:0]),""",
     """      .is_rot3_i(1'b0), .axis_i(u_imm[1:0]),"""),
    ("M137 ROT2 writes a third register it does not own", F_V2,
     """  wire [1:0]  s1_nres = (s1_is_rot3 || s1_is_nrm3)              ? 2'd3
                      : (s1_is_noise2 || s1_is_rot2 || s1_is_nrm2) ? 2'd2
                                                                   : 2'd1;""",
     """  wire [1:0]  s1_nres = (s1_is_rot3 || s1_is_nrm3 || s1_is_rot2) ? 2'd3
                      : (s1_is_noise2 || s1_is_nrm2)              ? 2'd2
                                                                  : 2'd1;"""),
    ("M138 the rotation angle is read from the wrong register", F_V2,
     """      .ang_i(u_b0),""",
     """      .ang_i(u_a),"""),
    ("M139 the sine table is asked for cosine and back again", F_V2,
     """      .clk(clk), .angle_i(rt_sin_angle), .is_cos_i(rt_sin_is_cos),""",
     """      .clk(clk), .angle_i(rt_sin_angle), .is_cos_i(!rt_sin_is_cos),"""),
    ("M140 ROT is routed to the curve unit's code", F_V2,
     """  wire to_rot   = (u_unit == UNIT_ROT);""",
     """  wire to_rot   = (u_unit == UNIT_CURVE);"""),
    ("M141 ROT's saturation reaches the ledger only beside another", F_V2,
     """      if (cv_sat_mul  || rg_sat_mul  || rt_sat_mul)  sat_mul_o     <= 1'b1;""",
     """      if ((cv_sat_mul || rg_sat_mul) && rt_sat_mul)  sat_mul_o     <= 1'b1;"""),
    ("M142 a rotation never takes its second read pass", F_V2,
     """  wire s1_needs_pass2 = s1_is_len || s1_is_noise2 || s1_is_rot || s1_is_nrm;""",
     """  wire s1_needs_pass2 = s1_is_len || s1_is_noise2 || s1_is_nrm;"""),
    # ---- NORMALIZE2/3, and the square root's SECOND consumer ---------------
    # The isqrt was wired straight to the length unit until normalize arrived.
    # These attack the mux both ways: normalize starved, and the length family
    # starved by normalize -- the second is the one that would pass a test
    # checking only the new opcode.
    ("M143 NORMALIZE3 collapses to NORMALIZE2", F_V2,
     """      .is3_i(u_mode[0]),""",
     """      .is3_i(1'b0),"""),
    ("M144 NORMALIZE2 writes a third register it does not own", F_V2,
     """  wire [1:0]  s1_nres = (s1_is_rot3 || s1_is_nrm3)              ? 2'd3
                      : (s1_is_noise2 || s1_is_rot2 || s1_is_nrm2) ? 2'd2
                                                                   : 2'd1;""",
     """  wire [1:0]  s1_nres = (s1_is_rot3 || s1_is_nrm3 || s1_is_nrm2) ? 2'd3
                      : (s1_is_noise2 || s1_is_rot2)              ? 2'd2
                                                                  : 2'd1;"""),
    ("M145 the square root always answers the length unit", F_V2,
     """  assign isq_valid  = to_norm ? nm_sq_valid  : sq_valid;""",
     """  assign isq_valid  = sq_valid && !nm_sq_valid;"""),
    ("M146 the square root is handed the wrong operand", F_V2,
     """  assign isq_n      = to_norm ? nm_sq_n      : sq_n;""",
     """  assign isq_n      = to_norm ? sq_n         : nm_sq_n;"""),
    ("M147 the length family is starved once normalize exists", F_V2,
     """  assign sq_rvalid  = to_norm ? 1'b0 : isq_rvalid;""",
     """  assign sq_rvalid  = to_norm ? isq_rvalid : 1'b0;"""),
    ("M148 normalize never takes its second read pass", F_V2,
     """  wire s1_needs_pass2 = s1_is_len || s1_is_noise2 || s1_is_rot || s1_is_nrm;""",
     """  wire s1_needs_pass2 = s1_is_len || s1_is_noise2 || s1_is_rot;"""),
    ("M149 normalize's rescale saturation never reaches the ledger", F_V2,
     """      if (cv_sat_resc || ln_sat_resc || rg_sat_resc ||
          nz_sat_resc  || nm_sat_resc)                sat_rescale_o <= 1'b1;""",
     """      if ((cv_sat_resc || ln_sat_resc || rg_sat_resc ||
           nz_sat_resc) && nm_sat_resc)               sat_rescale_o <= 1'b1;"""),
    ("M150 normalize is routed to the rot unit's code", F_V2,
     """  wire to_norm  = (u_unit == UNIT_NORM);""",
     """  wire to_norm  = (u_unit == UNIT_ROT);"""),
    # ---- THE FRONT END: program in, points in, answers out IN ORDER --------
    # The block that makes the engine usable. Its failure modes are not
    # arithmetic, they are SEQUENCING. M151 is the bug that shipped here first:
    # done_o is STICKY from the previous batch and busy_o is low before a
    # wavefront starts, so testing them immediately after a REGISTERED start
    # pulse completes a batch that never executed -- and the drain then returns
    # the PREVIOUS batch's answers.
    ("M151 a batch completes without waiting for its start to land", F_FRONT,
     """        F_RUN: if (!launched) begin
          if ((core_done & started) == '0) launched <= 1'b1;
        end else if (core_busy == '0 && (core_done & started) == started) begin""",
     """        F_RUN: if (launched || (core_busy == '0 &&
                       (core_done & started) == started)) begin"""),
    ("M152 ready fires on the FIRST lane of a point, not the last", F_FRONT,
     """  assign pt_ready_o = (state == F_FILL) && (filled != SW'(SLOTS)) &&
                      (fill_lane + 1 == n_in_i);""",
     """  assign pt_ready_o = (state == F_FILL) && (filled != SW'(SLOTS)) &&
                      (fill_lane == '0);"""),
    ("M153 an input lane is written to the wrong register", F_FRONT,
     """            h_reg   <= RW'(fill_lane);""",
     """            h_reg   <= RW'(fill_lane + 1);"""),
    ("M154 the drain reads the wrong lane of the slot", F_FRONT,
     """  wire [LW-1:0]  h_rlane = drain_ln;""",
     """  wire [LW-1:0]  h_rlane = LW'(drain_ln + LW'(1));"""),
    ("M155 a partial batch launches every wavefront", F_FRONT,
     """            core_start <= WFS'((1 << wf_used) - 1);
            started    <= WFS'((1 << wf_used) - 1);""",
     """            core_start <= {WFS{1'b1}};
            started    <= WFS'((1 << wf_used) - 1);"""),
    ("M156 the drain captures before the address has settled", F_FRONT,
     """              2'd1:    rd_phase <= 2'd2;""",
     """              2'd1:    rd_phase <= 2'd0;"""),
    ("M157 a drained point never advances, so the first repeats", F_FRONT,
     """              drained <= drained + SW'(1);""",
     """              drained <= drained;"""),
    # ---- the register file rebuild, 2026-08-26 -------------------------
    # The file was one array read on four ports and written from four places
    # in one clock. quartus_map measured 121,292 ALMs against a 41,910-ALM
    # device because none of it became memory. It is now four read replicas
    # sharing ONE write port, with the multi-result reply spent one result per
    # clock through a queue. These mutants exist because that machinery is new
    # and none of the mutants above were written against it.
    ("M158 issue is not blocked while the write-back queue drains", F_V2,
     """  assign issue_fire = sel_valid && !pc_overrun && !steal_now && !wbq_busy &&
                      !(ins_is_long && long_slot_busy);""",
     """  assign issue_fire = sel_valid && !pc_overrun && !steal_now &&
                      !(ins_is_long && long_slot_busy);"""),
    ("M159 the queue advances even on a clock the ALU took the write port", F_V2,
     """  wire                wbq_go = wbq_busy && !s2_writes;""",
     """  wire                wbq_go = wbq_busy;"""),
    # M160 moved with the storage: the replicas are module instances now, so
    # "one replica is never written" is a write-enable tied off on one of them.
    ("M160 one replica is never written, so operand b reads stale", F_V2,
     """      zhao_field_rf_ram #(.AW(RFAW), .DW(32)) u_rf_b (
          .clk(clk), .we_i(wb_we[gl]), .waddr_i(wb_addr), .wdata_i(wb_data[gl]),""",
     """      zhao_field_rf_ram #(.AW(RFAW), .DW(32)) u_rf_b (
          .clk(clk), .we_i(1'b0), .waddr_i(wb_addr), .wdata_i(wb_data[gl]),"""),
    ("M161 a host write broadcasts to every lane", F_V2,
     """      wb_we[h_lane_i]   = 1'b1;""",
     """      for (wl = 0; wl < LANES; wl++) wb_we[wl] = 1'b1;"""),
    ("M162 the wavefront is released when the reply ARRIVES, not when it lands", F_V2,
     """        wbq_idx <= 2'd0;""",
     """        wbq_idx <= 2'd0;
        inflight[lm_rsp_wf] <= 1'b0;"""),
    ("M163 the wavefront is released one result before the queue finishes", F_V2,
     """        if (wbq_cnt == 2'd1) inflight[wbq_wf] <= 1'b0;""",
     """        if (wbq_cnt <= 2'd2) inflight[wbq_wf] <= 1'b0;"""),
    ("M164 the two retirements are OR'd, so a simultaneous pair counts once", F_V2,
     """      instr_retired_o <= instr_retired_o + 32'(retire_s2) + 32'(retire_long);""",
     """      instr_retired_o <= instr_retired_o + 32'(retire_s2 | retire_long);"""),

    # ---- the ALU's second stage, 2026-08-27 --------------------------------
    # The multiply moved out of the write clock: stage 1 takes the product,
    # stage 2 rescales, saturates and adds MAD's third operand. Nothing above
    # was written against a stage 2, because until now there was not one.
    ("M165 stage 2 rescales on the LIVE flag rather than the captured one", F_V2,
     """      if (s2_is_mul) begin""",
     """      if (s2_is_mul || alu_is_mul) begin"""),
    ("M166 MAD's addend is taken live, not carried with the product", F_V2,
     """        alu_y[l] = s2_is_mad ? sat_add(q16_fin(s2_pre[l]), s2_c[l])""",
     """        alu_y[l] = s2_is_mad ? sat_add(q16_fin(s2_pre[l]), (s2_is_mad ? rd_c[l] : s2_c[l]))"""),
    ("M167 the product is never rescaled -- Q16.16 becomes Q32.32", F_V2,
     """                             : q16_fin(s2_pre[l]);""",
     """                             : s2_pre[l][31:0];"""),
    ("M168 every lane is given lane 0's product", F_V2,
     """          s2_pre[l] <= alu_pre[l];""",
     """          s2_pre[l] <= alu_pre[0];"""),

]


# ---------------------------------------------------------------------------
# PROVEN EQUIVALENTS
# ---------------------------------------------------------------------------
# The sweep's header has always said survivors are recorded with a PROOF of
# equivalence or they are holes, and that 'probably equivalent' is not a
# category this project has. It said it and enforced it nowhere: a proven
# equivalent and a real gap printed identically.
#
# Keyed by the mutant's id token, which is stable when mutants are inserted;
# indices are not.
#
# THE RULES, enforced in sweep_field_dsp.sh:
#   * declared + SURVIVED -> reported as equivalent with its proof, run passes;
#   * declared + CAUGHT   -> ABORT. The proof is false, and a false proof is
#                            worse than an unproven survivor because it is
#                            believed and stops anyone looking again;
#   * undeclared + SURVIVED -> the run FAILS, exactly as before. That rule is
#                            what stops this becoming a way to launder holes.
EQUIVALENT = {
    # --- the write-back queue's release point, 2026-08-27 -------------------
    'M162':
        "EQUIVALENT, AND ITS GUARD IS TESTED. Clearing inflight[] when the "
        "reply ARRIVES rather than when its last result lands cannot be "
        "observed, because inflight[] only gates WAVEFRONT SELECTION and "
        "issue_fire carries a separate `!wbq_busy` term: while the queue has "
        "anything owed, NO wavefront issues, released or not. So the earliest "
        "instruction that can read the multi-result registers is the same in "
        "both versions -- the clock after the last write. "
        "THIS IS NOT AN UNTESTED ASSUMPTION: M158 removes exactly that "
        "`!wbq_busy` term and IS CAUGHT (19a), so the property this "
        "equivalence rests on has its own mutant. The early release is still "
        "wrong to write -- it makes correctness depend on a term two "
        "expressions away instead of on the release itself -- which is why the "
        "mutant is kept rather than deleted.",
    'M163':
        "EQUIVALENT, for exactly the reason M162 is: releasing one result "
        "early still cannot let the wavefront issue early, because issue is "
        "blocked by `!wbq_busy` until the queue is empty. Same guard, same "
        "proof, and the same mutant (M158) covering it.",
    'M114': 
        "zhao_field_ring asserts rcp_valid_o ONLY in G_SPAN (4'd2) and "
        "mul_issue_o ONLY in G_T/G_T2/G_2T/G_CUBE/G_FIN (4,6,8,10,12), and it "
        "waits in G_SPANW (3) with mul_issue_o low while the reciprocal "
        "computes. The ring and the reciprocal therefore CANNOT drive the "
        "multiplier in the same cycle, so the order of the priority chain is "
        "unobservable. Not a test gap: no test CAN force the contention, "
        "because the unit serialises its own two demands. The chain is kept "
        "because it is v1's and because a future unit may contend.",
    'M116': 
        "SCOPED. zhao_field_ring latches rcp0_o <= rcp0_o || rcp_zero_i, so it "
        "holds whatever the reciprocal reported, and the ring is the "
        "reciprocal's ONLY consumer today. The two lanes always overlap and "
        "&& cannot be told from ||. The || is defensive for a SECOND consumer "
        "and there will be one: OP_RCP, the standalone reciprocal opcode, which "
        "v1 routes to this same unit (zhao_field_exec_shared: rcp_valid = "
        "op_is_ring ? rg_rcp_valid : (v_valid_i && op_is_rcp)). NOT normalize: "
        "zhao_field_normalize has no rcp_* ports at all -- it carries its own "
        "rcp24 ROM and shares only the isqrt. An earlier version of this proof "
        "named NORMALIZE and was WRONG. RE-SCORE THIS "
        "THE MOMENT A SECOND CONSUMER IS WIRED -- it should then be caught, "
        "and if it is not, the OR is genuinely untested.",
}


def _nl(raw):
    return '\r\n' if '\r\n' in raw else '\n'


def files():
    seen = []
    for _, f, _, _ in MUTS:
        if f not in seen:
            seen.append(f)
    return seen


def apply(k):
    name, path, old, new = MUTS[k]
    raw = io.open(path, encoding='utf-8', newline='').read()
    nl = _nl(raw)
    o = old.replace('\n', nl)
    n = new.replace('\n', nl)
    if raw.count(o) != 1:
        sys.stderr.write('%s: ANCHOR NOT UNIQUE (%d) in %s\n' % (name, raw.count(o), path))
        return False
    if o == n:
        sys.stderr.write('%s: MUTANT IDENTICAL TO BASE\n' % name)
        return False
    io.open(path, 'w', encoding='utf-8', newline='').write(raw.replace(o, n, 1))
    os.utime(path, None)   # NOW, never the future -- see the sweep's header
    return True


def main():
    if len(sys.argv) >= 2 and sys.argv[1] == '--count':
        print(len(MUTS))
        return 0
    if len(sys.argv) >= 2 and sys.argv[1] == '--files':
        for f in files():
            print(f)
        return 0
    if len(sys.argv) >= 3 and sys.argv[1] == '--name':
        print(MUTS[int(sys.argv[2])][0])
        return 0
    if len(sys.argv) >= 3 and sys.argv[1] == '--file':
        print(MUTS[int(sys.argv[2])][1])
        return 0
    if len(sys.argv) >= 3 and sys.argv[1] == '--equiv':
        proof = EQUIVALENT.get(sys.argv[2])
        if proof is None:
            return 1
        print(proof)
        return 0
    if len(sys.argv) >= 3 and sys.argv[1] == '--apply':
        return 0 if apply(int(sys.argv[2])) else 9
    sys.stderr.write('usage: --count | --files | --name K | --file K | --apply K\n')
    return 2


if __name__ == '__main__':
    sys.exit(main())
