// zhao_forge_jitter_rom.sv - JITTER_Q16, the FORGE.PRIM.EVAL kink table.
//
// GENERATED by tools/forge/gen_jitter_rom.py -- DO NOT HAND-EDIT.
// The formula lives in the generator; this file and the zref header
// (reference/include/zref/generated/zref_forge_jitter_table.hpp) are its
// two emissions, and tests/forge/forge_jitter_rom_directed.cpp checks every
// entry of this one against that one.
//
// 256 entries, signed fx16 in [-1.0, +1.0) (raw [-65536, +65535], 18 bits).
// Uniform. Indexed by the low 8 bits of the evaluator's xorshift32 stream.
//
// THE SHAPE THAT INFERS M10K (QUARTUS_GOTCHAS S10, same as
// zhao_field_sin_rom): one array, synchronous dual read, NO reset anywhere
// near `tbl` or the outputs -- a reset would hand the entries back to logic.
// 256 x 18 = 4,608 bits, well inside one 10,240-bit M10K in x18 mode.
`default_nettype none

module zhao_forge_jitter_rom (
    input  logic        clk,
    input  logic [7:0]  idx_a_i,
    input  logic [7:0]  idx_b_i,
    output logic [17:0] val_a_o,   // signed fx16, sign in bit 17
    output logic [17:0] val_b_o
);

  logic [17:0] tbl [0:255];

  initial begin
    tbl[  0] = 18'h3553E;
    tbl[  1] = 18'h35E06;
    tbl[  2] = 18'h3B530;
    tbl[  3] = 18'h0E51C;
    tbl[  4] = 18'h3E08B;
    tbl[  5] = 18'h03A78;
    tbl[  6] = 18'h07990;
    tbl[  7] = 18'h3F319;
    tbl[  8] = 18'h3E324;
    tbl[  9] = 18'h3F837;
    tbl[ 10] = 18'h3F961;
    tbl[ 11] = 18'h3E09A;
    tbl[ 12] = 18'h083EE;
    tbl[ 13] = 18'h06E63;
    tbl[ 14] = 18'h3C6F6;
    tbl[ 15] = 18'h33784;
    tbl[ 16] = 18'h36418;
    tbl[ 17] = 18'h3242A;
    tbl[ 18] = 18'h0DA68;
    tbl[ 19] = 18'h08C93;
    tbl[ 20] = 18'h0870A;
    tbl[ 21] = 18'h0167B;
    tbl[ 22] = 18'h30F02;
    tbl[ 23] = 18'h0555E;
    tbl[ 24] = 18'h0DAE2;
    tbl[ 25] = 18'h093B6;
    tbl[ 26] = 18'h3C4B4;
    tbl[ 27] = 18'h0E5C6;
    tbl[ 28] = 18'h0F40E;
    tbl[ 29] = 18'h0BDE4;
    tbl[ 30] = 18'h38BEC;
    tbl[ 31] = 18'h39B53;
    tbl[ 32] = 18'h038D1;
    tbl[ 33] = 18'h33C6B;
    tbl[ 34] = 18'h3B2AF;
    tbl[ 35] = 18'h01165;
    tbl[ 36] = 18'h04C2F;
    tbl[ 37] = 18'h064E9;
    tbl[ 38] = 18'h0E6CD;
    tbl[ 39] = 18'h3A007;
    tbl[ 40] = 18'h30D54;
    tbl[ 41] = 18'h09A5F;
    tbl[ 42] = 18'h3737F;
    tbl[ 43] = 18'h3389C;
    tbl[ 44] = 18'h39AF9;
    tbl[ 45] = 18'h32E0C;
    tbl[ 46] = 18'h36E45;
    tbl[ 47] = 18'h3EA67;
    tbl[ 48] = 18'h07C0B;
    tbl[ 49] = 18'h0C939;
    tbl[ 50] = 18'h05C6F;
    tbl[ 51] = 18'h31BBA;
    tbl[ 52] = 18'h09FA4;
    tbl[ 53] = 18'h3D8DE;
    tbl[ 54] = 18'h07A09;
    tbl[ 55] = 18'h05FE6;
    tbl[ 56] = 18'h36AEA;
    tbl[ 57] = 18'h3511C;
    tbl[ 58] = 18'h3D3D3;
    tbl[ 59] = 18'h342E9;
    tbl[ 60] = 18'h3690D;
    tbl[ 61] = 18'h30A9B;
    tbl[ 62] = 18'h3356B;
    tbl[ 63] = 18'h0C2DC;
    tbl[ 64] = 18'h0E333;
    tbl[ 65] = 18'h0A893;
    tbl[ 66] = 18'h089D7;
    tbl[ 67] = 18'h021E7;
    tbl[ 68] = 18'h33B43;
    tbl[ 69] = 18'h09124;
    tbl[ 70] = 18'h382FC;
    tbl[ 71] = 18'h09BCA;
    tbl[ 72] = 18'h0B8BE;
    tbl[ 73] = 18'h38C34;
    tbl[ 74] = 18'h0CE6D;
    tbl[ 75] = 18'h05491;
    tbl[ 76] = 18'h3B152;
    tbl[ 77] = 18'h07D92;
    tbl[ 78] = 18'h02B2A;
    tbl[ 79] = 18'h39199;
    tbl[ 80] = 18'h39CD5;
    tbl[ 81] = 18'h0F719;
    tbl[ 82] = 18'h0F937;
    tbl[ 83] = 18'h3E508;
    tbl[ 84] = 18'h038F6;
    tbl[ 85] = 18'h0049C;
    tbl[ 86] = 18'h0471F;
    tbl[ 87] = 18'h3C111;
    tbl[ 88] = 18'h328D3;
    tbl[ 89] = 18'h30CF2;
    tbl[ 90] = 18'h34223;
    tbl[ 91] = 18'h0417A;
    tbl[ 92] = 18'h33B9F;
    tbl[ 93] = 18'h0C1C9;
    tbl[ 94] = 18'h32781;
    tbl[ 95] = 18'h004F7;
    tbl[ 96] = 18'h06FE9;
    tbl[ 97] = 18'h02127;
    tbl[ 98] = 18'h3FF07;
    tbl[ 99] = 18'h06629;
    tbl[100] = 18'h0BDA5;
    tbl[101] = 18'h34C85;
    tbl[102] = 18'h3D245;
    tbl[103] = 18'h02A37;
    tbl[104] = 18'h3B149;
    tbl[105] = 18'h02B03;
    tbl[106] = 18'h05EB2;
    tbl[107] = 18'h00195;
    tbl[108] = 18'h3AC24;
    tbl[109] = 18'h0CD12;
    tbl[110] = 18'h071C1;
    tbl[111] = 18'h0F9ED;
    tbl[112] = 18'h0526E;
    tbl[113] = 18'h3A908;
    tbl[114] = 18'h0DD7D;
    tbl[115] = 18'h3E2C2;
    tbl[116] = 18'h35F3B;
    tbl[117] = 18'h0FF18;
    tbl[118] = 18'h34008;
    tbl[119] = 18'h335FB;
    tbl[120] = 18'h3F43F;
    tbl[121] = 18'h3C670;
    tbl[122] = 18'h3505B;
    tbl[123] = 18'h00875;
    tbl[124] = 18'h3E4FB;
    tbl[125] = 18'h3DADE;
    tbl[126] = 18'h36225;
    tbl[127] = 18'h055A0;
    tbl[128] = 18'h3DA51;
    tbl[129] = 18'h3BB35;
    tbl[130] = 18'h09334;
    tbl[131] = 18'h0A55C;
    tbl[132] = 18'h0D350;
    tbl[133] = 18'h3CABE;
    tbl[134] = 18'h09196;
    tbl[135] = 18'h05EAC;
    tbl[136] = 18'h064F3;
    tbl[137] = 18'h04FA7;
    tbl[138] = 18'h08D29;
    tbl[139] = 18'h09261;
    tbl[140] = 18'h034F6;
    tbl[141] = 18'h3989A;
    tbl[142] = 18'h0E28F;
    tbl[143] = 18'h04B69;
    tbl[144] = 18'h389E0;
    tbl[145] = 18'h05F26;
    tbl[146] = 18'h0C00B;
    tbl[147] = 18'h3C9FF;
    tbl[148] = 18'h0FCBF;
    tbl[149] = 18'h3714A;
    tbl[150] = 18'h37811;
    tbl[151] = 18'h01003;
    tbl[152] = 18'h35C3B;
    tbl[153] = 18'h076EF;
    tbl[154] = 18'h02978;
    tbl[155] = 18'h0E646;
    tbl[156] = 18'h30144;
    tbl[157] = 18'h3E67D;
    tbl[158] = 18'h029AA;
    tbl[159] = 18'h3FA22;
    tbl[160] = 18'h3CBA4;
    tbl[161] = 18'h3C4F9;
    tbl[162] = 18'h0A915;
    tbl[163] = 18'h03E0B;
    tbl[164] = 18'h3531F;
    tbl[165] = 18'h3AB5F;
    tbl[166] = 18'h054B2;
    tbl[167] = 18'h3F310;
    tbl[168] = 18'h03C0D;
    tbl[169] = 18'h048EC;
    tbl[170] = 18'h0D0C7;
    tbl[171] = 18'h39D52;
    tbl[172] = 18'h30431;
    tbl[173] = 18'h0137D;
    tbl[174] = 18'h09942;
    tbl[175] = 18'h3CBD0;
    tbl[176] = 18'h05BDA;
    tbl[177] = 18'h30939;
    tbl[178] = 18'h0D823;
    tbl[179] = 18'h0DFE4;
    tbl[180] = 18'h03607;
    tbl[181] = 18'h3F89A;
    tbl[182] = 18'h0E6A9;
    tbl[183] = 18'h3969E;
    tbl[184] = 18'h001DD;
    tbl[185] = 18'h06A7D;
    tbl[186] = 18'h06757;
    tbl[187] = 18'h3BA92;
    tbl[188] = 18'h3EBC3;
    tbl[189] = 18'h3FF0A;
    tbl[190] = 18'h301C9;
    tbl[191] = 18'h0749C;
    tbl[192] = 18'h05DE9;
    tbl[193] = 18'h32BA8;
    tbl[194] = 18'h06DD1;
    tbl[195] = 18'h39256;
    tbl[196] = 18'h00894;
    tbl[197] = 18'h3A71E;
    tbl[198] = 18'h385D3;
    tbl[199] = 18'h0F573;
    tbl[200] = 18'h005A0;
    tbl[201] = 18'h0CB42;
    tbl[202] = 18'h37C64;
    tbl[203] = 18'h30D60;
    tbl[204] = 18'h05C5A;
    tbl[205] = 18'h39DAB;
    tbl[206] = 18'h32FD9;
    tbl[207] = 18'h30CF1;
    tbl[208] = 18'h0068E;
    tbl[209] = 18'h0060A;
    tbl[210] = 18'h39E06;
    tbl[211] = 18'h0A3D2;
    tbl[212] = 18'h07B09;
    tbl[213] = 18'h09014;
    tbl[214] = 18'h33493;
    tbl[215] = 18'h31740;
    tbl[216] = 18'h09DAF;
    tbl[217] = 18'h36169;
    tbl[218] = 18'h01F89;
    tbl[219] = 18'h02A0D;
    tbl[220] = 18'h02C74;
    tbl[221] = 18'h3F7C9;
    tbl[222] = 18'h3C696;
    tbl[223] = 18'h38EA8;
    tbl[224] = 18'h031DE;
    tbl[225] = 18'h374E5;
    tbl[226] = 18'h39578;
    tbl[227] = 18'h38B21;
    tbl[228] = 18'h0E245;
    tbl[229] = 18'h0CE80;
    tbl[230] = 18'h3362E;
    tbl[231] = 18'h3FC84;
    tbl[232] = 18'h0D1E3;
    tbl[233] = 18'h32A3D;
    tbl[234] = 18'h39BDB;
    tbl[235] = 18'h36373;
    tbl[236] = 18'h01F95;
    tbl[237] = 18'h03910;
    tbl[238] = 18'h3593D;
    tbl[239] = 18'h3CFAF;
    tbl[240] = 18'h0B51F;
    tbl[241] = 18'h39DAA;
    tbl[242] = 18'h028EC;
    tbl[243] = 18'h04C3B;
    tbl[244] = 18'h06A0C;
    tbl[245] = 18'h07100;
    tbl[246] = 18'h3697D;
    tbl[247] = 18'h320C3;
    tbl[248] = 18'h3C805;
    tbl[249] = 18'h370F6;
    tbl[250] = 18'h3701F;
    tbl[251] = 18'h0A1D6;
    tbl[252] = 18'h3E356;
    tbl[253] = 18'h0D909;
    tbl[254] = 18'h04172;
    tbl[255] = 18'h07271;
  end

  always_ff @(posedge clk) begin
    val_a_o <= tbl[idx_a_i];
    val_b_o <= tbl[idx_b_i];
  end

endmodule : zhao_forge_jitter_rom

`default_nettype wire
